import { Column, TypeColumn } from './table/column.model';

export interface Program {
  id: number; // 1 - 2 ...
  label: string; // Random
  startDate: Date; // Random
  endDate: Date; // Random
  assetType: string[]; // aep_canalisation / aep_vanne
  action: string; // Random action for something like water pipes etc...
  status: string; // CREE / TERMINE / EN_COURS
  viewingPreference: string; // color
  contract: string; // Random string like 'S813E', 'A256B'....
  programRenewal: boolean; // Random between true or false
  periodRenewal: string; // Random string like '1A', '2An', '3A', '3An'.....'XAn'
  creationDate: Date; // Random date
  updateDate: Date; // Random Date
  lastEditor: string; // Random name
  creator: string; // Random name
  comment: string; // Random comment
}

export const PROGRAM_COLUMNS: Column[] = [
  {
    type: TypeColumn.CHECKBOX,
  },
  {
    key: 'label',
    label: 'Libellé',
    type: TypeColumn.TEXT,
  },
  {
    key: 'contract',
    label: 'Contrat',
    type: TypeColumn.TEXT,
  },

  {
    key: 'assetType',
    label: "Type d'asset",
    type: TypeColumn.TEXT,
  },
  {
    key: 'action',
    label: 'Action',
    type: TypeColumn.TEXT,
  },
  {
    key: 'endDate',
    label: 'Date de fin',
    type: TypeColumn.DATE,
  },
  {
    key: 'status',
    label: 'Statut',
    type: TypeColumn.TEXT,
  },
];

export const PROGRAM_TEST_DATA = [
  {
    id: 1,
    label: 'Random Program 1',
    startDate: new Date('2023-01-05'),
    endDate: new Date('2023-01-20'),
    assetType: ['aep_canalisation'],
    action: 'Inspect',
    status: 'CREE',
    viewingPreference: 'color',
    contract: 'S813E',
    programRenewal: true,
    periodRenewal: '2An',
    creationDate: new Date('2022-12-01'),
    updateDate: new Date('2022-12-15'),
    lastEditor: 'John Doe',
    creator: 'Jane Doe',
    comment: 'Testing program 1',
  },
  {
    id: 2,
    label: 'Sample Project 2',
    startDate: new Date('2023-02-10'),
    endDate: new Date('2023-02-28'),
    assetType: ['aep_vanne'],
    action: 'Repair',
    status: 'EN_COURS',
    viewingPreference: 'color',
    contract: 'A256B',
    programRenewal: false,
    periodRenewal: '3A',
    creationDate: new Date('2022-11-15'),
    updateDate: new Date('2022-11-30'),
    lastEditor: 'Alice Smith',
    creator: 'Bob Johnson',
    comment: 'Testing program 2',
  },
  {
    id: 3,
    label: 'Utility Program X',
    startDate: new Date('2023-03-15'),
    endDate: new Date('2023-03-31'),
    assetType: ['aep_canalisation', 'aep_vanne'],
    action: 'Install',
    status: 'TERMINE',
    viewingPreference: 'color',
    contract: 'X789C',
    programRenewal: true,
    periodRenewal: '1A',
    creationDate: new Date('2022-10-20'),
    updateDate: new Date('2022-11-05'),
    lastEditor: 'Eva Williams',
    creator: 'Sam Brown',
    comment: 'Test comment for program 3',
  },
  {
    id: 4,
    label: 'Project Alpha',
    startDate: new Date('2023-04-01'),
    endDate: new Date('2023-04-15'),
    assetType: ['aep_canalisation'],
    action: 'Upgrade',
    status: 'EN_COURS',
    viewingPreference: 'color',
    contract: 'P123Q',
    programRenewal: false,
    periodRenewal: '2An',
    creationDate: new Date('2022-09-05'),
    updateDate: new Date('2022-09-20'),
    lastEditor: 'David Miller',
    creator: 'Sophie Wilson',
    comment: 'Alpha program in progress',
  },
  {
    id: 5,
    label: 'Water System Renewal',
    startDate: new Date('2023-05-01'),
    endDate: new Date('2023-05-31'),
    assetType: ['aep_canalisation'],
    action: 'Inspect',
    status: 'CREE',
    viewingPreference: 'color',
    contract: 'W987Z',
    programRenewal: true,
    periodRenewal: '3A',
    creationDate: new Date('2022-08-10'),
    updateDate: new Date('2022-08-25'),
    lastEditor: 'Grace Johnson',
    creator: 'Michael Davis',
    comment: 'Water system maintenance',
  },
  {
    id: 6,
    label: 'Pipeline Project Y',
    startDate: new Date('2023-06-10'),
    endDate: new Date('2023-06-30'),
    assetType: ['aep_canalisation'],
    action: 'Repair',
    status: 'TERMINE',
    viewingPreference: 'color',
    contract: 'Y456D',
    programRenewal: false,
    periodRenewal: '1A',
    creationDate: new Date('2022-07-15'),
    updateDate: new Date('2022-07-30'),
    lastEditor: 'Olivia Brown',
    creator: 'Daniel White',
    comment: 'Completed pipeline project',
  },
  {
    id: 7,
    label: 'Infrastructure Upgrade',
    startDate: new Date('2023-07-05'),
    endDate: new Date('2023-07-20'),
    assetType: ['aep_vanne'],
    action: 'Upgrade',
    status: 'EN_COURS',
    viewingPreference: 'color',
    contract: 'I789A',
    programRenewal: true,
    periodRenewal: '2An',
    creationDate: new Date('2022-06-01'),
    updateDate: new Date('2022-06-15'),
    lastEditor: 'Sophia Wilson',
    creator: 'William Taylor',
    comment: 'Ongoing infrastructure upgrade',
  },
  {
    id: 8,
    label: 'Project Zeta',
    startDate: new Date('2023-08-01'),
    endDate: new Date('2023-08-15'),
    assetType: ['aep_vanne'],
    action: 'Install',
    status: 'TERMINE',
    viewingPreference: 'color',
    contract: 'Z654B',
    programRenewal: false,
    periodRenewal: '3A',
    creationDate: new Date('2022-05-10'),
    updateDate: new Date('2022-05-25'),
    lastEditor: 'Liam Davis',
    creator: 'Emma Smith',
    comment: 'Completed installation project',
  },
  {
    id: 9,
    label: 'Renewable Energy Program',
    startDate: new Date('2023-09-01'),
    endDate: new Date('2023-09-30'),
    assetType: ['aep_canalisation', 'aep_vanne'],
    action: 'Inspect',
    status: 'CREE',
    viewingPreference: 'color',
    contract: 'R987C',
    programRenewal: true,
    periodRenewal: '1A',
    creationDate: new Date('2022-04-15'),
    updateDate: new Date('2022-04-30'),
    lastEditor: 'Mia Johnson',
    creator: 'Noah Brown',
    comment: 'Testing renewable energy program',
  },
  {
    id: 10,
    label: 'Sewage System Upgrade',
    startDate: new Date('2023-10-05'),
    endDate: new Date('2023-10-20'),
    assetType: ['aep_canalisation'],
    action: 'Upgrade',
    status: 'EN_COURS',
    viewingPreference: 'color',
    contract: 'Y456D',
    programRenewal: false,
    periodRenewal: '1A',
    creationDate: new Date('2022-07-15'),
    updateDate: new Date('2022-07-30'),
    lastEditor: 'Olivia Brown',
    creator: 'Daniel White',
    comment: 'Completed pipeline project',
  },
];
