export enum SettingsTypeEnum {
  PERSONNAL_SETTINGS = 'PERSONNAL_SETTINGS',
  USERS_SETTINGS = 'USERS_SETTINGS',
}

export enum ActionType {
  CREATION = 'CREATION',
  DUPLICATION = 'DUPLICATION',
  MODIFICATION = 'MODIFICATION'
}
