version: '3'

services:
  postgres:
    container_name: postgres_container
    image: postgis/postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: next_canope
    volumes:
       - postgis:/data/postgis
    ports:
      - "5433:5432"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
    postgis:
    pgadmin: