-- VERSION_ALIAS
CREATE TABLE ITV_VERSION_ALIAS (
	label text,
	version text
);

COMMENT ON TABLE ITV_VERSION_ALIAS is 'This table contains the ITV version corresponding to the label in an ITV file';
COMMENT ON COLUMN ITV_VERSION_ALIAS.label is 'Label of the version in an ITV file';
COMMENT ON COLUMN ITV_VERSION_ALIAS.version is 'Version of the ITV';

INSERT INTO ITV_VERSION_ALIAS (label, version) VALUES
('EN 13508-2:2003', '2003'),
('EN13508-2:2003', '2003'),
('2003', '2003'),
('EN 13508-2:2003+A1:2011', '2011'),
('EN13508-2:2003+A1:2011', '2011'),
('EN13508-2:2003 A1', '2011'),
('2011', '2011'),
('EN 13508-2:2011+A1:2011', '2011');


-- VERSION
CREATE TABLE ITV_VERSION (
	version text,
	code text,
	label text,
	parent text,
	type text
);

COMMENT ON TABLE ITV_VERSION is 'This table contains the fields of an ITV';
COMMENT ON COLUMN ITV_VERSION.version is 'Version of the ITV';
COMMENT ON COLUMN ITV_VERSION.code is 'Code of the field';
COMMENT ON COLUMN ITV_VERSION.label is 'Label of the field';
COMMENT ON COLUMN ITV_VERSION.parent is 'Parent of the field';
COMMENT ON COLUMN ITV_VERSION.type is 'Type of the field';

INSERT INTO ITV_VERSION (version, code, label, parent, type) values
('2003','A','code_princ','C','E'),
('2003','AAA','ref_troncon','B',null),
('2003','AAB','ref_depart','B',null),
('2003','AAC','coord_depart','B',null),
('2003','AAD','ref_regard_1','B',null),
('2003','AAE',null,'B',null),
('2003','AAF','ref_regard_2','B',null),
('2003','AAG',null,'B',null),
('2003','AAH',null,'B','N'),
('2003','AAI',null,'B',null),
('2003','AAJ','desc_emplacement','B',null),
('2003','AAK','type_sens_inspection','B','E'),
('2003','AAL','type_emplacement','B','E'),
('2003','AAM','autorite_resp','B',null),
('2003','AAN','secteur','B',null),
('2003','AAO',null,'B',null),
('2003','AAP','nom_reseau','B',null),
('2003','AAQ','type_propriete_fonciere','B','E'),
('2003','ABA','version','B',null),
('2003','ABB','syst_codage','B',null),
('2003','ABC','type_point_ref','B','E'),
('2003','ABE',null,'B','E'),
('2003','ABF','date_saisie','B','D'),
('2003','ABG','heure_inspection','B','H'),
('2003','ABH','inspecteur','B',null),
('2003','ABI','fct_inspecteur','B',null),
('2003','ABJ',null,'B',null),
('2003','ABK','type_stockage_video','B','E'),
('2003','ABL','type_stockage_photo','B','E'),
('2003','ABM',null,'B','E'),
('2003','ABN',null,'B',null),
('2003','ABO',null,'B',null),
('2003','ABP','type_objet_inspection','B','E'),
('2003','ABQ','long_prevue','B',null),
('2003','ACA','forme','B','E'),
('2003','ACB','hauteur','B','N'),
('2003','ACC',null,'B','N'),
('2003','ACD','type_materiau','B','E'),
('2003','ACE','type_revetement','B','E'),
('2003','ACF','type_materiau_revetement','B',null),
('2003','ACG','longueur_unitaire','B','N'),
('2003','ACH','radamont','B','N'),
('2003','ACI','radaval','B','N'),
('2003','ACJ','type_collecteur','B','E'),
('2003','ACK','type_effluent','B','E'),
('2003','ACL','position_strategique','B',null),
('2003','ACM','type_nettoyage','B','E'),
('2003','ACN','annee_pose','B',null),
('2003','ADA','type_precipitation','B','E'),
('2003','ADB','type_temperature','B','E'),
('2003','ADC','type_regulation_debit','B','E'),
('2003','ADE','remarque_generale','B',null),
('2003','B','type_caracterisation1','C','E'),
('2003','C','type_caracterisation2','C','E'),
('2003','D','quantification1','C',null),
('2003','E','quantification2','C','N'),
('2003','F','remarques','C',null),
('2003','G','emplac_circonf1','C',null),
('2003','H','emplac_circonf2','C',null),
('2003','I','emplac_long_vert','C','N'),
('2003','J','longueur','C',null),
('2003','K','assemblage','C',null),
('2003','L','restrict_emplac','C',null),
('2003','M','photo','C',null),
('2003','N','video','C',null),
('2011','A','code_princ','C','E'),
('2011','AAA','ref_troncon','B',null),
('2011','AAB','ref_depart','B',null),
('2011','AAC','coord_depart','B',null),
('2011','AAD','ref_regard_1','B',null),
('2011','AAE',null,'B',null),
('2011','AAF','ref_regard_2','B',null),
('2011','AAG',null,'B',null),
('2011','AAH',null,'B','N'),
('2011','AAI',null,'B',null),
('2011','AAJ','desc_emplacement','B',null),
('2011','AAK','type_sens_inspection','B','E'),
('2011','AAL','type_emplacement','B','E'),
('2011','AAM','autorite_resp','B',null),
('2011','AAN','secteur','B',null),
('2011','AAO',null,'B',null),
('2011','AAP','nom_reseau','B',null),
('2011','AAQ','type_propriete_fonciere','B','E'),
('2011','ABA','version','B',null),
('2011','ABB','syst_codage_init','B',null),
('2011','ABC','type_point_ref','B','E'),
('2011','ABE',null,'B','E'),
('2011','ABF','date_saisie','B','D'),
('2011','ABG','heure_inspection','B','H'),
('2011','ABH','inspecteur','B',null),
('2011','ABI','fct_inspecteur','B',null),
('2011','ABJ',null,'B',null),
('2011','ABK','type_stockage_video','B','E'),
('2011','ABL','type_stockage_photo','B','E'),
('2011','ABM',null,'B','E'),
('2011','ABN',null,'B',null),
('2011','ABO',null,'B',null),
('2011','ABP','type_objet_inspection','B','E'),
('2011','ABQ','long_prevue','B','N'),
('2011','ACA','forme','B','E'),
('2011','ACB','hauteur','B','N'),
('2011','ACC',null,'B','N'),
('2011','ACD','type_materiau','B','E'),
('2011','ACE','type_revetement','B','E'),
('2011','ACF','type_materiau_revetement','B',null),
('2011','ACG','longueur_unitaire','B','N'),
('2011','ACH','radamont','B','N'),
('2011','ACI','radaval','B','N'),
('2011','ACJ','type_collecteur','B','E'),
('2011','ACK','type_effluent','B','E'),
('2011','ACL','position_strategique','B',null),
('2011','ACM','type_nettoyage','B','E'),
('2011','ACN','annee_pose','B',null),
('2011','ADA','type_precipitation','B','E'),
('2011','ADB','type_temperature','B','E'),
('2011','ADC','type_regulation_debit','B','E'),
('2011','ADE','remarque_generale','B',null),
('2011','B','type_caracterisation1','C','E'),
('2011','C','type_caracterisation2','C','E'),
('2011','D','quantification1','C',null),
('2011','E','quantification2','C','N'),
('2011','F','remarques','C',null),
('2011','G','emplac_circonf1','C',null),
('2011','H','emplac_circonf2','C',null),
('2011','I','emplac_long_vert','C','N'),
('2011','J','longueur','C',null),
('2011','K','assemblage','C',null),
('2011','L','restrict_emplac','C',null),
('2011','M','photo','C',null),
('2011','N','video','C',null),
('2011','AAT','Référence du noeud 3','B',null),
('2011','AAU','Coordonnées du noeud 3','B',null),
('2011','AAV','Point de départ de l''inspection latérale','B','E'),
('2011','ABR','Format d''images vidéo','B','E'),
('2011','ABS','nom_fichier_video','B',null),
('2011','ABT','Etape de l''inspection','B','E');


-- VERSION_ENUM
CREATE TABLE ITV_VERSION_ENUM (
	version text,
	code text,
	condition text,
	val text,
	type text,
	label text,
	real_version text
);

COMMENT ON TABLE ITV_VERSION_ENUM is 'This table contains the value and condition for each field of an ITV';
COMMENT ON COLUMN ITV_VERSION_ENUM.version is 'Version of the ITV';
COMMENT ON COLUMN ITV_VERSION_ENUM.code is 'Code of the field';
COMMENT ON COLUMN ITV_VERSION_ENUM.condition is 'Condition on the field and value';
COMMENT ON COLUMN ITV_VERSION_ENUM.val is 'Value of the field';
COMMENT ON COLUMN ITV_VERSION_ENUM.type is 'Type of the value';
COMMENT ON COLUMN ITV_VERSION_ENUM.label is 'Label of the value';
COMMENT ON COLUMN ITV_VERSION_ENUM.real_version is 'Sub version in the version';

INSERT INTO ITV_VERSION_ENUM (version, code, condition, val, type, label, real_version) values
('2003','ABC',null,'D',null,'Point central des canalisations entrantes et sortantes',null),
('2003','ABC',null,'Z',null,'Autre',null),
('2003','ABE',null,'A',null,'Inspection directe',null),
('2003','ABE',null,'B',null,'Inspection par une télécaméra',null),
('2003','ABE',null,'C',null,'Inspection à partir du n?ud de départ',null),
('2003','ABK',null,'A',null,'Cassette vidéo VHS',null),
('2003','ABK',null,'B',null,'CD vidéo',null),
('2003','ABK',null,'Z',null,'Autre',null),
('2003','ABL',null,'A',null,'Photographies',null),
('2003','ABL',null,'B',null,'Images fixes d''ordinateur',null),
('2003','ABL',null,'Z',null,'Autre',null),
('2003','ABM',null,'A',null,'Durée d''enregistrement',null),
('2003','ABM',null,'B',null,'Compteur numérique',null),
('2003','ABM',null,'Z',null,'Autre',null),
('2003','ACA',null,'A',null,'Circulaire',null),
('2003','ACA',null,'B',null,'Rectangulaire',null),
('2003','ACA',null,'C',null,'Ovoïde',null),
('2003','ACA',null,'D',null,'En U',null),
('2003','ACA',null,'E',null,'En arc',null),
('2003','ACA',null,'F',null,'Ovale',null),
('2003','ACA',null,'Xx',null,'Section locale définie par l''autorité responsable',null),
('2003','ACA',null,'Z',null,'Autre',null),
('2003','ACE',null,'A',null,'Revêtement intégré lors de la fabrication',null),
('2003','ACE',null,'B',null,'Revêtement projeté',null),
('2003','ACE',null,'C',null,'Revêtement polymérisé sur place',null),
('2003','ACE',null,'D',null,'Revêtements segmentaires',null),
('2003','ACE',null,'E',null,'Revêtement par tuyaux discontinus',null),
('2003','ACE',null,'F',null,'Revêtement par tubage continu',null),
('2003','ACE',null,'G',null,'Revêtement sans espace annulaire',null),
('2003','ACE',null,'H',null,'Revêtement enroulé en spirale',null),
('2003','ACE',null,'Z',null,'Autre',null),
('2003','ACJ',null,'A',null,'Branchement ou collecteur gravitaire',null),
('2003','ACJ',null,'B',null,'Conduite de relèvement',null),
('2003','ACK',null,'A',null,'Eaux usées',null),
('2003','ACK',null,'B',null,'Eaux pluviales',null),
('2003','ACK',null,'C',null,'Unitaire',null),
('2003','ACK',null,'D',null,'Effluents industriels',null),
('2003','ACK',null,'E',null,'Cours d?eau en caniveau',null),
('2003','ACK',null,'Z',null,'Autre',null),
('2003','ACM',null,'A',null,'Le branchement ou le collecteur a été nettoyé avant l''inspection',null),
('2003','ACM',null,'B',null,'Le branchement ou le collecteur n''a pas été nettoyé avant l''inspection',null),
('2003','ADA',null,'A',null,'Pas de précipitations',null),
('2003','ADA',null,'B',null,'Pluie',null),
('2003','ADA',null,'C',null,'Neige fondante ou glace',null),
('2003','ADB',null,'A',null,'Température au-dessus de zéro',null),
('2003','ADB',null,'B',null,'Température au-dessous de zéro',null),
('2003','ADC',null,'A',null,'Aucune mesure prise',null),
('2003','ADC',null,'B',null,'L''écoulement a été obturé en amont',null),
('2003','ADC',null,'C',null,'L''écoulement a été partiellement obturé',null),
('2003','ADC',null,'Z',null,'Autre',null),
('2003','ABP',null,'A',null,'Contrôle finale d''une nouvelle construction',null),
('2003','ABP',null,'B',null,'Fin de la période de garantie',null),
('2003','ABP',null,'C',null,'Inspection de routine de l''état',null),
('2003','ABP',null,'D',null,'Problème structurel suspecté',null),
('2003','ABP',null,'E',null,'Problème opérationnel suspecté',null),
('2003','ABP',null,'F',null,'Problème d''infiltration suspecté',null),
('2003','ABP',null,'G',null,'Contrôle final de travaux de rénovation ou de réparation',null),
('2003','ABP',null,'H',null,'Transfert de propriété',null),
('2003','ABP',null,'I',null,'Planification d''investissement',null),
('2003','ABP',null,'J',null,'Etude par échantillon',null),
('2003','ABP',null,'Z',null,'Autre',null),
('2011','A',null,'AEA',null,null,null),
('2011','A',null,'AEB',null,null,null),
('2011','A',null,'AEC',null,null,null),
('2011','A',null,'AED',null,null,null),
('2011','A',null,'AEE',null,null,null),
('2011','A',null,'AEF',null,null,null),
('2011','A',null,'AEG',null,null,null),
('2011','A',null,'BAA',null,null,null),
('2011','A',null,'BAB',null,null,null),
('2011','A',null,'BAC',null,null,null),
('2011','A',null,'BAD',null,null,null),
('2011','A',null,'BAE',null,null,null),
('2011','A',null,'BAF',null,null,null),
('2011','A',null,'BAG',null,null,null),
('2011','A',null,'BAH',null,null,null),
('2011','A',null,'BAI',null,null,null),
('2011','A',null,'BAJ',null,null,null),
('2011','A',null,'BAK',null,null,null),
('2011','A',null,'BAL',null,null,null),
('2011','A',null,'BAM',null,null,null),
('2011','A',null,'BAN',null,null,null),
('2011','A',null,'BAO',null,null,null),
('2011','A',null,'BAP',null,null,null),
('2011','A',null,'BBA',null,null,null),
('2011','A',null,'BBB',null,null,null),
('2011','A',null,'BBC',null,null,null),
('2011','A',null,'BBD',null,null,null),
('2011','A',null,'BBE',null,null,null),
('2011','A',null,'BBF',null,null,null),
('2011','A',null,'BBG',null,null,null),
('2011','A',null,'BBH',null,null,null),
('2011','A',null,'BCA',null,null,null),
('2011','A',null,'BCB',null,null,null),
('2011','A',null,'BCC',null,null,null),
('2011','A',null,'BCD',null,null,null),
('2011','A',null,'BCE',null,null,null),
('2011','A',null,'BCF',null,null,null),
('2011','A',null,'BDA',null,null,null),
('2011','A',null,'BDB',null,null,null),
('2011','A',null,'BDC',null,null,null),
('2011','A',null,'BDD',null,null,null),
('2011','A',null,'BDE',null,null,null),
('2011','A',null,'BDF',null,null,null),
('2011','A',null,'BDG',null,null,null),
('2011','A',null,'DAA',null,null,null),
('2011','A',null,'DAB',null,null,null),
('2011','A',null,'DAC',null,null,null),
('2011','A',null,'DAD',null,null,null),
('2011','A',null,'DAE',null,null,null),
('2011','A',null,'DAF',null,null,null),
('2011','A',null,'DAG',null,null,null),
('2011','A',null,'DAH',null,null,null),
('2011','A',null,'DAI',null,null,null),
('2011','A',null,'DAJ',null,null,null),
('2011','A',null,'DAK',null,null,null),
('2011','A',null,'DAL',null,null,null),
('2011','A',null,'DAM',null,null,null),
('2011','A',null,'DAN',null,null,null),
('2011','A',null,'DAO',null,null,null),
('2011','A',null,'DAP',null,null,null),
('2011','A',null,'DAQ',null,null,null),
('2011','A',null,'DAR',null,null,null),
('2011','A',null,'DBA',null,null,null),
('2011','A',null,'DBB',null,null,null),
('2011','A',null,'DBC',null,null,null),
('2011','A',null,'DBD',null,null,null),
('2011','A',null,'DBE',null,null,null),
('2011','A',null,'DBF',null,null,null),
('2011','A',null,'DBG',null,null,null),
('2011','A',null,'DBH',null,null,null),
('2011','A',null,'DCA',null,null,null),
('2011','A',null,'DCB',null,null,null),
('2011','A',null,'DCC',null,null,null),
('2011','A',null,'DCD',null,null,null),
('2011','A',null,'DCE',null,null,null),
('2011','A',null,'DCF',null,null,null),
('2011','A',null,'DCG',null,null,null),
('2011','A',null,'DCH',null,null,null),
('2011','A',null,'DCI',null,null,null),
('2011','A',null,'DCJ',null,null,null),
('2011','A',null,'DCK',null,null,null),
('2011','A',null,'DCL',null,null,null),
('2011','A',null,'DCM',null,null,null),
('2011','A',null,'DCN',null,null,null),
('2011','A',null,'DCO',null,null,null),
('2011','A',null,'DDA',null,null,null),
('2011','A',null,'DDB',null,null,null),
('2011','A',null,'DDC',null,null,null),
('2011','A',null,'DDD',null,null,null),
('2011','A',null,'DDE',null,null,null),
('2011','A',null,'DDF',null,null,null),
('2011','A',null,'DDG',null,null,null),
('2011','AAK',null,'A',null,'Aval',null),
('2011','AAK',null,'B',null,'Amont',null),
('2011','AAK',null,'C',null,'Inconnu',null),
('2011','AAL',null,'A',null,'Sous une route',null),
('2011','AAL',null,'B',null,'Sous un trottoir',null),
('2011','AAL',null,'C',null,'Sous l''accotement d''une route',null),
('2011','AAL',null,'D',null,'Dans une autre zone piétonnière',null),
('2011','AAL',null,'E',null,'Dans un champ',null),
('2011','AAL',null,'F',null,'Sous une propriété bâtie',null),
('2011','AAL',null,'G',null,'Sous des jardins',null),
('2011','AAL',null,'H',null,'Sous un bâtiment permanent',null),
('2011','AAL',null,'I',null,'Sous un terrain boisé',null),
('2011','AAL',null,'J',null,'Accès difficile',null),
('2011','AAL',null,'K',null,'Sous une voie navigable',null),
('2011','AAL',null,'Xx',null,'Type spécial défini par l?autorité responsable',null),
('2011','AAL',null,'Z',null,'Autre',null),
('2011','AAQ',null,'A',null,'Bien public',null),
('2011','AAQ',null,'B',null,'Bien privé',null),
('2011','AAQ',null,'C',null,'Inconnue',null),
('2011','AAV',null,'A',null,'Raccordement au collecteur principal',null),
('2011','AAV',null,'B',null,'Le troisième noeud',null),
('2011','ABC',null,'A',null,'Face intérieure de la paroi du noeud de départ',null),
('2011','ABC',null,'B',null,'Intrados du tronçon à l''intérieur du noeud de départ.',null),
('2011','ABC',null,'C',null,'Centre du n?ud de départ',null),
('2011','ABC',null,'D',null,'Point central des canalisations entrantes et sortantes',null),
('2011','ABC',null,'Z',null,'Autre',null),
('2011','ABE',null,'A',null,'Inspection directe',null),
('2011','ABE',null,'B',null,'Inspection par une télécaméra',null),
('2011','ABE',null,'C',null,'Inspection à partir du n?ud de départ',null),
('2011','ABK',null,'A',null,'Cassette vidéo VHS',null),
('2011','ABK',null,'B',null,'CD vidéo',null),
('2011','ABK',null,'C',null,'DVD vidéo',null),
('2011','ABK',null,'D',null,'CD de données',null),
('2011','ABK',null,'E',null,'DVD de données',null),
('2011','ABK',null,'F',null,'Disque dur portable',null),
('2011','ABK',null,'Z',null,'Autre',null),
('2011','ABL',null,'A',null,'Images fixes',null),
('2011','ABL',null,'B',null,'Hors d''usage',null),
('2011','ABL',null,'C',null,'Windows Meta File ? WMF',null),
('2011','ABL',null,'D',null,'Graphic Image File ? GIF',null),
('2011','ABL',null,'E',null,'JPEG',null),
('2011','ABL',null,'Z',null,'Autre',null),
('2011','ABM',null,'A',null,'Durée d''enregistrement',null),
('2011','ABM',null,'B',null,'Compteur numérique',null),
('2011','ABM',null,'Z',null,'Autre',null),
('2011','ABP',null,'A',null,'Contrôle finale d''une nouvelle construction',null),
('2011','ABP',null,'B',null,'Fin de la période de garantie',null),
('2011','ABP',null,'C',null,'Inspection de routine de l''état',null),
('2011','ABP',null,'D',null,'Problème structurel suspecté',null),
('2011','ABP',null,'E',null,'Problème opérationnel suspecté',null),
('2011','ABP',null,'F',null,'Problème d''infiltration suspecté',null),
('2011','ABP',null,'G',null,'Contrôle final de travaux de rénovation ou de réparation',null),
('2011','ABP',null,'H',null,'Transfert de propriété',null),
('2011','ABP',null,'I',null,'Planification d''investissement',null),
('2011','ABP',null,'J',null,'Etude par échantillon',null),
('2011','ABP',null,'Z',null,'Autre',null),
('2011','ABR',null,'A',null,'Type fixe sur support',null),
('2011','ABR',null,'B',null,'MPEG1',null),
('2011','ABR',null,'C',null,'MPEG2',null),
('2011','ABR',null,'D',null,'MPEG4',null),
('2011','ABR',null,'Z',null,'Autre',null),
('2011','ABT',null,'A',null,'De l''autorité responsable à l''inspecteur',null),
('2011','ABT',null,'B',null,'De l''inspecteur à l''autorité responsable pour étude',null),
('2011','ABT',null,'C',null,'Dans les mains de l''autorité responsable après étude',null),
('2011','ABT',null,'Z',null,'Autre',null),
('2011','ACA',null,'A',null,'Circulaire',null),
('2011','ACA',null,'B',null,'Rectangulaire',null),
('2011','ACA',null,'C',null,'Ovoïde',null),
('2011','ACA',null,'D',null,'En U',null),
('2011','ACA',null,'E',null,'En arc',null),
('2011','ACA',null,'F',null,'Ovale',null),
('2011','ACA',null,'Xx',null,'Section locale définie par l''autorité responsable',null),
('2011','ACA',null,'Z',null,'Autre',null),
('2011','ACD',null,'AA',null,'Amiante-ciment',null),
('2011','ACD',null,'AB',null,'Bitume',null),
('2011','ACD',null,'AC',null,'Fibres projetées',null),
('2011','ACD',null,'AD',null,'Briquetage',null),
('2011','ACD',null,'AE',null,'Grès',null),
('2011','ACD',null,'AF',null,'Mortier de ciment',null),
('2011','ACD',null,'AG',null,'Béton',null),
('2011','ACD',null,'AH',null,'Béton armé',null),
('2011','ACD',null,'AI',null,'Béton projeté',null),
('2011','ACD',null,'AJ',null,'Segments de béton',null),
('2011','ACD',null,'AK',null,'Fibres-ciment',null),
('2011','ACD',null,'AL',null,'Plastiques renforcés de fibres',null),
('2011','ACD',null,'AM',null,'Fonte',null),
('2011','ACD',null,'AN',null,'Fonte grise',null),
('2011','ACD',null,'AO',null,'Fonte ductile',null),
('2011','ACD',null,'AP',null,'Acier',null),
('2011','ACD',null,'AQ',null,'Type de fer ou d''acier non identifié',null),
('2011','ACD',null,'AR',null,'Maçonnerie (appareillée)',null),
('2011','ACD',null,'AS',null,'Maçonnerie (non appareillée)',null),
('2011','ACD',null,'AT',null,'Epoxy',null),
('2011','ACD',null,'AU',null,'Polyester',null),
('2011','ACD',null,'AV',null,'Polyéthylène',null),
('2011','ACD',null,'AW',null,'Polyproylène',null),
('2011','ACD',null,'AX',null,'PVC-U',null),
('2011','ACD',null,'AY',null,'Type de plastique non identifié',null),
('2011','ACD',null,'AZ',null,'Matériau non identifié',null),
('2011','ACD',null,'Z',null,'Autre',null),
('2011','ACE',null,'A',null,'Revêtement intégré lors de la fabrication',null),
('2011','ACE',null,'B',null,'Revêtement projeté',null),
('2011','ACE',null,'C',null,'Revêtement polymérisé sur place',null),
('2011','ACE',null,'D',null,'Revêtements segmentaires',null),
('2011','ACE',null,'E',null,'Revêtement par tuyaux discontinus',null),
('2011','ACE',null,'F',null,'Revêtement par tubage continu',null),
('2011','ACE',null,'G',null,'Revêtement sans espace annulaire',null),
('2011','ACE',null,'H',null,'Revêtement enroulé en spirale',null),
('2011','ACE',null,'X',null,'Pas de revêtement',null),
('2011','ACE',null,'Z',null,'Autre',null),
('2011','ACF',null,'AA',null,'Amiante-ciment',null),
('2011','ACF',null,'AB',null,'Bitume',null),
('2011','ACF',null,'AC',null,'Fibres projetées',null),
('2011','ACF',null,'AD',null,'Briquetage',null),
('2011','ACF',null,'AE',null,'Grès',null),
('2011','ACF',null,'AF',null,'Mortier de ciment',null),
('2011','ACF',null,'AG',null,'Béton',null),
('2011','ACF',null,'AH',null,'Béton armé',null),
('2011','ACF',null,'AI',null,'Béton projeté',null),
('2011','ACF',null,'AJ',null,'Segments de béton',null),
('2011','ACF',null,'AK',null,'Fibres-ciment',null),
('2011','ACF',null,'AL',null,'Plastiques renforcés de fibres',null),
('2011','ACF',null,'AM',null,'Fonte',null),
('2011','ACF',null,'AN',null,'Fonte grise',null),
('2011','ACF',null,'AO',null,'Fonte ductile',null),
('2011','ACF',null,'AP',null,'Acier',null),
('2011','ACF',null,'AQ',null,'Type de fer ou d''acier non identifié',null),
('2011','ACF',null,'AR',null,'Maçonnerie (appareillée)',null),
('2011','ACF',null,'AS',null,'Maçonnerie (non appareillée)',null),
('2011','ACF',null,'AT',null,'Epoxy',null),
('2011','ACF',null,'AU',null,'Polyester',null),
('2011','ACF',null,'AV',null,'Polyéthylène',null),
('2011','ACF',null,'AW',null,'Polyproylène',null),
('2011','ACF',null,'AX',null,'PVC-U',null),
('2011','ACF',null,'AY',null,'Type de plastique non identifié',null),
('2011','ACF',null,'AZ',null,'Matériau non identifié',null),
('2011','ACF',null,'Z',null,'Autre',null),
('2011','ACJ',null,'A',null,'Branchement ou collecteur gravitaire',null),
('2011','ACJ',null,'B',null,'Conduite de relèvement',null),
('2011','ACJ',null,'C',null,'Tuyau d''aspiration',null),
('2011','ACK',null,'A',null,'Eaux usées',null),
('2011','ACK',null,'B',null,'Eaux pluviales',null),
('2011','ACK',null,'C',null,'Unitaire',null),
('2011','ACK',null,'D',null,'Effluents industriels',null),
('2011','ACK',null,'E',null,'Cours d?eau en caniveau',null),
('2011','ACK',null,'F',null,'Drainage souterrain ou agricole',null),
('2011','ACK',null,'Z',null,'Autre',null),
('2011','ACM',null,'A',null,'Le branchement ou le collecteur a été nettoyé avant l''inspection',null),
('2011','ACM',null,'B',null,'Le branchement ou le collecteur n''a pas été nettoyé avant l''inspection',null),
('2011','ADA',null,'A',null,'Pas de précipitations',null),
('2011','ADA',null,'B',null,'Pluie',null),
('2011','ADA',null,'C',null,'Neige fondante ou glace',null),
('2011','ADB',null,'A',null,'Température au-dessus de zéro',null),
('2011','ADB',null,'B',null,'Température au-dessous de zéro',null),
('2011','ADC',null,'A',null,'Aucune mesure prise',null),
('2011','ADC',null,'B',null,'L''écoulement a été obturé en amont',null),
('2011','ADC',null,'C',null,'L''écoulement a été partiellement obturé',null),
('2011','ADC',null,'Z',null,'Autre',null),
('2011','B','A=AEC','A',null,'Circulaire',null),
('2011','B','A=AEC','B',null,'Rectangulaire',null),
('2011','B','A=AEC','C',null,'Ovoïde',null),
('2011','B','A=AEC','D',null,'En U',null),
('2011','B','A=AEC','E',null,'En arc',null),
('2011','B','A=AEC','F',null,'Ovale',null),
('2011','B','A=AEC','Z',null,'Autre forme',null),
('2011','B','A=AED','AA',null,'Amiante-ciment',null),
('2011','B','A=AED','AB',null,'Bitume',null),
('2011','B','A=AED','AC',null,'Fibres projetées',null),
('2011','B','A=AED','AD',null,'Briquetage',null),
('2011','B','A=AED','AE',null,'Grès',null),
('2011','B','A=AED','AF',null,'Mortier de ciment',null),
('2011','B','A=AED','AG',null,'Béton',null),
('2011','B','A=AED','AH',null,'Béton armé',null),
('2011','B','A=AED','AI',null,'Béton projeté',null),
('2011','B','A=AED','AJ',null,'Segments de béton',null),
('2011','B','A=AED','AK',null,'Fibres-ciment',null),
('2011','B','A=AED','AL',null,'Plastiques renforcés de fibres',null),
('2011','B','A=AED','AM',null,'Fonte',null),
('2011','B','A=AED','AN',null,'Fonte grise',null),
('2011','B','A=AED','AO',null,'Fonte ductile',null),
('2011','B','A=AED','AP',null,'Acier',null),
('2011','B','A=AED','AQ',null,'Type de fer ou d''acier non identifié',null),
('2011','B','A=AED','AR',null,'Maçonnerie (appareillée)',null),
('2011','B','A=AED','AS',null,'Maçonnerie (non appareillée)',null),
('2011','B','A=AED','AT',null,'Epoxy',null),
('2011','B','A=AED','AU',null,'Polyester',null),
('2011','B','A=AED','AV',null,'Polyéthylène',null),
('2011','B','A=AED','AW',null,'Polyproylène',null),
('2011','B','A=AED','AX',null,'PVC-U',null),
('2011','B','A=AED','AY',null,'Type de plastique non identifié',null),
('2011','B','A=AED','AZ',null,'Matériau non identifié',null),
('2011','B','A=AED','Z',null,'Autre',null),
('2011','B','A=AEE','A',null,'Revêtement intégré lors de la fabrication',null),
('2011','B','A=AEE','B',null,'Revêtement projeté',null),
('2011','B','A=AEE','C',null,'Revêtement polymérisé sur place',null),
('2011','B','A=AEE','D',null,'Revêtements segmentaires',null),
('2011','B','A=AEE','E',null,'Revêtement par tuyaux discontinus',null),
('2011','B','A=AEE','F',null,'Revêtement par tubage continu',null),
('2011','B','A=AEE','G',null,'Revêtement sans espace annulaire',null),
('2011','B','A=AEE','H',null,'Revêtement enroulé en spirale',null),
('2011','B','A=AEE','Z',null,'Autre revêtement',null),
('2011','B','A=AEG','A',null,'Pas de précipitation',null),
('2011','B','A=AEG','B',null,'Pluie',null),
('2011','B','A=AEG','C',null,'Neige fondante ou glace',null),
('2011','B','A=BAA','A',null,'Verticale',null),
('2011','B','A=BAA','B',null,'Horizontale',null),
('2011','B','A=BAB','A',null,'Micro-fissure',null),
('2011','B','A=BAB','B',null,'Fissure fermée',null),
('2011','B','A=BAB','C',null,'Fissure ouverte',null),
('2011','B','A=BAC','A',null,'Rupture',null),
('2011','B','A=BAC','B',null,'Effondrement partiel',null),
('2011','B','A=BAC','C',null,'Effondrement',null),
('2011','B','A=BAD','A',null,'Déplacé',null),
('2011','B','A=BAD','B',null,'Pièces manquantes',null),
('2011','B','A=BAD','C',null,'Affaissement de radier',null),
('2011','B','A=BAD','D',null,'Effondrement',null),
('2011','B','A=BAF','A',null,'Rugosité accrue',null),
('2011','B','A=BAF','B',null,'Ecaillage (détachement de petits fragments de la surface)',null),
('2011','B','A=BAF','C',null,'Granulats exposés',null),
('2011','B','A=BAF','D',null,'Granulats déchaussés',null),
('2011','B','A=BAF','E',null,'Granulats manquants',null),
('2011','B','A=BAF','F',null,'Armature visible',null),
('2011','B','A=BAF','G',null,'Armature dépassant de la surface',null),
('2011','B','A=BAF','H',null,'Armature corrodée',null),
('2011','B','A=BAF','I',null,'Paroi manquante',null),
('2011','B','A=BAF','J',null,'Produits corrosifs sur la surface',null),
('2011','B','A=BAF','K',null,'Cloquage',null),
('2011','B','A=BAF','Z',null,'Autres dégradations de surface',null),
('2011','B','A=BAH','A',null,'La position du raccordement sur la canalisation est incorrecte',null),
('2011','B','A=BAH','B',null,'Il y a un vide entre l''extrémité de la conduite de raccordement et la canalisation principale',null),
('2011','B','A=BAH','C',null,'Il y a un vide partiel entre l''extrémité de la conduite de raccordement et la canalisation principale',null),
('2011','B','A=BAH','D',null,'La conduite de raccordement est endommagée',null),
('2011','B','A=BAH','E',null,'La conduite de raccordement est obturée',null),
('2011','B','A=BAH','Z',null,'Autre défaut',null),
('2011','B','A=BAI','A',null,'Anneau d''étanchéité',null),
('2011','B','A=BAI','Z',null,'Autre élément d''étanchéité',null),
('2011','B','A=BAJ','A',null,'Déboîtement (longitudinal)',null),
('2011','B','A=BAJ','B',null,'Décentrage (radial)',null),
('2011','B','A=BAJ','C',null,'Déviation (angulaire)',null),
('2011','B','A=BAK','A',null,'Le revêtement de la canalisation s''est détaché',null),
('2011','B','A=BAK','B',null,'Décoloration du revêtement',null),
('2011','B','A=BAK','C',null,'Extrémité du revêtement défectueuse',null),
('2011','B','A=BAK','D',null,'Revêtement ondulé',null),
('2011','B','A=BAK','E',null,'Revêtement cloqué ou renflement interne du revêtement',null),
('2011','B','A=BAK','F',null,'Renflement externe',null),
('2011','B','A=BAK','G',null,'Détachement du revêtement intérieur',null),
('2011','B','A=BAK','H',null,'Détachement du couvre-joint',null),
('2011','B','A=BAK','I',null,'Fissure ou fente (y compris la rupture de soudure)',null),
('2011','B','A=BAK','J',null,'Trou dans le revêtement',null),
('2011','B','A=BAK','K',null,'Défaut de raccordement du revêtement',null),
('2011','B','A=BAK','L',null,'Le matériau de revêtement semble mou',null),
('2011','B','A=BAK','M',null,'Manque de résine dans le stratifié',null),
('2011','B','A=BAK','N',null,'Défaut d?étanchéité entre l?extrémité du revêtement et la conduite d?accueil ou le regard de visite',null),
('2011','B','A=BAK','Z',null,'Autres défauts de revêtement',null),
('2011','B','A=BAL','A',null,'Paroi manquante',null),
('2011','B','A=BAL','B',null,'Une reprise bouchant un trou délébirément pratiqué dans la paroi de la canalisation est devenue défectueuse',null),
('2011','B','A=BAL','C',null,'Détachement du matériau de réparation',null),
('2011','B','A=BAL','D',null,'Matériau de réparation manquant',null),
('2011','B','A=BAL','E',null,'Excès de matériau de réparation',null),
('2011','B','A=BAL','F',null,'Trou dans le matériau de réparation',null),
('2011','B','A=BAL','G',null,'Fissure dans le matériau de réparation',null),
('2011','B','A=BAL','Z',null,'Autre défaut',null),
('2011','B','A=BAM','A',null,'Longitudinal',null),
('2011','B','A=BAM','B',null,'Circonférentiel',null),
('2011','B','A=BAM','C',null,'Hélicoïdal',null),
('2011','B','A=BBA','A',null,'Grosse racine isolée',null),
('2011','B','A=BBA','B',null,'Radicelles',null),
('2011','B','A=BBA','C',null,'Ensemble complexe de racines',null),
('2011','B','A=BBB','A',null,'Concrétions',null),
('2011','B','A=BBB','B',null,'Graisse',null),
('2011','B','A=BBB','C',null,'Encrassement',null),
('2011','B','A=BBB','Z',null,'Autre type de dépôt',null),
('2011','B','A=BBC','A',null,'Fin (p.ex. sable, vase)',null),
('2011','B','A=BBC','B',null,'Grossier (p.ex. gravats, gravier)',null),
('2011','B','A=BBC','C',null,'Dur ou compacté (p.ex. béton)',null),
('2011','B','A=BBC','Z',null,'Autre type de dépôt',null),
('2011','B','A=BBD','A',null,'Sable',null),
('2011','B','A=BBD','B',null,'Tourbe',null),
('2011','B','A=BBD','C',null,'Matériau fin (p.ex. argile, vase)',null),
('2011','B','A=BBD','D',null,'Gravier',null),
('2011','B','A=BBD','Z',null,'Autre type de sol',null),
('2011','B','A=BBE','A',null,'Briquetage ou élément de maçonnerie gisant sur le radier',null),
('2011','B','A=BBE','B',null,'Fragment de conduite d''évacuation et d''assainissement gisant sur le radier',null),
('2011','B','A=BBE','C',null,'Autre objet gisant sur le radier',null),
('2011','B','A=BBE','D',null,'Obstacle dépassant de la paroi',null),
('2011','B','A=BBE','E',null,'Obstacle coincé dans l''assemblage',null),
('2011','B','A=BBE','F',null,'Obstacle traversant un raccordement ou une conduite de raccordement',null),
('2011','B','A=BBE','G',null,'Conduites externes ou câbles insérés dans la canalisation',null),
('2011','B','A=BBE','H',null,'Obstacle intégré à la structure',null),
('2011','B','A=BBE','Z',null,'Autre type d''obstacle',null),
('2011','B','A=BBF','A',null,'Suintement',null),
('2011','B','A=BBF','B',null,'Goutte à goutte',null),
('2011','B','A=BBF','C',null,'Ecoulement',null),
('2011','B','A=BBF','D',null,'Jaillissement',null),
('2011','B','A=BBH','A',null,'Rat',null),
('2011','B','A=BBH','B',null,'Cafard',null),
('2011','B','A=BBH','Z',null,'Autre animal',null),
('2011','B','A=BCA','A',null,'Culotte',null),
('2011','B','A=BCA','B',null,'Selle - carottée',null),
('2011','B','A=BCA','C',null,'Selle - burinée',null),
('2011','B','A=BCA','D',null,'Piquage direct - carotté',null),
('2011','B','A=BCA','E',null,'Piquage direct - buriné',null),
('2011','B','A=BCA','F',null,'Raccord autre que culotte',null),
('2011','B','A=BCA','G',null,'Type de raccord inconnu',null),
('2011','B','A=BCA','Z',null,'Autre type de raccord',null),
('2011','B','A=BCB','A',null,'Remplacement de la conduite',null),
('2011','B','A=BCB','B',null,'Revêtement localisé de conduite',null),
('2011','B','A=BCB','C',null,'Mortier injecté',null),
('2011','B','A=BCB','D',null,'Autre matériau d''étanchéité injecté',null),
('2011','B','A=AEE','X',null,'Pas de RevÃªtement',null),
('2003','A','A=ABL','A',null,'Photographies','EN13508-2:2003'),
('2003','B','A=ABL','A',null,'Images fixes','EN13508-2:2003'),
('2003','A','A=ABL','Z',null,'Autre','EN13508-2:2003'),
('2011','B','A=ABL','A',null,'Images fixes','EN13508-2:2003+A1:2011'),
('2011','B','A=ABL','B',null,'Hors d''usage','EN13508-2:2003+A1:2011'),
('2011','B','A=ABL','C',null,'WMF','EN13508-2:2003+A1:2011'),
('2011','B','A=ABL','D',null,'GIF','EN13508-2:2003+A1:2011'),
('2011','B','A=ABL','E',null,'JPEG','EN13508-2:2003+A1:2011'),
('2011','B','A=ABL','Z',null,'Autre','EN13508-2:2003+A1:2011'),
('2011','B','A=BCB','E',null,'Trou réparé',null),
('2011','B','A=BCB','F',null,'Revêtement localisé de raccordement',null),
('2011','B','A=BCB','G',null,'Autre réparation de raccordement',null),
('2011','B','A=BCB','Z',null,'Autre méthode de réparation sans tranchée',null),
('2011','B','A=BCC','A',null,'Vers la gauche',null),
('2011','B','A=BCC','B',null,'Vers la droite',null),
('2011','B','A=BCD','A',null,'Regard de visite',null),
('2011','B','A=BCD','B',null,'Chambre d''inspection',null),
('2011','B','A=BCD','C',null,'Orifice de nettoyage',null),
('2011','B','A=BCD','D',null,'Orifice de passage de la lampe',null),
('2011','B','A=BCD','E',null,'Déversoir',null),
('2011','B','A=BCD','F',null,'Raccordement important sans regard de visite ou chambre d''inspection',null),
('2011','B','A=BCD','Z',null,'Autre ouvrage spécial',null),
('2011','B','A=BCE','A',null,'Regard de visite',null),
('2011','B','A=BCE','B',null,'Chambre d''inspection',null),
('2011','B','A=BCE','C',null,'Orifice de nettoyage',null),
('2011','B','A=BCE','D',null,'Orifice de passage de la lampe',null),
('2011','B','A=BCE','E',null,'Déversoir',null),
('2011','B','A=BCE','F',null,'Raccordement important sans regard de visite ou chambre d''inspection',null),
('2011','B','A=BCE','Z',null,'Autre ouvrage spécial',null),
('2011','B','A=BDC','A',null,'Obstruction',null),
('2011','B','A=BDC','B',null,'Niveau d''eau trop élevé',null),
('2011','B','A=BDC','C',null,'Panne de l''équipement',null),
('2011','B','A=BDC','Z',null,'Autre cause d''abandon',null),
('2011','B','A=BDD','A',null,'Claires',null),
('2011','B','A=BDD','B',null,'Présentent un aspect discontinu',null),
('2011','B','A=BDD','C',null,'Troubles',null),
('2011','B','A=BDD','D',null,'Colorées',null),
('2011','B','A=BDD','E',null,'Troubles et colorées',null),
('2011','B','A=BDE','A',null,'Clair',null),
('2011','B','A=BDE','B',null,'Présente un aspect discontinu',null),
('2011','B','A=BDE','C',null,'Trouble',null),
('2011','B','A=BDE','D',null,'Coloré',null),
('2011','B','A=BDE','E',null,'Trouble et coloré',null),
('2011','B','A=BDF','A',null,'Manque d''oxygène',null),
('2011','B','A=BDF','B',null,'Sulfure d''hydrogène',null),
('2011','B','A=BDF','C',null,'Méthane',null),
('2011','B','A=BDF','Z',null,'Autre danger',null),
('2011','B','A=BDG','A',null,'Caméra sous l''eau',null),
('2011','B','A=BDG','B',null,'Vase',null),
('2011','B','A=BDG','C',null,'Vapeur',null),
('2011','B','A=BDG','Z',null,'Autre cause',null),
('2011','B','A=CED','AA',null,'Amiante-ciment',null),
('2011','B','A=CED','AB',null,'Bitume',null),
('2011','B','A=CED','AC',null,'Fibres projetées',null),
('2011','B','A=CED','AD',null,'Briquetage',null),
('2011','B','A=CED','AE',null,'Grès',null),
('2011','B','A=CED','AF',null,'Mortier de ciment',null),
('2011','B','A=CED','AG',null,'Béton',null),
('2011','B','A=CED','AH',null,'Béton armé',null),
('2011','B','A=CED','AI',null,'Béton projeté',null),
('2011','B','A=CED','AJ',null,'Segments de béton',null),
('2011','B','A=CED','AK',null,'Fibres-ciment',null),
('2011','B','A=CED','AL',null,'Plastiques renforcés de fibres',null),
('2011','B','A=CED','AM',null,'Fonte',null),
('2011','B','A=CED','AN',null,'Fonte grise',null),
('2011','B','A=CED','AO',null,'Fonte ductile',null),
('2011','B','A=CED','AP',null,'Acier',null),
('2011','B','A=CED','AQ',null,'Type de fer ou d''acier non identifié',null),
('2011','B','A=CED','AR',null,'Maçonnerie (appareillée)',null),
('2011','B','A=CED','AS',null,'Maçonnerie (non appareillée)',null),
('2011','B','A=CED','AT',null,'Epoxy',null),
('2011','B','A=CED','AU',null,'Polyester',null),
('2011','B','A=CED','AV',null,'Polyéthylène',null),
('2011','B','A=CED','AW',null,'Polyproylène',null),
('2011','B','A=CED','AX',null,'PVC-U',null),
('2011','B','A=CED','AY',null,'Type de plastique non identifié',null),
('2011','B','A=CED','AZ',null,'Matériau non identifié',null),
('2011','B','A=CED','Z',null,'Autre',null),
('2011','B','A=DAA','A',null,'Généralisée',null),
('2011','B','A=DAA','B',null,'Localisée',null),
('2011','B','A=DAB','A',null,'Micro-fissure',null),
('2011','B','A=DAB','B',null,'Fissure fermée',null),
('2011','B','A=DAB','C',null,'Fissure ouverte',null),
('2011','B','A=DAC','A',null,'Rupture',null),
('2011','B','A=DAC','B',null,'Effondrement partiel',null),
('2011','B','A=DAC','C',null,'Effondrement',null),
('2011','B','A=DAD','A',null,'Déplacé',null),
('2011','B','A=DAD','B',null,'Pièces manquantes',null),
('2011','B','A=DAD','C',null,'Effondrement',null),
('2011','C','A=DAD','A',null,'Autre couche visible de briquetage ou d''élément de maçonnerie',null),
('2011','C','A=DAD','B',null,'Rien de visible',null),
('2011','B','A=DAF','A',null,'Rugosité accrue',null),
('2011','B','A=DAF','B',null,'Ecaillage (détachement de petits fragments de la surface)',null),
('2011','B','A=DAF','C',null,'Granulats exposés',null),
('2011','B','A=DAF','D',null,'Granulats déchaussés',null),
('2011','B','A=DAF','E',null,'Granulats manquants',null),
('2011','B','A=DAF','F',null,'Armature visible',null),
('2011','B','A=DAF','G',null,'Armature dépassant de la surface',null),
('2011','B','A=DAF','H',null,'Armature corrodée',null),
('2011','B','A=DAF','I',null,'Paroi manquante',null),
('2011','B','A=DAF','J',null,'Produits corrosifs sur la surface',null),
('2011','B','A=DAF','Z',null,'Autres dégradations de surface',null),
('2011','B','A=DAH','A',null,'La position du raccordement sur la canalisation est incorrecte',null),
('2011','B','A=DAH','B',null,'Il y a un vide entre l''extrémité de la conduite de raccordement et la canalisation principale',null),
('2011','B','A=DAH','C',null,'Il y a un vide partiel entre l''extrémité de la conduite de raccordement et la canalisation principale',null),
('2011','B','A=DAH','D',null,'La conduite de raccordement est endommagée',null),
('2011','B','A=DAH','E',null,'La conduite de raccordement est obturée',null),
('2011','B','A=DAH','Z',null,'Autre défaut',null),
('2011','B','A=DAI','A',null,'Anneau d''étanchéité',null),
('2011','B','A=DAI','Z',null,'Autre élément d''étanchéité',null),
('2011','C','A=DAI','A',null,'Visiblement déplacée mais ne dépassant pas dans la chambre',null),
('2011','C','A=DAI','B',null,'Pendante mais non rompue',null),
('2011','C','A=DAI','C',null,'Rompue',null),
('2011','B','A=DAJ','A',null,'Vertical',null),
('2011','B','A=DAJ','B',null,'Horizontal',null),
('2011','B','A=DAJ','C',null,'Angulaire',null),
('2011','B','A=DAK','A',null,'Le revêtement de la canalisation s''est détaché',null),
('2011','B','A=DAK','B',null,'Décoloration du revêtement',null),
('2011','B','A=DAK','C',null,'Extrémité du revêtement défectueuse',null),
('2011','B','A=DAK','D',null,'Revêtement ondulé',null),
('2011','B','A=DAK','E',null,'Revêtement cloqué ou renflement interne du revêtement',null),
('2011','B','A=DAK','Z',null,'Autres défauts de revêtement',null),
('2011','B','A=DAL','A',null,'Paroi manquante',null),
('2011','B','A=DAL','B',null,'Une reprise bouchant un trou délébirément pratiqué dans la paroi de la canalisation est devenue défectueuse',null),
('2011','B','A=DAL','Z',null,'Autre défaut',null),
('2011','B','A=DAM','A',null,'Vertical',null),
('2011','B','A=DAM','B',null,'Horizontal',null),
('2011','B','A=DAM','C',null,'Incliné',null),
('2011','B','A=DAQ','A',null,'Echelon déboîté',null),
('2011','B','A=DAQ','B',null,'Echelon manquant',null),
('2011','B','A=DAQ','C',null,'Echelon corrodé',null),
('2011','B','A=DAQ','D',null,'Echelon faussé',null),
('2011','B','A=DAQ','E',null,'Enreobage plastique brisé',null),
('2011','B','A=DAQ','F',null,'Main-courante de l''échelle corrodée',null),
('2011','B','A=DAQ','G',null,'Support de l''échelle déboîté',null),
('2011','B','A=DAQ','H',null,'Support de l''échelle manquant',null),
('2011','B','A=DAQ','I',null,'Support de l''échelle corrodé',null),
('2011','B','A=DAQ','J',null,'Montant de l''échelle corrodé',null),
('2011','B','A=DAQ','K',null,'Trou dans la paroi défectueux',null),
('2011','B','A=DAQ','Z',null,'Autre défaut',null),
('2011','B','A=DAR','A',null,'Tampon cassé',null),
('2011','B','A=DAR','B',null,'Tampon oscillant',null),
('2011','B','A=DAR','C',null,'Tampon manquant',null),
('2011','B','A=DAR','D',null,'Cadre brisé',null),
('2011','B','A=DAR','E',null,'Cadre déboîté',null),
('2011','B','A=DAR','F',null,'Cadre manquant',null),
('2011','B','A=DAR','G',null,'Tampon au-dessous du niveau de la surface',null),
('2011','B','A=DAR','H',null,'Tampon au-dessus du niveau de la surface',null),
('2011','B','A=DAR','Z',null,'Autre défaut',null),
('2011','B','A=DBA','A',null,'Grosse racine isolée',null),
('2011','B','A=DBA','B',null,'Radicelles',null),
('2011','B','A=DBA','C',null,'Ensemble complexe de racines',null),
('2011','B','A=DBB','A',null,'Concrétions',null),
('2011','B','A=DBB','B',null,'Graisse',null),
('2011','B','A=DBB','C',null,'Encrassement',null),
('2011','B','A=DBB','Z',null,'Autre type de dépôt',null),
('2011','B','A=DBC','A',null,'Fin (p.ex. sable, vase)',null),
('2011','B','A=DBC','B',null,'Grossier (p.ex. gravats, gravier)',null),
('2011','B','A=DBC','C',null,'Dur ou compacté (p.ex. béton)',null),
('2011','B','A=DBC','Z',null,'Autre type de dépôt',null),
('2011','B','A=DBE','A',null,'Briquetage ou élément de maçonnerie détaché',null),
('2011','B','A=DBE','B',null,'Fragment de canalisation brisés',null),
('2011','B','A=DBE','C',null,'Autre objet',null),
('2011','B','A=DBE','D',null,'Obstacle dépassant de la paroi',null),
('2011','B','A=DBE','E',null,'Obstacle coincé dans l''assemblage',null),
('2011','B','A=DBE','F',null,'Obstacle traversant un raccordement ou une conduite de raccordement',null),
('2011','B','A=DBE','G',null,'Conduites externes ou câbles insérés dans la canalisation',null),
('2011','B','A=DBE','Z',null,'Autre type d''obstacle',null),
('2011','B','A=DBF','A',null,'Suintement',null),
('2011','B','A=DBF','B',null,'Goutte à goutte',null),
('2011','B','A=DBF','C',null,'Ecoulement',null),
('2011','B','A=DBF','D',null,'Jaillissement',null),
('2011','C','A=DBF','A',null,'A travers la paroi du regard de visite ou de la chambre d''inspection',null),
('2011','C','A=DBF','B',null,'A travers l''espace entre une conduite de raccordement et la paroi du regard de visite ou de la chambre d''inspection au niveau du radier',null),
('2011','C','A=DBF','C',null,'A travers l''espace entre une conduite de raccordement et la paroi du regard de visite ou de la chambre d''inspection au-dessus de la banquette',null),
('2011','B','A=DBH','A',null,'Rat',null),
('2011','B','A=DBH','B',null,'Cafard',null),
('2011','B','A=DBH','Z',null,'Autre animal',null),
('2011','C','A=DBH','A',null,'Dans le regard de visite ou la chambre d''inspection',null),
('2011','C','A=DBH','B',null,'Dans un raccordement',null),
('2011','C','A=DBH','C',null,'Dans un assemblage ouvert',null),
('2011','C','A=DBH','Z',null,'Autre emplacement',null),
('2011','B','A=DCA','A',null,'Raccordement dans la banquette',null),
('2011','B','A=DCA','B',null,'Chute dans la cunette',null),
('2011','B','A=DCA','C',null,'Chute accompagnée',null),
('2011','B','A=DCA','D',null,'Chute accompagnée verticale interne',null),
('2011','B','A=DCA','E',null,'Chute accompagnée inclinée externe',null),
('2011','B','A=DCA','F',null,'Canalisation d''aération',null),
('2011','B','A=DCA','Z',null,'Autre type de raccordement',null),
('2011','B','A=DCB','A',null,'Remplacement d''une partie de la paroi',null),
('2011','B','A=DCB','B',null,'Revêtement localisé d''un regard de visite ou d''une chambre d''inspection',null),
('2011','B','A=DCB','C',null,'Injection de matériau d''étanchéité',null),
('2011','B','A=DCB','Z',null,'Autre méthode de réparation',null),
('2011','B','A=DCG','A',null,'Circulaire',null),
('2011','B','A=DCG','B',null,'Rectangulaire',null),
('2011','B','A=DCG','C',null,'Ovoïde',null),
('2011','B','A=DCG','D',null,'En U',null),
('2011','B','A=DCG','E',null,'En arc',null),
('2011','B','A=DCG','F',null,'Ovale',null),
('2011','B','A=DCG','Z',null,'Autre forme',null),
('2011','B','A=DCH','A',null,'Banquette défectueuse',null),
('2011','B','A=DCH','B',null,'Banquette correcte',null),
('2011','B','A=DCI','A',null,'Cunette défectueuse',null),
('2011','B','A=DCI','B',null,'Cunette correcte',null),
('2011','B','A=DCJ','A',null,'Chaîne de sécurité présente sans aucun défaut',null),
('2011','B','A=DCJ','B',null,'Chaîne de sécurité manquante',null),
('2011','B','A=DCJ','C',null,'Chaîne de sécurité défectueuse',null),
('2011','B','A=DCJ','D',null,'Chaîne de sécurité en place mais couverte de débris',null),
('2011','B','A=DCJ','E',null,'Barre de sécurité présente sans aucun défaut',null),
('2011','B','A=DCJ','F',null,'Barre de sécurité manquante',null),
('2011','B','A=DCJ','G',null,'Barre de sécurité défectueuse',null),
('2011','B','A=DCJ','H',null,'Barre de sécurité en place mais couverte de débris',null),
('2011','B','A=DCK','A',null,'Déversoir',null),
('2011','B','A=DCK','B',null,'Siphon',null),
('2011','B','A=DCK','C',null,'Orifice',null),
('2011','B','A=DCK','D',null,'Régulateur de tourbillons',null),
('2011','B','A=DCK','E',null,'Vanne d''arrêts',null),
('2011','B','A=DCK','F',null,'Vanne d''arrêts actionnée par flotteur',null),
('2011','B','A=DCK','G',null,'Canal jaugeur',null),
('2011','B','A=DCK','H',null,'Soupape à clapets',null),
('2011','B','A=DCK','I',null,'Ecrans',null),
('2011','B','A=DCK','Z',null,'Autre dispositif de régulation',null),
('2011','B','A=DCL','A',null,'Pas d''accès à la canalisation',null),
('2011','B','A=DCL','B',null,'Accès assuré - Tampon en place',null),
('2011','B','A=DCL','C',null,'Accès assuré - Couvercle manquant',null),
('2011','B','A=DCM','A',null,'Piège présent sans aucun défaut',null),
('2011','B','A=DCM','B',null,'Piège manquant',null),
('2011','B','A=DCM','C',null,'Piège défectueux',null),
('2011','B','A=DCN','A',null,'Bassin non défectueux',null),
('2011','B','A=DCN','B',null,'Bassin défectueux',null),
('2011','B','A=DCO','A',null,'Circulaire',null),
('2011','B','A=DCO','B',null,'Rectangulaire',null),
('2011','B','A=DCO','Z',null,'Autre forme',null),
('2011','B','A=DDC','A',null,'Impossible d''ôter le tampon',null),
('2011','B','A=DDC','B',null,'Obstruction',null),
('2011','B','A=DDC','C',null,'Niveau d''eau trop élevé',null),
('2011','B','A=DDC','D',null,'Panne de l''équipement',null),
('2011','B','A=DDC','Z',null,'Autre cause',null),
('2011','B','A=DDE','A',null,'Clair',null),
('2011','B','A=DDE','B',null,'Présente un aspect discontinu',null),
('2011','B','A=DDE','C',null,'Trouble',null),
('2011','B','A=DDE','D',null,'Décoloré',null),
('2011','B','A=DDE','E',null,'Trouble et coloré',null),
('2011','C','A=DDE','A',null,'Mal raccordée car les eaux usées se déversent dans un branchement ou un collecteur d''eaux de surface',null),
('2011','C','A=DDE','B',null,'Mal raccordée car les eaux usées se déversent dans un branchement ou un collecteur d''eaux usées',null),
('2011','C','A=DDE','C',null,'Aucun mauvais raccordement observé',null),
('2011','B','A=DDF','A',null,'Manque d''oxygène',null),
('2011','B','A=DDF','B',null,'Sulfure d''hydrogène',null),
('2011','B','A=DDF','C',null,'Méthane',null),
('2011','B','A=DDF','Z',null,'Autre danger',null),
('2011','B','A=DDG','A',null,'Caméra sous l''eau',null),
('2011','B','A=DDG','B',null,'Vase',null),
('2011','B','A=DDG','C',null,'Vapeur',null),
('2011','B','A=DDG','Z',null,'Autre cause',null),
('2011','C','A=AEE','AA',null,'Amiante-ciment',null),
('2011','C','A=AEE','AB',null,'Bitume',null),
('2011','C','A=AEE','AC',null,'Fibres projetées',null),
('2011','C','A=AEE','AD',null,'Briquetage',null),
('2011','C','A=AEE','AE',null,'Grès',null),
('2011','C','A=AEE','AF',null,'Mortier de ciment',null),
('2011','C','A=AEE','AG',null,'Béton',null),
('2011','C','A=AEE','AH',null,'Béton armé',null),
('2011','C','A=AEE','AI',null,'Béton projeté',null),
('2011','C','A=AEE','AJ',null,'Segments de béton',null),
('2011','C','A=AEE','AK',null,'Fibres-ciment',null),
('2011','C','A=AEE','AL',null,'Plastiques renforcés de fibres',null),
('2011','C','A=AEE','AM',null,'Fonte',null),
('2011','C','A=AEE','AN',null,'Fonte grise',null),
('2011','C','A=AEE','AO',null,'Fonte ductile',null),
('2011','C','A=AEE','AP',null,'Acier',null),
('2011','C','A=AEE','AQ',null,'Type de fer ou d''acier non identifié',null),
('2011','C','A=AEE','AR',null,'Maçonnerie (appareillée)',null),
('2011','C','A=AEE','AS',null,'Maçonnerie (non appareillée)',null),
('2011','C','A=AEE','AT',null,'Epoxy',null),
('2011','C','A=AEE','AU',null,'Polyester',null),
('2011','C','A=AEE','AV',null,'Polyéthylène',null),
('2011','C','A=AEE','AW',null,'Polyproylène',null),
('2011','C','A=AEE','AX',null,'PVC-U',null),
('2011','C','A=AEE','AY',null,'Type de plastique non identifié',null),
('2011','C','A=AEE','AZ',null,'Matériau non identifié',null),
('2011','C','A=AEE','Z',null,'Autre',null),
('2011','C','A=BAB','A',null,'Longitudinale',null),
('2011','C','A=BAB','B',null,'Circonférentielle',null),
('2011','C','A=BAB','C',null,'Complexe',null),
('2011','C','A=BAB','D',null,'Hélicoïdale',null),
('2011','C','A=BAB','E',null,'Radiale à partir d''un point',null),
('2011','C','A=BAD','A',null,'Autre couche visible de briquetage ou d''élément de maçonnerie',null),
('2011','C','A=BAD','B',null,'Rien de visible',null),
('2011','C','A=BAF','A',null,'Mécanique',null),
('2011','C','A=BAF','B',null,'Chimique - Générale',null),
('2011','C','A=BAF','C',null,'Chimique - Endommagement de la partie supérieure de la conduite',null),
('2011','C','A=BAF','D',null,'Chimique - Endommagement de la partie inférieure de la conduite',null),
('2011','C','A=BAF','E',null,'Aucune cause évidente',null),
('2011','C','A=BAF','Z',null,'Autes causes',null),
('2011','C','A=BAI','A',null,'Visiblement déplacée mais ne dépassant pas dans la conduite',null),
('2011','C','A=BAI','B',null,'Pénétrant mais non rompu - point le plus bas au-dessus de la ligne médiane horizontale',null),
('2011','C','A=BAI','C',null,'Pénétrant mais non rompu - point le plus bas au-dessous de la ligne médiane horizontale',null),
('2011','C','A=BAI','D',null,'Pénétrant et rompu',null),
('2011','C','A=BAK','A',null,'Longitudinale',null),
('2011','C','A=BAK','B',null,'Circonférentielle',null),
('2011','C','A=BAK','C',null,'Complexe',null),
('2011','C','A=BAK','D',null,'Hélicoïdal',null),
('2011','C','A=BAL','A',null,'Longitudinale ',null),
('2011','C','A=BAL','B',null,'Circonférentielle ',null),
('2011','C','A=BAL','C',null,'Complexe ',null),
('2011','C','A=BAL','D',null,'Hélicoïdale ',null),
('2011','C','A=BBH','A',null,'Dans la canalisation',null),
('2011','C','A=BBH','B',null,'Dans un raccordement',null),
('2011','C','A=BBH','C',null,'Dans un assemblage ouvert',null),
('2011','C','A=BBH','Z',null,'Autre emplacement',null),
('2011','C','A=BCA','A',null,'Raccordement ouvert',null),
('2011','C','A=BCA','B',null,'Raccordement fermé',null),
('2011','C','A=BCC','A',null,'Vers le haut',null),
('2011','C','A=BCC','B',null,'Vers le bas',null),
('2011','C','A=BDC','A',null,'Inspection objective terminée',null),
('2011','C','A=BDC','B',null,'Sur instructions de l''autorité responsable ',null),
('2011','C','A=BDC','C',null,'Inspection complémentaire insuffisante',null),
('2011','C','A=BDC','D',null,'Inspection complémentaire peut-être insuffisante',null),
('2011','C','A=BDC','E',null,'Inspection complémentaire suffisante',null),
('2011','C','A=BDC','Z',null,'Autre ',null),
('2011','C','A=BDE','A',null,'Eaux usées dans un branchement ou un collecteur d''eaux de surface',null),
('2011','C','A=BDE','B',null,'Eaux de surface dans un branchement ou un collecteur d''eaux usées',null),
('2011','C','A=BDE','C',null,'Aucun mauvais raccordement observé',null),
('2011','C','A=DAB','A',null,'Verticale',null),
('2011','C','A=DAB','B',null,'Horizontale',null),
('2011','C','A=DAB','C',null,'Complexe',null),
('2011','C','A=DAB','D',null,'Inclinée',null),
('2011','C','A=DAF','A',null,'Mécanique',null),
('2011','C','A=DAF','B',null,'Chimique - Générale',null),
('2011','C','A=DAF','C',null,'Chimique - Endommagement de la partie supérieure de la conduite',null),
('2011','C','A=DAF','D',null,'Chimique - Endommagement de la partie inférieure de la conduite',null),
('2011','C','A=DAF','E',null,'Aucune cause évidente',null),
('2011','C','A=DAK','A',null,'Verticale',null),
('2011','C','A=DAK','B',null,'Horizontale',null),
('2011','C','A=DAK','C',null,'Complexe',null),
('2011','C','A=DCG','A',null,'Raccordement entrant',null),
('2011','C','A=DCG','B',null,'Raccordement sortant',null),
('2011','C','A=DCG','C',null,'Raccordement obturé',null),
('2011','C','A=DCK','A',null,'Contrôle de l''écoulement continu',null),
('2011','C','A=DCK','B',null,'Contrôle du trop-plein',null),
('2011','C','A=DCL','A',null,'Canalisation défectueuse',null),
('2011','C','A=DCL','B',null,'Canalisation non défectueuse',null),
('2011','CCD',null,'AA',null,'Amiante-ciment',null),
('2011','CCD',null,'AB',null,'Bitume',null),
('2011','CCD',null,'AC',null,'Fibres projetées',null),
('2011','CCD',null,'AD',null,'Briquetage',null),
('2011','CCD',null,'AE',null,'Grès',null),
('2011','CCD',null,'AF',null,'Mortier de ciment',null),
('2011','CCD',null,'AG',null,'Béton',null),
('2011','CCD',null,'AH',null,'Béton armé',null),
('2011','CCD',null,'AI',null,'Béton projeté',null),
('2011','CCD',null,'AJ',null,'Segments de béton',null),
('2011','CCD',null,'AK',null,'Fibres-ciment',null),
('2011','CCD',null,'AL',null,'Plastiques renforcés de fibres',null),
('2011','CCD',null,'AM',null,'Fonte',null),
('2011','CCD',null,'AN',null,'Fonte grise',null),
('2011','CCD',null,'AO',null,'Fonte ductile',null),
('2011','CCD',null,'AP',null,'Acier',null),
('2011','CCD',null,'AQ',null,'Type de fer ou d''acier non identifié',null),
('2011','CCD',null,'AR',null,'Maçonnerie (appareillée)',null),
('2011','CCD',null,'AS',null,'Maçonnerie (non appareillée)',null),
('2011','CCD',null,'AT',null,'Epoxy',null),
('2011','CCD',null,'AU',null,'Polyester',null),
('2011','CCD',null,'AV',null,'Polyéthylène',null),
('2011','CCD',null,'AW',null,'Polyproylène',null),
('2011','CCD',null,'AX',null,'PVC-U',null),
('2011','CCD',null,'AY',null,'Type de plastique non identifié',null),
('2011','CCD',null,'AZ',null,'Matériau non identifié',null),
('2011','CCD',null,'Z',null,'Autre',null),
('2011','CCP',null,'AA',null,'Amiante-ciment',null),
('2011','CCP',null,'AB',null,'Bitume',null),
('2011','CCP',null,'AC',null,'Fibres projetées',null),
('2011','CCP',null,'AD',null,'Briquetage',null),
('2011','CCP',null,'AE',null,'Grès',null),
('2011','CCP',null,'AF',null,'Mortier de ciment',null),
('2011','CCP',null,'AG',null,'Béton',null),
('2011','CCP',null,'AH',null,'Béton armé',null),
('2011','CCP',null,'AI',null,'Béton projeté',null),
('2011','CCP',null,'AJ',null,'Segments de béton',null),
('2011','CCP',null,'AK',null,'Fibres-ciment',null),
('2011','CCP',null,'AL',null,'Plastiques renforcés de fibres',null),
('2011','CCP',null,'AM',null,'Fonte',null),
('2011','CCP',null,'AN',null,'Fonte grise',null),
('2011','CCP',null,'AO',null,'Fonte ductile',null),
('2011','CCP',null,'AP',null,'Acier',null),
('2011','CCP',null,'AQ',null,'Type de fer ou d''acier non identifié',null),
('2011','CCP',null,'AR',null,'Maçonnerie (appareillée)',null),
('2011','CCP',null,'AS',null,'Maçonnerie (non appareillée)',null),
('2011','CCP',null,'AT',null,'Epoxy',null),
('2011','CCP',null,'AU',null,'Polyester',null),
('2011','CCP',null,'AV',null,'Polyéthylène',null),
('2011','CCP',null,'AW',null,'Polyproylène',null),
('2011','CCP',null,'AX',null,'PVC-U',null),
('2011','CCP',null,'AY',null,'Type de plastique non identifié',null),
('2011','CCP',null,'AZ',null,'Matériau non identifié',null),
('2011','CCP',null,'Z',null,'Autre',null),
('2003','B','A=AEC','A',null,'Circulaire',null),
('2003','B','A=AEC','B',null,'Rectangulaire',null),
('2003','B','A=AEC','C',null,'Ovoïde',null),
('2003','B','A=AEC','D',null,'En U',null),
('2003','B','A=AEC','E',null,'En arc',null),
('2003','B','A=AEC','F',null,'Ovale',null),
('2003','B','A=AEC','Z',null,'Autre forme',null),
('2003','B','A=AED','AA',null,'Amiante-ciment',null),
('2003','B','A=AED','AB',null,'Bitume',null),
('2003','B','A=AED','AC',null,'Fibres projetées',null),
('2003','B','A=AED','AD',null,'Briquetage',null),
('2003','B','A=AED','AE',null,'Grès',null),
('2003','B','A=AED','AF',null,'Mortier de ciment',null),
('2003','B','A=AED','AG',null,'Béton',null),
('2003','B','A=AED','AH',null,'Béton armé',null),
('2003','B','A=AED','AI',null,'Béton projeté',null),
('2003','B','A=AED','AJ',null,'Segments de béton',null),
('2003','B','A=AED','AK',null,'Fibres-ciment',null),
('2003','B','A=AED','AL',null,'Plastiques renforcés de fibres',null),
('2003','B','A=AED','AM',null,'Fonte',null),
('2003','B','A=AED','AN',null,'Fonte grise',null),
('2003','B','A=AED','AO',null,'Fonte ductile',null),
('2003','B','A=AED','AP',null,'Acier',null),
('2003','B','A=AED','AQ',null,'Type de fer ou d''acier non identifié',null),
('2003','B','A=AED','AR',null,'Maçonnerie (appareillée)',null),
('2003','B','A=AED','AS',null,'Maçonnerie (non appareillée)',null),
('2003','B','A=AED','AT',null,'Epoxy',null),
('2003','B','A=AED','AU',null,'Polyester',null),
('2003','B','A=AED','AV',null,'Polyéthylène',null),
('2003','B','A=AED','AW',null,'Polyproylène',null),
('2003','B','A=AED','AX',null,'PVC-U',null),
('2003','B','A=AED','AY',null,'Type de plastique non identifié',null),
('2003','B','A=AED','AZ',null,'Matériau non identifié',null),
('2003','B','A=AED','Z',null,'Autre',null),
('2003','B','A=AEE','A',null,'Revêtement intégré lors de la fabrication',null),
('2003','B','A=AEE','B',null,'Revêtement projeté',null),
('2003','B','A=AEE','C',null,'Revêtement polymérisé sur place',null),
('2003','B','A=AEE','D',null,'Revêtements segmentaires',null),
('2003','B','A=AEE','E',null,'Revêtement par tuyaux discontinus',null),
('2003','B','A=AEE','F',null,'Revêtement par tubage continu',null),
('2003','B','A=AEE','G',null,'Revêtement sans espace annulaire',null),
('2003','B','A=AEE','H',null,'Revêtement enroulé en spirale',null),
('2003','B','A=AEE','X',null,'Pas de revêtement',null),
('2003','B','A=AEE','Z',null,'Autre revêtement',null),
('2003','C','A=AEE','AA',null,'Amiante-ciment',null),
('2003','C','A=AEE','AB',null,'Bitume',null),
('2003','C','A=AEE','AC',null,'Fibres projetées',null),
('2003','C','A=AEE','AD',null,'Briquetage',null),
('2003','C','A=AEE','AE',null,'Grès',null),
('2003','C','A=AEE','AF',null,'Mortier de ciment',null),
('2003','C','A=AEE','AG',null,'Béton',null),
('2003','C','A=AEE','AH',null,'Béton armé',null),
('2003','C','A=AEE','AI',null,'Béton projeté',null),
('2003','C','A=AEE','AJ',null,'Segments de béton',null),
('2003','C','A=AEE','AK',null,'Fibres-ciment',null),
('2003','C','A=AEE','AL',null,'Plastiques renforcés de fibres',null),
('2003','C','A=AEE','AM',null,'Fonte',null),
('2003','C','A=AEE','AN',null,'Fonte grise',null),
('2003','C','A=AEE','AO',null,'Fonte ductile',null),
('2003','C','A=AEE','AP',null,'Acier',null),
('2003','C','A=AEE','AQ',null,'Type de fer ou d''acier non identifié',null),
('2003','C','A=AEE','AR',null,'Maçonnerie (appareillée)',null),
('2003','C','A=AEE','AS',null,'Maçonnerie (non appareillée)',null),
('2003','C','A=AEE','AT',null,'Epoxy',null),
('2003','C','A=AEE','AU',null,'Polyester',null),
('2003','C','A=AEE','AV',null,'Polyéthylène',null),
('2003','C','A=AEE','AW',null,'Polyproylène',null),
('2003','C','A=AEE','AX',null,'PVC-U',null),
('2003','C','A=AEE','AY',null,'Type de plastique non identifié',null),
('2003','C','A=AEE','AZ',null,'Matériau non identifié',null),
('2003','C','A=AEE','Z',null,'Autre',null),
('2003','B','A=AEG','A',null,'Pas de précipitation',null),
('2003','B','A=AEG','B',null,'Pluie',null),
('2003','B','A=AEG','C',null,'Neige fondante ou glace',null),
('2003','B','A=BAA','A',null,'Verticale',null),
('2003','B','A=BAA','B',null,'Horizontale',null),
('2003','B','A=BAB','A',null,'Micro-fissure',null),
('2003','B','A=BAB','B',null,'Fissure fermée',null),
('2003','B','A=BAB','C',null,'Fissure ouverte',null),
('2003','C','A=BAB','A',null,'Longitudinale',null),
('2003','C','A=BAB','B',null,'Circonférentielle',null),
('2003','C','A=BAB','C',null,'Complexe',null),
('2003','C','A=BAB','D',null,'Hélicoïdale',null),
('2003','B','A=BAC','A',null,'Rupture',null),
('2003','B','A=BAC','B',null,'Effondrement partiel',null),
('2003','B','A=BAC','C',null,'Effondrement',null),
('2003','B','A=BAD','A',null,'Déplacé',null),
('2003','B','A=BAD','B',null,'Pièces manquantes',null),
('2003','B','A=BAD','C',null,'Affaissement de radier',null),
('2003','B','A=BAD','D',null,'Effondrement',null),
('2003','C','A=BAD','A',null,'Autre couche visible de briquetage ou d''élément de maçonnerie',null),
('2003','C','A=BAD','B',null,'Rien de visible',null),
('2003','B','A=BAF','A',null,'Rugosité accrue',null),
('2003','B','A=BAF','B',null,'Ecaillage (détachement de petits fragments de la surface)',null),
('2003','B','A=BAF','C',null,'Granulats exposés',null),
('2003','B','A=BAF','D',null,'Granulats déchaussés',null),
('2003','B','A=BAF','E',null,'Granulats manquants',null),
('2003','B','A=BAF','F',null,'Armature visible',null),
('2003','B','A=BAF','G',null,'Armature dépassant de la surface',null),
('2003','B','A=BAF','H',null,'Armature corrodée',null),
('2003','B','A=BAF','I',null,'Paroi manquante',null),
('2003','B','A=BAF','J',null,'Produits corrosifs sur la surface',null),
('2003','B','A=BAF','Z',null,'Autres dégradations de surface',null),
('2003','C','A=BAF','A',null,'Mécanique',null),
('2003','C','A=BAF','B',null,'Chimique - Générale',null),
('2003','C','A=BAF','C',null,'Chimique - Endommagement de la partie supérieure de la conduite',null),
('2003','C','A=BAF','D',null,'Chimique - Endommagement de la partie inférieure de la conduite',null),
('2003','C','A=BAF','E',null,'Aucune cause évidente',null),
('2003','B','A=BAH','A',null,'La position du raccordement sur la canalisation est incorrecte',null),
('2003','B','A=BAH','B',null,'Il y a un vide entre l''extrémité de la conduite de raccordement et la canalisation principale',null),
('2003','B','A=BAH','C',null,'Il y a un vide partiel entre l''extrémité de la conduite de raccordement et la canalisation principale',null),
('2003','B','A=BAH','D',null,'La conduite de raccordement est endommagée',null),
('2003','B','A=BAH','E',null,'La conduite de raccordement est obturée',null),
('2003','B','A=BAH','Z',null,'Autre défaut',null),
('2003','B','A=BAI','A',null,'Anneau d''étanchéité',null),
('2003','B','A=BAI','Z',null,'Autre élément d''étanchéité',null),
('2003','C','A=BAI','A',null,'Visiblement déplacée mais ne dépassant pas dans la conduite',null),
('2003','C','A=BAI','B',null,'Pénétrant mais non rompu - point le plus bas au-dessus de la ligne médiane horizontale',null),
('2003','C','A=BAI','C',null,'Pénétrant mais non rompu - point le plus bas au-dessous de la ligne médiane horizontale',null),
('2003','C','A=BAI','D',null,'Pénétrant et rompu',null),
('2003','B','A=BAJ','A',null,'Déboîtement (longitudinal)',null),
('2003','B','A=BAJ','B',null,'Décentrage (radial)',null),
('2003','B','A=BAJ','C',null,'Déviation (angulaire)',null),
('2003','B','A=BAK','A',null,'Le revêtement de la canalisation s''est détaché',null),
('2003','B','A=BAK','B',null,'Décoloration du revêtement',null),
('2003','B','A=BAK','C',null,'Extrémité du revêtement défectueuse',null),
('2003','B','A=BAK','D',null,'Revêtement ondulé',null),
('2003','B','A=BAK','E',null,'Revêtement cloqué ou renflement interne du revêtement',null),
('2003','B','A=BAK','Z',null,'Autres défauts de revêtement',null),
('2003','C','A=BAK','A',null,'Longitudinale',null),
('2003','C','A=BAK','B',null,'Circonférentielle',null),
('2003','C','A=BAK','C',null,'Complexe',null),
('2003','B','A=BAL','A',null,'Paroi manquante',null),
('2003','B','A=BAL','B',null,'Une reprise bouchant un trou délébirément pratiqué dans la paroi de la canalisation est devenue défectueuse',null),
('2003','B','A=BAL','Z',null,'Autre défaut',null),
('2003','B','A=BAM','A',null,'Longitudinal',null),
('2003','B','A=BAM','B',null,'Circonférentiel',null),
('2003','B','A=BAM','C',null,'Hélicoïdal',null),
('2003','B','A=BBA','A',null,'Grosse racine isolée',null),
('2003','B','A=BBA','B',null,'Radicelles',null),
('2003','B','A=BBA','C',null,'Ensemble complexe de racines',null),
('2003','B','A=BBB','A',null,'Concrétions',null),
('2003','B','A=BBB','B',null,'Graisse',null),
('2003','B','A=BBB','C',null,'Encrassement',null),
('2003','B','A=BBB','Z',null,'Autre type de dépôt',null),
('2003','B','A=BBC','A',null,'Fin (p.ex. sable, vase)',null),
('2003','B','A=BBC','B',null,'Grossier (p.ex. gravats, gravier)',null),
('2003','B','A=BBC','C',null,'Dur ou compacté (p.ex. béton)',null),
('2003','B','A=BBC','Z',null,'Autre type de dépôt',null),
('2003','B','A=BBD','A',null,'Sable',null),
('2003','B','A=BBD','B',null,'Tourbe',null),
('2003','B','A=BBD','C',null,'Matériau fin (p.ex. argile, vase)',null),
('2003','B','A=BBD','D',null,'Gravier',null),
('2003','B','A=BBD','Z',null,'Autre type de sol',null),
('2003','B','A=BBE','A',null,'Briquetage ou élément de maçonnerie gisant sur le radier',null),
('2003','B','A=BBE','B',null,'Fragment de conduite d''évacuation et d''assainissement gisant sur le radier',null),
('2003','B','A=BBE','C',null,'Autre objet gisant sur le radier',null),
('2003','B','A=BBE','D',null,'Obstacle dépassant de la paroi',null),
('2003','B','A=BBE','E',null,'Obstacle coincé dans l''assemblage',null),
('2003','B','A=BBE','F',null,'Obstacle traversant un raccordement ou une conduite de raccordement',null),
('2003','B','A=BBE','G',null,'Conduites externes ou câbles insérés dans la canalisation',null),
('2003','B','A=BBE','H',null,'Obstacle intégré à la structure',null),
('2003','B','A=BBE','Z',null,'Autre type d''obstacle',null),
('2003','B','A=BBF','A',null,'Suintement',null),
('2003','B','A=BBF','B',null,'Goutte à goutte',null),
('2003','B','A=BBF','C',null,'Ecoulement',null),
('2003','B','A=BBF','D',null,'Jaillissement',null),
('2003','B','A=BBH','A',null,'Rat',null),
('2003','B','A=BBH','B',null,'Cafard',null),
('2003','B','A=BBH','Z',null,'Autre animal',null),
('2003','C','A=BBH','A',null,'Dans la canalisation',null),
('2003','C','A=BBH','B',null,'Dans un raccordement',null),
('2003','C','A=BBH','C',null,'Dans un assemblage ouvert',null),
('2003','C','A=BBH','Z',null,'Autre emplacement',null),
('2003','B','A=BCA','A',null,'Culotte',null),
('2003','B','A=BCA','B',null,'Selle - carottée',null),
('2003','B','A=BCA','C',null,'Selle - burinée',null),
('2003','B','A=BCA','D',null,'Piquage direct - carotté',null),
('2003','B','A=BCA','E',null,'Piquage direct - buriné',null),
('2003','B','A=BCA','F',null,'Raccord autre que culotte',null),
('2003','B','A=BCA','G',null,'Type de raccord inconnu',null),
('2003','B','A=BCA','Z',null,'Autre type de raccord',null),
('2003','C','A=BCA','A',null,'Raccordement ouvert',null),
('2003','C','A=BCA','B',null,'Raccordement fermé',null),
('2003','B','A=BCB','A',null,'Remplacement de la conduite',null),
('2003','B','A=BCB','B',null,'Revêtement localisé de conduite',null),
('2003','B','A=BCB','C',null,'Mortier injecté',null),
('2003','B','A=BCB','D',null,'Autre matériau d''étanchéité injecté',null),
('2003','B','A=BCB','E',null,'Trou réparé',null),
('2003','B','A=BCB','Z',null,'Autre méthode de réparation sans tranchée',null),
('2003','B','A=BCC','A',null,'Vers la gauche',null),
('2003','B','A=BCC','B',null,'Vers la droite',null),
('2003','C','A=BCC','A',null,'Vers le haut',null),
('2003','C','A=BCC','B',null,'Vers le bas',null),
('2003','B','A=BCD','A',null,'Regard de visite',null),
('2003','B','A=BCD','B',null,'Chambre d''inspection',null),
('2003','B','A=BCD','C',null,'Orifice de nettoyage',null),
('2003','B','A=BCD','D',null,'Orifice de passage de la lampe',null),
('2003','B','A=BCD','E',null,'Déversoir',null),
('2003','B','A=BCD','F',null,'Raccordement important sans regard de visite ou chambre d''inspection',null),
('2003','B','A=BCD','Z',null,'Autre ouvrage spécial',null),
('2003','B','A=BCE','A',null,'Regard de visite',null),
('2003','B','A=BCE','B',null,'Chambre d''inspection',null),
('2003','B','A=BCE','C',null,'Orifice de nettoyage',null),
('2003','B','A=BCE','D',null,'Orifice de passage de la lampe',null),
('2003','B','A=BCE','E',null,'Déversoir',null),
('2003','B','A=BCE','F',null,'Raccordement important sans regard de visite ou chambre d''inspection',null),
('2003','B','A=BCE','Z',null,'Autre ouvrage spécial',null),
('2003','B','A=BDC','A',null,'Obstruction',null),
('2003','B','A=BDC','B',null,'Niveau d''eau trop élevé',null),
('2003','B','A=BDC','C',null,'Panne de l''équipement',null),
('2003','B','A=BDC','Z',null,'Autre cause d''abandon',null),
('2003','B','A=BDD','A',null,'Clair(le radier est visible)',null),
('2003','B','A=BDD','B',null,'Trouble ou décoloré',null),
('2003','B','A=BDE','A',null,'Eaux usées claires',null),
('2003','B','A=BDE','B',null,'Eaux usées d''aspect discontinu',null),
('2003','C','A=BDE','A',null,'Eaux usées dans un branchement ou un collecteur d''eaux de surface',null),
('2003','C','A=BDE','B',null,'Eaux de surface dans un branchement ou un collecteur d''eaux usées',null),
('2003','C','A=BDE','C',null,'Aucun mauvais raccordement observé',null),
('2003','B','A=BDF','A',null,'Manque d''oxygène',null),
('2003','B','A=BDF','B',null,'Sulfure d''hydrogène',null),
('2003','B','A=BDF','C',null,'Méthane',null),
('2003','B','A=BDF','Z',null,'Autre danger',null),
('2003','B','A=BDG','A',null,'Caméra sous l''eau',null),
('2003','B','A=BDG','B',null,'Vase',null),
('2003','B','A=BDG','C',null,'Vapeur',null),
('2003','B','A=BDG','Z',null,'Autre cause',null),
('2003','B','A=CED','AA',null,'Amiante-ciment',null),
('2003','B','A=CED','AB',null,'Bitume',null),
('2003','B','A=CED','AC',null,'Fibres projetées',null),
('2003','B','A=CED','AD',null,'Briquetage',null),
('2003','B','A=CED','AE',null,'Grès',null),
('2003','B','A=CED','AF',null,'Mortier de ciment',null),
('2003','B','A=CED','AG',null,'Béton',null),
('2003','B','A=CED','AH',null,'Béton armé',null),
('2003','B','A=CED','AI',null,'Béton projeté',null),
('2003','B','A=CED','AJ',null,'Segments de béton',null),
('2003','B','A=CED','AK',null,'Fibres-ciment',null),
('2003','B','A=CED','AL',null,'Plastiques renforcés de fibres',null),
('2003','B','A=CED','AM',null,'Fonte',null),
('2003','B','A=CED','AN',null,'Fonte grise',null),
('2003','B','A=CED','AO',null,'Fonte ductile',null),
('2003','B','A=CED','AP',null,'Acier',null),
('2003','B','A=CED','AQ',null,'Type de fer ou d''acier non identifié',null),
('2003','B','A=CED','AR',null,'Maçonnerie (appareillée)',null),
('2003','B','A=CED','AS',null,'Maçonnerie (non appareillée)',null),
('2003','B','A=CED','AT',null,'Epoxy',null),
('2003','B','A=CED','AU',null,'Polyester',null),
('2003','B','A=CED','AV',null,'Polyéthylène',null),
('2003','B','A=CED','AW',null,'Polyproylène',null),
('2003','B','A=CED','AX',null,'PVC-U',null),
('2003','B','A=CED','AY',null,'Type de plastique non identifié',null),
('2003','B','A=CED','AZ',null,'Matériau non identifié',null),
('2003','B','A=CED','Z',null,'Autre',null),
('2003','B','A=DAA','A',null,'Généralisée',null),
('2003','B','A=DAA','B',null,'Localisée',null),
('2003','B','A=DAB','A',null,'Micro-fissure',null),
('2003','B','A=DAB','B',null,'Fissure fermée',null),
('2003','B','A=DAB','C',null,'Fissure ouverte',null),
('2003','C','A=DAB','A',null,'Verticale',null),
('2003','C','A=DAB','B',null,'Horizontale',null),
('2003','C','A=DAB','C',null,'Complexe',null),
('2003','C','A=DAB','D',null,'Inclinée',null),
('2003','B','A=DAC','A',null,'Rupture',null),
('2003','B','A=DAC','B',null,'Effondrement partiel',null),
('2003','B','A=DAC','C',null,'Effondrement',null),
('2003','B','A=DAD','A',null,'Déplacé',null),
('2003','B','A=DAD','B',null,'Pièces manquantes',null),
('2003','B','A=DAD','C',null,'Effondrement',null),
('2003','C','A=DAD','A',null,'Autre couche visible de briquetage ou d''élément de maçonnerie',null),
('2003','C','A=DAD','B',null,'Rien de visible',null),
('2003','B','A=DAF','A',null,'Rugosité accrue',null),
('2003','B','A=DAF','B',null,'Ecaillage (détachement de petits fragments de la surface)',null),
('2003','B','A=DAF','C',null,'Granulats exposés',null),
('2003','B','A=DAF','D',null,'Granulats déchaussés',null),
('2003','B','A=DAF','E',null,'Granulats manquants',null),
('2003','B','A=DAF','F',null,'Armature visible',null),
('2003','B','A=DAF','G',null,'Armature dépassant de la surface',null),
('2003','B','A=DAF','H',null,'Armature corrodée',null),
('2003','B','A=DAF','I',null,'Paroi manquante',null),
('2003','B','A=DAF','J',null,'Produits corrosifs sur la surface',null),
('2003','B','A=DAF','Z',null,'Autres dégradations de surface',null),
('2003','C','A=DAF','A',null,'Mécanique',null),
('2003','C','A=DAF','B',null,'Chimique - Générale',null),
('2003','C','A=DAF','C',null,'Chimique - Endommagement de la partie supérieure de la conduite',null),
('2003','C','A=DAF','D',null,'Chimique - Endommagement de la partie inférieure de la conduite',null),
('2003','C','A=DAF','E',null,'Aucune cause évidente',null),
('2003','B','A=DAH','A',null,'La position du raccordement sur la canalisation est incorrecte',null),
('2003','B','A=DAH','B',null,'Il y a un vide entre l''extrémité de la conduite de raccordement et la canalisation principale',null),
('2003','B','A=DAH','C',null,'Il y a un vide partiel entre l''extrémité de la conduite de raccordement et la canalisation principale',null),
('2003','B','A=DAH','D',null,'La conduite de raccordement est endommagée',null),
('2003','B','A=DAH','E',null,'La conduite de raccordement est obturée',null),
('2003','B','A=DAH','Z',null,'Autre défaut',null),
('2003','B','A=DAI','A',null,'Anneau d''étanchéité',null),
('2003','B','A=DAI','Z',null,'Autre élément d''étanchéité',null),
('2003','C','A=DAI','A',null,'Visiblement déplacée mais ne dépassant pas dans la chambre',null),
('2003','C','A=DAI','B',null,'Pendante mais non rompue',null),
('2003','C','A=DAI','C',null,'Rompue',null),
('2003','B','A=DAJ','A',null,'Vertical',null),
('2003','B','A=DAJ','B',null,'Horizontal',null),
('2003','B','A=DAJ','C',null,'Angulaire',null),
('2003','B','A=DAK','A',null,'Le revêtement de la canalisation s''est détaché',null),
('2003','B','A=DAK','B',null,'Décoloration du revêtement',null),
('2003','B','A=DAK','C',null,'Extrémité du revêtement défectueuse',null),
('2003','B','A=DAK','D',null,'Revêtement ondulé',null),
('2003','B','A=DAK','E',null,'Revêtement cloqué ou renflement interne du revêtement',null),
('2003','B','A=DAK','Z',null,'Autres défauts de revêtement',null),
('2003','C','A=DAK','A',null,'Verticale',null),
('2003','C','A=DAK','B',null,'Horizontale',null),
('2003','C','A=DAK','C',null,'Complexe',null),
('2003','B','A=DAL','A',null,'Paroi manquante',null),
('2003','B','A=DAL','B',null,'Une reprise bouchant un trou délébirément pratiqué dans la paroi de la canalisation est devenue défectueuse',null),
('2003','B','A=DAL','Z',null,'Autre défaut',null),
('2003','B','A=DAM','A',null,'Vertical',null),
('2003','B','A=DAM','B',null,'Horizontal',null),
('2003','B','A=DAM','C',null,'Incliné',null),
('2003','B','A=DAQ','A',null,'Echelon déboîté',null),
('2003','B','A=DAQ','B',null,'Echelon manquant',null),
('2003','B','A=DAQ','C',null,'Echelon corrodé',null),
('2003','B','A=DAQ','D',null,'Echelon faussé',null),
('2003','B','A=DAQ','E',null,'Enreobage plastique brisé',null),
('2003','B','A=DAQ','F',null,'Main-courante de l''échelle corrodée',null),
('2003','B','A=DAQ','G',null,'Support de l''échelle déboîté',null),
('2003','B','A=DAQ','H',null,'Support de l''échelle manquant',null),
('2003','B','A=DAQ','I',null,'Support de l''échelle corrodé',null),
('2003','B','A=DAQ','J',null,'Montant de l''échelle corrodé',null),
('2003','B','A=DAQ','K',null,'Trou dans la paroi défectueux',null),
('2003','B','A=DAQ','Z',null,'Autre défaut',null),
('2003','B','A=DAR','A',null,'Tampon cassé',null),
('2003','B','A=DAR','B',null,'Tampon oscillant',null),
('2003','B','A=DAR','C',null,'Tampon manquant',null),
('2003','B','A=DAR','D',null,'Cadre brisé',null),
('2003','B','A=DAR','E',null,'Cadre déboîté',null),
('2003','B','A=DAR','F',null,'Cadre manquant',null),
('2003','B','A=DAR','G',null,'Tampon au-dessous du niveau de la surface',null),
('2003','B','A=DAR','H',null,'Tampon au-dessus du niveau de la surface',null),
('2003','B','A=DAR','Z',null,'Autre défaut',null),
('2003','B','A=DBA','A',null,'Grosse racine isolée',null),
('2003','B','A=DBA','B',null,'Radicelles',null),
('2003','B','A=DBA','C',null,'Ensemble complexe de racines',null),
('2003','B','A=DBB','A',null,'Concrétions',null),
('2003','B','A=DBB','B',null,'Graisse',null),
('2003','B','A=DBB','C',null,'Encrassement',null),
('2003','B','A=DBB','Z',null,'Autre type de dépôt',null),
('2003','B','A=DBC','A',null,'Fin (p.ex. sable, vase)',null),
('2003','B','A=DBC','B',null,'Grossier (p.ex. gravats, gravier)',null),
('2003','B','A=DBC','C',null,'Dur ou compacté (p.ex. béton)',null),
('2003','B','A=DBC','Z',null,'Autre type de dépôt',null),
('2003','B','A=DBE','A',null,'Briquetage ou élément de maçonnerie détaché',null),
('2003','B','A=DBE','B',null,'Fragment de canalisation brisés',null),
('2003','B','A=DBE','C',null,'Autre objet',null),
('2003','B','A=DBE','D',null,'Obstacle dépassant de la paroi',null),
('2003','B','A=DBE','E',null,'Obstacle coincé dans l''assemblage',null),
('2003','B','A=DBE','F',null,'Obstacle traversant un raccordement ou une conduite de raccordement',null),
('2003','B','A=DBE','G',null,'Conduites externes ou câbles insérés dans la canalisation',null),
('2003','B','A=DBE','H',null,'Obstacle intégré à la structure',null),
('2003','B','A=DBE','Z',null,'Autre type d''obstacle',null),
('2003','B','A=DBF','A',null,'Suintement',null),
('2003','B','A=DBF','B',null,'Goutte à goutte',null),
('2003','B','A=DBF','C',null,'Ecoulement',null),
('2003','B','A=DBF','D',null,'Jaillissement',null),
('2003','C','A=DBF','A',null,'A travers la paroi du regard de visite ou de la chambre d''inspection',null),
('2003','C','A=DBF','B',null,'A travers l''espace entre une conduite de raccordement et la paroi du regard de visite ou de la chambre d''inspection au niveau du radier',null),
('2003','C','A=DBF','C',null,'A travers l''espace entre une conduite de raccordement et la paroi du regard de visite ou de la chambre d''inspection au-dessus de la banquette',null),
('2003','B','A=DBH','A',null,'Rat',null),
('2003','B','A=DBH','B',null,'Cafard',null),
('2003','B','A=DBH','Z',null,'Autre animal',null),
('2003','C','A=DBH','A',null,'Dans le regard de visite ou la chambre d''inspection',null),
('2003','C','A=DBH','B',null,'Dans un raccordement',null),
('2003','C','A=DBH','C',null,'Dans un assemblage ouvert',null),
('2003','C','A=DBH','Z',null,'Autre emplacement',null),
('2003','B','A=DCA','A',null,'Raccordement dans la banquette',null),
('2003','B','A=DCA','B',null,'Chute dans la cunette',null),
('2003','B','A=DCA','C',null,'Chute accompagnée',null),
('2003','B','A=DCA','D',null,'Chute accompagnée verticale interne',null),
('2003','B','A=DCA','E',null,'Chute accompagnée inclinée externe',null),
('2003','B','A=DCA','F',null,'Canalisation d''aération',null),
('2003','B','A=DCA','Z',null,'Autre type de raccordement',null),
('2003','B','A=DCB','A',null,'Remplacement d''une partie de la paroi',null),
('2003','B','A=DCB','B',null,'Revêtement localisé d''un regard de visite ou d''une chambre d''inspection',null),
('2003','B','A=DCB','C',null,'Injection de matériau d''étanchéité',null),
('2003','B','A=DCB','Z',null,'Autre méthode de réparation',null),
('2003','B','A=DCG','A',null,'Circulaire',null),
('2003','B','A=DCG','B',null,'Rectangulaire',null),
('2003','B','A=DCG','C',null,'Ovoïde',null),
('2003','B','A=DCG','D',null,'En U',null),
('2003','B','A=DCG','E',null,'En arc',null),
('2003','B','A=DCG','F',null,'Ovale',null),
('2003','B','A=DCG','Z',null,'Autre forme',null),
('2003','C','A=DCG','A',null,'Raccordement entrant',null),
('2003','C','A=DCG','B',null,'Raccordement sortant',null),
('2003','C','A=DCG','C',null,'Raccordement obturé',null),
('2003','B','A=DCH','A',null,'Banquette défectueuse',null),
('2003','B','A=DCH','B',null,'Banquette correcte',null),
('2003','B','A=DCI','A',null,'Cunette défectueuse',null),
('2003','B','A=DCI','B',null,'Cunette correcte',null),
('2003','B','A=DCJ','A',null,'Chaîne de sécurité présente sans aucun défaut',null),
('2003','B','A=DCJ','B',null,'Chaîne de sécurité manquante',null),
('2003','B','A=DCJ','C',null,'Chaîne de sécurité défectueuse',null),
('2003','B','A=DCJ','D',null,'Chaîne de sécurité en place mais couverte de débris',null),
('2003','B','A=DCJ','E',null,'Barre de sécurité présente sans aucun défaut',null),
('2003','B','A=DCJ','F',null,'Barre de sécurité manquante',null),
('2003','B','A=DCJ','G',null,'Barre de sécurité défectueuse',null),
('2003','B','A=DCJ','H',null,'Barre de sécurité en place mais couverte de débris',null),
('2003','B','A=DCK','A',null,'Déversoir',null),
('2003','B','A=DCK','B',null,'Siphon',null),
('2003','B','A=DCK','C',null,'Orifice',null),
('2003','B','A=DCK','D',null,'Régulateur de tourbillons',null),
('2003','B','A=DCK','E',null,'Vanne d''arrêts',null),
('2003','B','A=DCK','F',null,'Vanne d''arrêts actionnée par flotteur',null),
('2003','B','A=DCK','G',null,'Canal jaugeur',null),
('2003','B','A=DCK','H',null,'Soupape à clapets',null),
('2003','B','A=DCK','I',null,'Ecrans',null),
('2003','B','A=DCK','Z',null,'Autre dispositif de régulation',null),
('2003','C','A=DCK','A',null,'Contrôle de l''écoulement continu',null),
('2003','C','A=DCK','B',null,'Contrôle du trop-plein',null),
('2003','B','A=DCL','A',null,'Pas d''accès à la canalisation',null),
('2003','B','A=DCL','B',null,'Accès assuré - Tampon en place',null),
('2003','B','A=DCL','C',null,'Accès assuré - Couvercle manquant',null),
('2003','C','A=DCL','A',null,'Canalisation défectueuse',null),
('2003','C','A=DCL','B',null,'Canalisation non défectueuse',null),
('2003','B','A=DCM','A',null,'Piège présent sans aucun défaut',null),
('2003','B','A=DCM','B',null,'Piège manquant',null),
('2003','B','A=DCM','C',null,'Piège défectueux',null),
('2003','B','A=DCN','A',null,'Bassin non défectueux',null),
('2003','B','A=DCN','B',null,'Bassin défectueux',null),
('2003','B','A=DCO','A',null,'Circulaire',null),
('2003','B','A=DCO','B',null,'Rectangulaire',null),
('2003','B','A=DCO','Z',null,'Autre forme',null),
('2003','B','A=DDC','A',null,'Impossible d''ôter le tampon',null),
('2003','B','A=DDC','B',null,'Obstruction',null),
('2003','B','A=DDC','C',null,'Niveau d''eau trop élevé',null),
('2003','B','A=DDC','D',null,'Panne de l''équipement',null),
('2003','B','A=DDC','Z',null,'Autre cause',null),
('2003','B','A=DDE','A',null,'Clair',null),
('2003','B','A=DDE','B',null,'Trouble ou décoloré',null),
('2003','C','A=DDE','A',null,'Mal raccordée car les eaux usées se déversent dans un branchement ou un collecteur d''eaux de surface',null),
('2003','C','A=DDE','B',null,'Mal raccordée car les eaux usées se déversent dans un branchement ou un collecteur d''eaux usées',null),
('2003','C','A=DDE','C',null,'Aucun mauvais raccordement observé',null),
('2003','B','A=DDF','A',null,'Manque d''oxygène',null),
('2003','B','A=DDF','B',null,'Sulfure d''hydrogène',null),
('2003','B','A=DDF','C',null,'Méthane',null),
('2003','B','A=DDF','Z',null,'Autre danger',null),
('2003','B','A=DDG','A',null,'Caméra sous l''eau',null),
('2003','B','A=DDG','B',null,'Vase',null),
('2003','B','A=DDG','C',null,'Vapeur',null),
('2003','B','A=DDG','Z',null,'Autre cause',null),
('2003','A',null,'AEA',null,null,null),
('2003','A',null,'AEB',null,null,null),
('2003','A',null,'AEC',null,null,null),
('2003','A',null,'AED',null,null,null),
('2003','A',null,'AEE',null,null,null),
('2003','A',null,'AEF',null,null,null),
('2003','A',null,'AEG',null,'null',null),
('2003','A',null,'BAA',null,null,null),
('2003','A',null,'BAB',null,null,null),
('2003','A',null,'BAC',null,null,null),
('2003','A',null,'BAD',null,null,null),
('2003','A',null,'BAE',null,null,null),
('2003','A',null,'BAF',null,null,null),
('2003','A',null,'BAG',null,null,null),
('2003','A',null,'BAH',null,null,null),
('2003','A',null,'BAI',null,null,null),
('2003','A',null,'BAJ',null,null,null),
('2003','A',null,'BAK',null,null,null),
('2003','A',null,'BAL',null,null,null),
('2003','A',null,'BAM',null,null,null),
('2003','A',null,'BAN',null,null,null),
('2003','A',null,'BAO',null,null,null),
('2003','A',null,'BAP',null,null,null),
('2003','A',null,'BBA',null,null,null),
('2003','A',null,'BBB',null,null,null),
('2003','A',null,'BBC',null,null,null),
('2003','A',null,'BBD',null,null,null),
('2003','A',null,'BBE',null,null,null),
('2003','A',null,'BBF',null,null,null),
('2003','A',null,'BBG',null,null,null),
('2003','A',null,'BBH',null,null,null),
('2003','A',null,'BCA',null,null,null),
('2003','A',null,'BCB',null,null,null),
('2003','A',null,'BCC',null,null,null),
('2003','A',null,'BCD',null,null,null),
('2003','A',null,'BCE',null,null,null),
('2003','A',null,'BCF',null,null,null),
('2003','A',null,'BDA',null,null,null),
('2003','A',null,'BDB',null,null,null),
('2003','A',null,'BDC',null,null,null),
('2003','A',null,'BDD',null,null,null),
('2003','A',null,'BDE',null,null,null),
('2003','A',null,'BDF',null,null,null),
('2003','A',null,'BDG',null,null,null),
('2003','A',null,'DAA',null,null,null),
('2003','A',null,'DAB',null,null,null),
('2003','A',null,'DAC',null,null,null),
('2003','A',null,'DAD',null,null,null),
('2003','A',null,'DAE',null,null,null),
('2003','A',null,'DAF',null,null,null),
('2003','A',null,'DAG',null,null,null),
('2003','A',null,'DAH',null,null,null),
('2003','A',null,'DAI',null,null,null),
('2003','A',null,'DAJ',null,null,null),
('2003','A',null,'DAK',null,null,null),
('2003','A',null,'DAL',null,null,null),
('2003','A',null,'DAM',null,null,null),
('2003','A',null,'DAN',null,null,null),
('2003','A',null,'DAO',null,null,null),
('2003','A',null,'DAP',null,null,null),
('2003','A',null,'DAQ',null,null,null),
('2003','A',null,'DAR',null,null,null),
('2003','A',null,'DBA',null,null,null),
('2003','A',null,'DBB',null,null,null),
('2003','A',null,'DBC',null,null,null),
('2003','A',null,'DBD',null,null,null),
('2003','A',null,'DBE',null,null,null),
('2003','A',null,'DBF',null,null,null),
('2003','A',null,'DBG',null,null,null),
('2003','A',null,'DBH',null,null,null),
('2003','A',null,'DCA',null,null,null),
('2003','A',null,'DCB',null,null,null),
('2003','A',null,'DCC',null,null,null),
('2003','A',null,'DCD',null,null,null),
('2003','A',null,'DCE',null,null,null),
('2003','A',null,'DCF',null,null,null),
('2003','A',null,'DCG',null,null,null),
('2003','A',null,'DCH',null,null,null),
('2003','A',null,'DCI',null,null,null),
('2003','A',null,'DCJ',null,null,null),
('2003','A',null,'DCK',null,null,null),
('2003','A',null,'DCL',null,null,null),
('2003','A',null,'DCM',null,null,null),
('2003','A',null,'DCN',null,null,null),
('2003','A',null,'DCO',null,null,null),
('2003','A',null,'DDA',null,null,null),
('2003','A',null,'DDB',null,null,null),
('2003','A',null,'DDC',null,null,null),
('2003','A',null,'DDD',null,null,null),
('2003','A',null,'DDE',null,null,null),
('2003','A',null,'DDF',null,null,null),
('2003','A',null,'DDG',null,null,null),
('2003','ACD',null,'AA',null,'Amiante-ciment',null),
('2003','ACD',null,'AB',null,'Bitume',null),
('2003','ACD',null,'AC',null,'Fibres projetées',null),
('2003','ACD',null,'AD',null,'Briquetage',null),
('2003','ACD',null,'AE',null,'Grès',null),
('2003','ACD',null,'AF',null,'Mortier de ciment',null),
('2003','ACD',null,'AG',null,'Béton',null),
('2003','ACD',null,'AH',null,'Béton armé',null),
('2003','ACD',null,'AI',null,'Béton projeté',null),
('2003','ACD',null,'AJ',null,'Segments de béton',null),
('2003','ACD',null,'AK',null,'Fibres-ciment',null),
('2003','ACD',null,'AL',null,'Plastiques renforcés de fibres',null),
('2003','ACD',null,'AM',null,'Fonte',null),
('2003','ACD',null,'AN',null,'Fonte grise',null),
('2003','ACD',null,'AO',null,'Fonte ductile',null),
('2003','ACD',null,'AP',null,'Acier',null),
('2003','ACD',null,'AQ',null,'Type de fer ou d''acier non identifié',null),
('2003','ACD',null,'AR',null,'Maçonnerie (appareillée)',null),
('2003','ACD',null,'AS',null,'Maçonnerie (non appareillée)',null),
('2003','ACD',null,'AT',null,'Epoxy',null),
('2003','ACD',null,'AU',null,'Polyester',null),
('2003','ACD',null,'AV',null,'Polyéthylène',null),
('2003','ACD',null,'AW',null,'Polyproylène',null),
('2003','ACD',null,'AX',null,'PVC-U',null),
('2003','ACD',null,'AY',null,'Type de plastique non identifié',null),
('2003','ACD',null,'AZ',null,'Matériau non identifié',null),
('2003','ACD',null,'Z',null,'Autre',null),
('2003','ACF',null,'AA',null,'Amiante-ciment',null),
('2003','ACF',null,'AB',null,'Bitume',null),
('2003','ACF',null,'AC',null,'Fibres projetées',null),
('2003','ACF',null,'AD',null,'Briquetage',null),
('2003','ACF',null,'AE',null,'Grès',null),
('2003','ACF',null,'AF',null,'Mortier de ciment',null),
('2003','ACF',null,'AG',null,'Béton',null),
('2003','ACF',null,'AH',null,'Béton armé',null),
('2003','ACF',null,'AI',null,'Béton projeté',null),
('2003','ACF',null,'AJ',null,'Segments de béton',null),
('2003','ACF',null,'AK',null,'Fibres-ciment',null),
('2003','ACF',null,'AL',null,'Plastiques renforcés de fibres',null),
('2003','ACF',null,'AM',null,'Fonte',null),
('2003','ACF',null,'AN',null,'Fonte grise',null),
('2003','ACF',null,'AO',null,'Fonte ductile',null),
('2003','ACF',null,'AP',null,'Acier',null),
('2003','ACF',null,'AQ',null,'Type de fer ou d''acier non identifié',null),
('2003','ACF',null,'AR',null,'Maçonnerie (appareillée)',null),
('2003','ACF',null,'AS',null,'Maçonnerie (non appareillée)',null),
('2003','ACF',null,'AT',null,'Epoxy',null),
('2003','ACF',null,'AU',null,'Polyester',null),
('2003','ACF',null,'AV',null,'Polyéthylène',null),
('2003','ACF',null,'AW',null,'Polyproylène',null),
('2003','ACF',null,'AX',null,'PVC-U',null),
('2003','ACF',null,'AY',null,'Type de plastique non identifié',null),
('2003','ACF',null,'AZ',null,'Matériau non identifié',null),
('2003','ACF',null,'Z',null,'Autre',null),
('2003','CCD',null,'AA',null,'Amiante-ciment',null),
('2003','CCD',null,'AB',null,'Bitume',null),
('2003','CCD',null,'AC',null,'Fibres projetées',null),
('2003','CCD',null,'AD',null,'Briquetage',null),
('2003','CCD',null,'AE',null,'Grès',null),
('2003','CCD',null,'AF',null,'Mortier de ciment',null),
('2003','CCD',null,'AG',null,'Béton',null),
('2003','CCD',null,'AH',null,'Béton armé',null),
('2003','CCD',null,'AI',null,'Béton projeté',null),
('2003','CCD',null,'AJ',null,'Segments de béton',null),
('2003','CCD',null,'AK',null,'Fibres-ciment',null),
('2003','CCD',null,'AL',null,'Plastiques renforcés de fibres',null),
('2003','CCD',null,'AM',null,'Fonte',null),
('2003','CCD',null,'AN',null,'Fonte grise',null),
('2003','CCD',null,'AO',null,'Fonte ductile',null),
('2003','CCD',null,'AP',null,'Acier',null),
('2003','CCD',null,'AQ',null,'Type de fer ou d''acier non identifié',null),
('2003','CCD',null,'AR',null,'Maçonnerie (appareillée)',null),
('2003','CCD',null,'AS',null,'Maçonnerie (non appareillée)',null),
('2003','CCD',null,'AT',null,'Epoxy',null),
('2003','CCD',null,'AU',null,'Polyester',null),
('2003','CCD',null,'AV',null,'Polyéthylène',null),
('2003','CCD',null,'AW',null,'Polyproylène',null),
('2003','CCD',null,'AX',null,'PVC-U',null),
('2003','CCD',null,'AY',null,'Type de plastique non identifié',null),
('2003','CCD',null,'AZ',null,'Matériau non identifié',null),
('2003','CCD',null,'Z',null,'Autre',null),
('2003','CCP',null,'AA',null,'Amiante-ciment',null),
('2003','CCP',null,'AB',null,'Bitume',null),
('2003','CCP',null,'AC',null,'Fibres projetées',null),
('2003','CCP',null,'AD',null,'Briquetage',null),
('2003','CCP',null,'AE',null,'Grès',null),
('2003','CCP',null,'AF',null,'Mortier de ciment',null),
('2003','CCP',null,'AG',null,'Béton',null),
('2003','CCP',null,'AH',null,'Béton armé',null),
('2003','CCP',null,'AI',null,'Béton projeté',null),
('2003','CCP',null,'AJ',null,'Segments de béton',null),
('2003','CCP',null,'AK',null,'Fibres-ciment',null),
('2003','CCP',null,'AL',null,'Plastiques renforcés de fibres',null),
('2003','CCP',null,'AM',null,'Fonte',null),
('2003','CCP',null,'AN',null,'Fonte grise',null),
('2003','CCP',null,'AO',null,'Fonte ductile',null),
('2003','CCP',null,'AP',null,'Acier',null),
('2003','CCP',null,'AQ',null,'Type de fer ou d''acier non identifié',null),
('2003','CCP',null,'AR',null,'Maçonnerie (appareillée)',null),
('2003','CCP',null,'AS',null,'Maçonnerie (non appareillée)',null),
('2003','CCP',null,'AT',null,'Epoxy',null),
('2003','CCP',null,'AU',null,'Polyester',null),
('2003','CCP',null,'AV',null,'Polyéthylène',null),
('2003','CCP',null,'AW',null,'Polyproylène',null),
('2003','CCP',null,'AX',null,'PVC-U',null),
('2003','CCP',null,'AY',null,'Type de plastique non identifié',null),
('2003','CCP',null,'AZ',null,'Matériau non identifié',null),
('2003','CCP',null,'Z',null,'Autre',null),
('2003','AAK',null,'A',null,'Aval',null),
('2003','AAK',null,'B',null,'Amont',null),
('2003','AAK',null,'C',null,'Inconnu',null),
('2003','AAL',null,'A',null,'Sous une route',null),
('2003','AAL',null,'B',null,'Sous un trottoir',null),
('2003','AAL',null,'C',null,'Sous l''accotement d''une route',null),
('2003','AAL',null,'D',null,'Dans une autre zone piétonnière',null),
('2003','AAL',null,'E',null,'Dans un champ',null),
('2003','AAL',null,'F',null,'Sous une propriété bâtie',null),
('2003','AAL',null,'G',null,'Sous des jardins',null),
('2003','AAL',null,'H',null,'Sous un bâtiment permanent',null),
('2003','AAL',null,'I',null,'Sous un terrain boisé',null),
('2003','AAL',null,'J',null,'Accès difficile',null),
('2003','AAL',null,'K',null,'Sous une voie navigable',null),
('2003','AAL',null,'Xx',null,'Type spécial défini par l?autorité responsable',null),
('2003','AAL',null,'Z',null,'Autre',null),
('2003','AAQ',null,'A',null,'Bien public',null),
('2003','AAQ',null,'B',null,'Bien privé',null),
('2003','AAQ',null,'C',null,'Inconnue',null),
('2003','ABC',null,'A',null,'Face intérieure de la paroi du noeud de départ',null),
('2003','ABC',null,'B',null,'Intrados du tronçon à l''intérieur du noeud de départ.',null),
('2003','ABC',null,'C',null,'Centre du noeud de départ',null);


-- ITV
create table ITV (
	id 				bigserial primary key,
	itv_filename 	text not null,
	itv_status 		text not null,
	itv_ucre_id     bigint references users(id) default 0,
	itv_umod_id     bigint references users(id) default 0,
	itv_dcre  		timestamp without time zone  default current_timestamp,
	itv_dmod        timestamp without time zone  default current_timestamp
);

COMMENT ON TABLE ITV is 'This table contains the ITV';
COMMENT ON COLUMN ITV.itv_filename is 'Name of the ITV file';
COMMENT ON COLUMN ITV.itv_status is 'Status of the ITV';
COMMENT ON COLUMN ITV.itv_ucre_id is 'Creator Id';
COMMENT ON COLUMN ITV.itv_umod_id is 'Last modificator Id';
COMMENT ON COLUMN ITV.itv_dcre is 'Creation date';
COMMENT ON COLUMN ITV.itv_dmod is 'Last modification date';


-- ITV_BLOCK
create table ITV_BLOCK (
	id 				bigserial primary key,
	itv_id			bigint not null references ITV(id),
	itb_obj_ref     text,
	itb_obj_table   text REFERENCES layer(lyr_table_name)
);

COMMENT ON TABLE ITV_BLOCK is 'This table contains the ITV Block linked to an ITV';
COMMENT ON COLUMN ITV_BLOCK.itv_id is 'Id of the ITV';
COMMENT ON COLUMN ITV_BLOCK.itb_obj_ref is 'Patrimonial Object Reference (uuid)';
COMMENT ON COLUMN ITV_BLOCK.itb_obj_table is 'Associated table in the patrimonial schema';

-- ITV_BLOCK_DATA
create table ITV_BLOCK_DATA (
	id 				bigserial primary key,
	itb_id			bigint not null references ITV_BLOCK(id),
	ibd_parent		text not null,
	ibd_code		text not null,
	ibd_value		text
);

COMMENT ON TABLE ITV_BLOCK_DATA is 'This table contains the data of an ITV Block';
COMMENT ON COLUMN ITV_BLOCK_DATA.itb_id is 'Id of the ITV_BLOCK';
COMMENT ON COLUMN ITV_BLOCK_DATA.ibd_parent is 'Parent of field (B or C)';
COMMENT ON COLUMN ITV_BLOCK_DATA.ibd_code is 'Code of the field';
COMMENT ON COLUMN ITV_BLOCK_DATA.ibd_value is 'Value of the field';


-- ITV_PICTURE
create table ITV_PICTURE (
	id 				bigserial primary key,
	itv_id			bigint not null references ITV(id),
	itp_label 		text not null,
	itp_reference   text,
	itp_ucre_id     bigint references users(id) default 0,
	itp_umod_id     bigint references users(id) default 0,
	itp_dcre  		timestamp without time zone  default current_timestamp,
	itp_dmod        timestamp without time zone  default current_timestamp
);

COMMENT ON TABLE ITV_PICTURE is 'This table contains the pictures related to an ITV';
COMMENT ON COLUMN ITV_PICTURE.itv_id is 'Id of the ITV';
COMMENT ON COLUMN ITV_PICTURE.itp_label is 'Name of the picture';
COMMENT ON COLUMN ITV_PICTURE.itp_reference is 'Reference of the picture';
COMMENT ON COLUMN ITV_PICTURE.itp_ucre_id is 'Creator Id';
COMMENT ON COLUMN ITV_PICTURE.itp_umod_id is 'Last modificator Id';
COMMENT ON COLUMN ITV_PICTURE.itp_dcre is 'Creation date';
COMMENT ON COLUMN ITV_PICTURE.itp_dmod is 'Last modification date';