/*
 * Generated by TelosysTools with the custom VEOLIA template
 */
package com.veolia.nextcanope.model;

import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.Date;
import jakarta.persistence.*;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.hibernate.annotations.UpdateTimestamp;
import org.hibernate.annotations.CreationTimestamp;
import org.locationtech.jts.geom.Geometry;


/**
 * JPA entity class for "AppGrid"
 *
 * @author VEOLIA
 *
 */
@Entity
@Table(name="app_grid", schema="nomad" )
@JsonIgnoreProperties(ignoreUnknown = true)
public class AppGrid implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY ---\\
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Long id;

    //--- ENTITY DATA FIELDS ---\\
    @Column(name="geom", length=2147483647)
	@JsonProperty("geom")
    private Geometry geom;
    @Column(name="agr_valid")
    @JsonProperty("agr_valid")
    private Boolean agrValid;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="agr_dcre")
    @CreationTimestamp
    @JsonProperty("agr_dcre")
    private Date agrDcre;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="agr_dmod")
    @UpdateTimestamp
    @JsonProperty("agr_dmod")
    private Date agrDmod;


    //--- ENTITY LINKS ( RELATIONSHIP ) ---\\
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="agr_umod_id", referencedColumnName="id")
	@JsonIgnore
    private Users modifiedBy;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="agr_ucre_id", referencedColumnName="id")
	@JsonIgnore
    private Users createdBy;

    /**
     * Constructor
     */
    public AppGrid() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS ---\\
    public Long getId() {
        return this.id;
    }

    public void setId( Long id ) {
        this.id = id ;
    }

    public Geometry getGeom() {
        return this.geom;
    }

	public void setGeom( Geometry geom ) {
        this.geom = geom ;
    }

    public Boolean getAgrValid() {
        return this.agrValid;
    }

	public void setAgrValid( Boolean agrValid ) {
        this.agrValid = agrValid ;
    }

    public Date getAgrDcre() {
        return this.agrDcre;
    }

	public void setAgrDcre( Date agrDcre ) {
        this.agrDcre = agrDcre ;
    }

    public Date getAgrDmod() {
        return this.agrDmod;
    }

	public void setAgrDmod( Date agrDmod ) {
        this.agrDmod = agrDmod ;
    }

    //--- GETTERS AND SETTERS FOR LINKS ---\\
    public Users getModifiedBy() {
        return this.modifiedBy;
    }

    public void setModifiedBy(Users modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    public Users getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(Users createdBy) {
        this.createdBy = createdBy;
    }

}
