/*
 * Created on 2023-04-03 ( 11:41:17 )
 * Generated by TelosysTools with the custom VEOLIA template
 */
package com.veolia.nextcanope.model;

import java.io.Serializable;


import jakarta.persistence.*;
/**
 * JPA entity class for "AppUser"
 *
 * @author VEOLIA
 *
 */
@Entity
@Table(name="app_user", schema="config" )
public class AppUser implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="first_name", length=2147483647)
    private String firstName ;

    @Column(name="last_name", length=2147483647)
    private String lastName ;

    @Column(name="email", length=2147483647)
    private String email ;


    @Column(name="user_context", columnDefinition = "text")
    private String userContext ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    /**
     * Constructor
     */
    public AppUser() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setFirstName( String firstName ) {
        this.firstName = firstName ;
    }
    public String getFirstName() {
        return this.firstName;
    }

    public void setLastName( String lastName ) {
        this.lastName = lastName ;
    }
    public String getLastName() {
        return this.lastName;
    }

    public void setEmail( String email ) {
        this.email = email ;
    }
    public String getEmail() {
        return this.email;
    }

    public String getUserContext() {   return userContext;   }

    public void setUserContext(String userContext) { this.userContext = userContext;  }

    //--- GETTERS FOR LINKS

}
