/*
 * Generated by TelosysTools with the custom VEOLIA template
 */
package com.veolia.nextcanope.model;

import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.Date;
import jakarta.persistence.*;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.locationtech.jts.geom.Geometry;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;


/**
 * JPA entity class for "AssetForSig"
 *
 * @author VEOLIA
 *
 */
@Entity
@Table(name="asset_for_sig", schema="nomad" )
@JsonIgnoreProperties(ignoreUnknown = true)
public class AssetForSig implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY ---\\
        @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
private Long id;

    //--- ENTITY DATA FIELDS ---\\
    @Column(name="geom", nullable=false, length=2147483647)
	@JsonProperty("geom")
    private Geometry geom;
    @Column(name="afs_informations", nullable=false, length=2147483647)
    @JsonProperty("afs_informations")
    private String afsInformations;

    @Column(name="afs_cache_id")
    @JsonProperty("afs_cache_id")
    private Long afsCacheId;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="afs_dcre")
    @CreationTimestamp
    @JsonProperty("afs_dcre")
    private Date afsDcre;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="afs_dmod")
    @UpdateTimestamp
    @JsonProperty("afs_dmod")
    private Date afsDmod;


    //--- ENTITY LINKS ( RELATIONSHIP ) ---\\
    @ManyToOne
    @JoinColumn(name="lyr_id", referencedColumnName="id")
    private Layer layer;

    @ManyToOne
    @JoinColumn(name="afs_umod_id", referencedColumnName="id")
	@JsonIgnore
    private Users modifiedBy;

    @ManyToOne
    @JoinColumn(name="afs_ucre_id", referencedColumnName="id")
	@JsonIgnore
    private Users createdBy;

    /**
     * Constructor
     */
    public AssetForSig() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS ---\\
    public Long getId() {
        return this.id;
    }

    public void setId( Long id ) {
        this.id = id ;
    }

    public Geometry getGeom() {
        return this.geom;
    }

	public void setGeom( Geometry geom ) {
        this.geom = geom ;
    }

    public String getAfsInformations() {
        return this.afsInformations;
    }

	public void setAfsInformations( String afsInformations ) {
        this.afsInformations = afsInformations ;
    }

    public Long getAfsCacheId() {
        return this.afsCacheId;
    }

	public void setAfsCacheId( Long afsCacheId ) {
        this.afsCacheId = afsCacheId ;
    }

    public Date getAfsDcre() {
        return this.afsDcre;
    }

	public void setAfsDcre( Date afsDcre ) {
        this.afsDcre = afsDcre ;
    }

    public Date getAfsDmod() {
        return this.afsDmod;
    }

	public void setAfsDmod( Date afsDmod ) {
        this.afsDmod = afsDmod ;
    }

    //--- GETTERS AND SETTERS FOR LINKS ---\\
    public Layer getLayer() {
        return this.layer;
    }

    public void setLayer(Layer layer) {
        this.layer = layer;
    }

    public Users getModifiedBy() {
        return this.modifiedBy;
    }

    public void setModifiedBy(Users modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    public Users getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(Users createdBy) {
        this.createdBy = createdBy;
    }

}
