/*
 * Generated by TelosysTools with the custom VEOLIA template
 */
package com.veolia.nextcanope.model;

import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.Date;
import java.util.List;
import jakarta.persistence.*;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;


/**
 * JPA entity class for "AssetType"
 *
 * @author VEOLIA
 *
 */
@Entity
@Table(name="asset_type", schema="nomad" )
@JsonIgnoreProperties(ignoreUnknown = true)
public class AssetType implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY ---\\
        @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
private Long id;

    //--- ENTITY DATA FIELDS ---\\
    @Column(name="ast_code", nullable=false, length=2147483647)
    @JsonProperty("ast_code")
    private String astCode;

    @Column(name="ast_slabel", length=2147483647)
    @JsonProperty("ast_slabel")
    private String astSlabel;

    @Column(name="ast_llabel", length=2147483647)
    @JsonProperty("ast_llabel")
    private String astLlabel;

    @Column(name="ast_valid")
    @JsonProperty("ast_valid")
    private Boolean astValid;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ast_dcre")
    @CreationTimestamp
    @JsonProperty("ast_dcre")
    private Date astDcre;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ast_dmod")
    @UpdateTimestamp
    @JsonProperty("ast_dmod")
    private Date astDmod;


    //--- ENTITY LINKS ( RELATIONSHIP ) ---\\
    @OneToMany(mappedBy="assetType")
    @Fetch(value = FetchMode.SUBSELECT)
    private List<Layer> listOfLayer;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="ast_umod_id", referencedColumnName="id")
	@JsonIgnore
    private Users modifiedBy;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="ast_ucre_id", referencedColumnName="id")
	@JsonIgnore
    private Users createdBy;

    @ManyToOne
    @JoinColumn(name="dom_id", referencedColumnName="id")
    private Domains domains;

    @OneToMany(mappedBy="assetType")
    @Fetch(value = FetchMode.SUBSELECT)
    private List<AstWtr> listOfAstWtr;

    /**
     * Constructor
     */
    public AssetType() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS ---\\
    public Long getId() {
        return this.id;
    }

    public void setId( Long id ) {
        this.id = id ;
    }

    public String getAstCode() {
        return this.astCode;
    }

	public void setAstCode( String astCode ) {
        this.astCode = astCode ;
    }

    public String getAstSlabel() {
        return this.astSlabel;
    }

	public void setAstSlabel( String astSlabel ) {
        this.astSlabel = astSlabel ;
    }

    public String getAstLlabel() {
        return this.astLlabel;
    }

	public void setAstLlabel( String astLlabel ) {
        this.astLlabel = astLlabel ;
    }

    public Boolean getAstValid() {
        return this.astValid;
    }

	public void setAstValid( Boolean astValid ) {
        this.astValid = astValid ;
    }

    public Date getAstDcre() {
        return this.astDcre;
    }

	public void setAstDcre( Date astDcre ) {
        this.astDcre = astDcre ;
    }

    public Date getAstDmod() {
        return this.astDmod;
    }

	public void setAstDmod( Date astDmod ) {
        this.astDmod = astDmod ;
    }

    //--- GETTERS AND SETTERS FOR LINKS ---\\
    public List<Layer> getListOfLayer() {
        return this.listOfLayer;
    }

    public void setListOfLayer(List<Layer> listOfLayer) {
        this.listOfLayer = listOfLayer;
    }

    public Users getModifiedBy() {
        return this.modifiedBy;
    }

    public void setModifiedBy(Users modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    public Users getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(Users createdBy) {
        this.createdBy = createdBy;
    }

    public Domains getDomains() {
        return this.domains;
    }

    public void setDomains(Domains domains) {
        this.domains = domains;
    }

    public List<AstWtr> getListOfAstWtr() {
        return this.listOfAstWtr;
    }

    public void setListOfAstWtr(List<AstWtr> listOfAstWtr) {
        this.listOfAstWtr = listOfAstWtr;
    }

}
