/*
 * Generated by TelosysTools with the custom VEOLIA template
 */
package com.veolia.nextcanope.model;


import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.Date;
import jakarta.persistence.*;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.hibernate.annotations.UpdateTimestamp;
import org.hibernate.annotations.CreationTimestamp;


/**
 * JPA entity class for "AstWtr"
 *
 * @author VEOLIA
 *
 */
@Entity
@Table(name="ast_wtr", schema="nomad" )
@IdClass(AstWtrId.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class AstWtr implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY ---\\
    @Id
    @Column(name="wtr_id", nullable=false, insertable=false, updatable=false)
    private Long wtrId;

    @Id
    @Column(name="ast_id", nullable=false, insertable=false, updatable=false)
    private Long astId;

    //--- ENTITY DATA FIELDS ---\\
    @Column(name="asw_valid")
    @JsonProperty("asw_valid")
    private Boolean aswValid;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="asw_dcre")
    @CreationTimestamp
    @JsonProperty("asw_dcre")
    private Date aswDcre;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="asw_dmod")
    @UpdateTimestamp
    @JsonProperty("asw_dmod")
    private Date aswDmod;


    //--- ENTITY LINKS ( RELATIONSHIP ) ---\\
    @ManyToOne
    @JoinColumn(name="ast_id", referencedColumnName="id")
    private AssetType assetType;

    @ManyToOne
    @JoinColumn(name="wtr_id", referencedColumnName="id")
    private WorkorderTaskReason workorderTaskReason;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="asw_umod_id", referencedColumnName="id")
	@JsonIgnore
    private Users modifiedBy;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="asw_ucre_id", referencedColumnName="id")
	@JsonIgnore
    private Users createdBy;

    /**
     * Constructor
     */
    public AstWtr() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS ---\\
    public Boolean getAswValid() {
        return this.aswValid;
    }

	public void setAswValid( Boolean aswValid ) {
        this.aswValid = aswValid ;
    }

    public Date getAswDcre() {
        return this.aswDcre;
    }

	public void setAswDcre( Date aswDcre ) {
        this.aswDcre = aswDcre ;
    }

    public Date getAswDmod() {
        return this.aswDmod;
    }

	public void setAswDmod( Date aswDmod ) {
        this.aswDmod = aswDmod ;
    }

    //--- GETTERS AND SETTERS FOR LINKS ---\\
    public AssetType getAssetType() {
        return this.assetType;
    }

    public void setAssetType(AssetType assetType) {
        this.assetType = assetType;
    }

    public WorkorderTaskReason getWorkorderTaskReason() {
        return this.workorderTaskReason;
    }

    public void setWorkorderTaskReason(WorkorderTaskReason workorderTaskReason) {
        this.workorderTaskReason = workorderTaskReason;
    }

    public Users getModifiedBy() {
        return this.modifiedBy;
    }

    public void setModifiedBy(Users modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    public Users getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(Users createdBy) {
        this.createdBy = createdBy;
    }

}
