/*
 * Generated by TelosysTools with the custom VEOLIA template
 */
package com.veolia.nextcanope.model;

import java.io.Serializable;
import java.util.Date;
import jakarta.persistence.*;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * JPA entity class for "Basemaps"
 *
 * @author VEOLIA
 *
 */
@Entity
@Table(name="basemaps", schema="nomad" )
public class Basemaps implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="map_slabel", length=2147483647)
    private String mapSlabel ;

    @Column(name="map_llabel", length=2147483647)
    private String mapLlabel ;

    @Column(name="map_type", length=2147483647)
    private String mapType ;

    @Column(name="map_url", length=2147483647)
    private String mapUrl ;

    @Column(name="map_layer", length=2147483647)
    private String mapLayer ;

    @Column(name="map_matrixset", length=2147483647)
    private String mapMatrixset ;

    @Column(name="map_format", length=2147483647)
    private String mapFormat ;

    @Column(name="map_projection", length=2147483647)
    private String mapProjection ;

    @Column(name="map_tilegrid", length=2147483647)
    private String mapTilegrid ;

    @Column(name="map_style", length=2147483647)
    private String mapStyle ;

    @Column(name="map_attributions", length=2147483647)
    private String mapAttributions ;

    @Column(name="map_default")
    private Boolean mapDefault ;

    @Column(name="map_display")
    private Boolean mapDisplay ;

    @Lob
    @Column(name="map_thumbnail")
    private byte[] mapThumbnail ;

    @Column(name="map_valid")
    private Boolean mapValid ;

    @Column(name="map_ucre_id")
    private Long mapUcreId ;

    @Column(name="map_umod_id")
    private Long mapUmodId ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="map_dcre")
    private Date mapDcre ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="map_dmod")
    private Date mapDmod ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    @ManyToOne
    @JoinColumn(name="map_ucre_id", referencedColumnName="id", insertable=false, updatable=false)
	@JsonIgnore
    private Users createdBy ; 


    @ManyToOne
    @JoinColumn(name="map_umod_id", referencedColumnName="id", insertable=false, updatable=false)
	@JsonIgnore
    private Users modifiedBy ; 


    /**
     * Constructor
     */
    public Basemaps() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    public void setMapSlabel( String mapSlabel ) {
        this.mapSlabel = mapSlabel ;
    }
    public String getMapSlabel() {
        return this.mapSlabel;
    }

    public void setMapLlabel( String mapLlabel ) {
        this.mapLlabel = mapLlabel ;
    }
    public String getMapLlabel() {
        return this.mapLlabel;
    }

    public void setMapType( String mapType ) {
        this.mapType = mapType ;
    }
    public String getMapType() {
        return this.mapType;
    }

    public void setMapUrl( String mapUrl ) {
        this.mapUrl = mapUrl ;
    }
    public String getMapUrl() {
        return this.mapUrl;
    }

    public void setMapLayer( String mapLayer ) {
        this.mapLayer = mapLayer ;
    }
    public String getMapLayer() {
        return this.mapLayer;
    }

    public void setMapMatrixset( String mapMatrixset ) {
        this.mapMatrixset = mapMatrixset ;
    }
    public String getMapMatrixset() {
        return this.mapMatrixset;
    }

    public void setMapFormat( String mapFormat ) {
        this.mapFormat = mapFormat ;
    }
    public String getMapFormat() {
        return this.mapFormat;
    }

    public void setMapProjection( String mapProjection ) {
        this.mapProjection = mapProjection ;
    }
    public String getMapProjection() {
        return this.mapProjection;
    }

    public void setMapTilegrid( String mapTilegrid ) {
        this.mapTilegrid = mapTilegrid ;
    }
    public String getMapTilegrid() {
        return this.mapTilegrid;
    }

    public void setMapStyle( String mapStyle ) {
        this.mapStyle = mapStyle ;
    }
    public String getMapStyle() {
        return this.mapStyle;
    }

    public void setMapAttributions( String mapAttributions ) {
        this.mapAttributions = mapAttributions ;
    }
    public String getMapAttributions() {
        return this.mapAttributions;
    }

    public void setMapDefault( Boolean mapDefault ) {
        this.mapDefault = mapDefault ;
    }
    public Boolean getMapDefault() {
        return this.mapDefault;
    }

    public void setMapDisplay( Boolean mapDisplay ) {
        this.mapDisplay = mapDisplay ;
    }
    public Boolean getMapDisplay() {
        return this.mapDisplay;
    }

    public void setMapThumbnail( byte[] mapThumbnail ) {
        this.mapThumbnail = mapThumbnail ;
    }
    public byte[] getMapThumbnail() {
        return this.mapThumbnail;
    }

    public void setMapValid( Boolean mapValid ) {
        this.mapValid = mapValid ;
    }
    public Boolean getMapValid() {
        return this.mapValid;
    }

    public void setMapUcreId( Long mapUcreId ) {
        this.mapUcreId = mapUcreId ;
    }
    public Long getMapUcreId() {
        return this.mapUcreId;
    }

    public void setMapUmodId( Long mapUmodId ) {
        this.mapUmodId = mapUmodId ;
    }
    public Long getMapUmodId() {
        return this.mapUmodId;
    }

    public void setMapDcre( Date mapDcre ) {
        this.mapDcre = mapDcre ;
    }
    public Date getMapDcre() {
        return this.mapDcre;
    }

    public void setMapDmod( Date mapDmod ) {
        this.mapDmod = mapDmod ;
    }
    public Date getMapDmod() {
        return this.mapDmod;
    }

    //--- GETTERS FOR LINKS
    public Users getCreatedBy() {
        return this.createdBy;
    } 

    public Users getModifiedBy() {
        return this.modifiedBy;
    } 


}
