/*
 * Created on 2023-04-03 ( 11:41:17 )
 * Generated by TelosysTools with the custom VEOLIA template
 */
package com.veolia.nextcanope.model;

import java.io.Serializable;
import jakarta.persistence.*;

/**
 * JPA entity class for "Basemaps"
 *
 * @author VEOLIA
 *
 */
@Entity
@Table(name="basemaps", schema="config" )
public class Basemaps implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="alias", length=250)
    private String alias ;

    @Column(name="type", length=2147483647)
    private String type ;

    @Column(name="url", length=2147483647)
    private String url ;

    @Column(name="layer", length=2147483647)
    private String layer ;

    @Column(name="matrixset", length=2147483647)
    private String matrixset ;

    @Column(name="format", length=2147483647)
    private String format ;

    @Column(name="projection", length=2147483647)
    private String projection ;

    @Column(name="tilegrid", length=2147483647)
    private String tilegrid ;

    @Column(name="style", length=2147483647)
    private String style ;

    @Column(name="attributions", length=2147483647)
    private String attributions ;

    @Column(name="default")
    private Boolean default_ ;

    @Column(name="display")
    private Boolean display ;

    @Lob
    @Column(name="thumbnail")
    private byte[] thumbnail ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    /**
     * Constructor
     */
    public Basemaps() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setAlias( String alias ) {
        this.alias = alias ;
    }
    public String getAlias() {
        return this.alias;
    }

    public void setType( String type ) {
        this.type = type ;
    }
    public String getType() {
        return this.type;
    }

    public void setUrl( String url ) {
        this.url = url ;
    }
    public String getUrl() {
        return this.url;
    }

    public void setLayer( String layer ) {
        this.layer = layer ;
    }
    public String getLayer() {
        return this.layer;
    }

    public void setMatrixset( String matrixset ) {
        this.matrixset = matrixset ;
    }
    public String getMatrixset() {
        return this.matrixset;
    }

    public void setFormat( String format ) {
        this.format = format ;
    }
    public String getFormat() {
        return this.format;
    }

    public void setProjection( String projection ) {
        this.projection = projection ;
    }
    public String getProjection() {
        return this.projection;
    }

    public void setTilegrid( String tilegrid ) {
        this.tilegrid = tilegrid ;
    }
    public String getTilegrid() {
        return this.tilegrid;
    }

    public void setStyle( String style ) {
        this.style = style ;
    }
    public String getStyle() {
        return this.style;
    }

    public void setAttributions( String attributions ) {
        this.attributions = attributions ;
    }
    public String getAttributions() {
        return this.attributions;
    }

    public void setDefault( Boolean default_ ) {
        this.default_ = default_ ;
    }
    public Boolean getDefault() {
        return this.default_;
    }

    public void setDisplay( Boolean display ) {
        this.display = display ;
    }
    public Boolean getDisplay() {
        return this.display;
    }

    public void setThumbnail( byte[] thumbnail ) {
        this.thumbnail = thumbnail ;
    }
    public byte[] getThumbnail() {
        return this.thumbnail;
    }

    //--- GETTERS FOR LINKS

}
