/*
 * Created on 2023-04-03 ( 11:41:17 )
 * Generated by TelosysTools with the custom VEOLIA template
 */
package com.veolia.nextcanope.model;

import java.io.Serializable;
import java.util.List;
import jakarta.persistence.*;

/**
 * JPA entity class for "BusinessObject"
 *
 * @author VEOLIA
 *
 */
@Entity
@Table(name="business_object", schema="config" )
public class BusinessObject implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="domain_type", nullable=false, length=2147483647)
    private String domainType ;

    @Column(name="topology_type", length=2147483647)
    private String topologyType ;

    @Column(name="type", nullable=false, length=2147483647)
    private String type ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="domain_type", referencedColumnName="type", insertable=false, updatable=false)
    private Domain domain ; 

    @ManyToOne
    @JoinColumn(name="topology_type", referencedColumnName="type", insertable=false, updatable=false)
    private VlTopologyType vlTopologyType ; 

    @OneToMany(mappedBy="businessObject")
    private List<Layer> listOfLayer ; 


    /**
     * Constructor
     */
    public BusinessObject() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setDomainType( String domainType ) {
        this.domainType = domainType ;
    }
    public String getDomainType() {
        return this.domainType;
    }

    public void setTopologyType( String topologyType ) {
        this.topologyType = topologyType ;
    }
    public String getTopologyType() {
        return this.topologyType;
    }

    public void setType( String type ) {
        this.type = type ;
    }
    public String getType() {
        return this.type;
    }

    //--- GETTERS FOR LINKS
    public Domain getDomain() {
        return this.domain;
    } 

    public VlTopologyType getVlTopologyType() {
        return this.vlTopologyType;
    } 

    public List<Layer> getListOfLayer() {
        return this.listOfLayer;
    } 


}
