/*
 * Generated by TelosysTools with the custom VEOLIA template
 */
package com.veolia.nextcanope.model;

import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.Date;
import java.util.List;
import jakarta.persistence.*;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.stream.Collectors;
import java.util.ArrayList;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import org.locationtech.jts.geom.Geometry;


/**
 * JPA entity class for "Contract"
 *
 * @author VEOLIA
 *
 */
@Entity
@Table(name="contract", schema="nomad" )
@JsonIgnoreProperties(ignoreUnknown = true)
public class Contract implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY ---\\
        @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
private Long id;

    //--- ENTITY DATA FIELDS ---\\
    @Column(name="ctr_code", length=2147483647)
    @JsonProperty("ctr_code")
    private String ctrCode;

    @Column(name="ctr_slabel", length=2147483647)
    @JsonProperty("ctr_slabel")
    private String ctrSlabel;

    @Column(name="ctr_llabel", length=2147483647)
    @JsonProperty("ctr_llabel")
    private String ctrLlabel;

    @Column(name="ctr_valid")
    @JsonProperty("ctr_valid")
    private Boolean ctrValid;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ctr_start_date")
    @JsonProperty("ctr_start_date")
    private Date ctrStartDate;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ctr_end_date")
    @JsonProperty("ctr_end_date")
    private Date ctrEndDate;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ctr_dcre")
    @CreationTimestamp
    @JsonProperty("ctr_dcre")
    private Date ctrDcre;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ctr_dmod")
    @UpdateTimestamp
    @JsonProperty("ctr_dmod")
    private Date ctrDmod;

    @Column(name="geom", length=2147483647)
	@JsonProperty("geom")
    private Geometry geom;

    //--- ENTITY LINKS ( RELATIONSHIP ) ---\\
    @ManyToOne
    @JoinColumn(name="cta_id", referencedColumnName="id")
    private ContractActivity contractActivity;

    @OneToMany(mappedBy="contract")
    private List<OrgCtr> listOfOrgCtr;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="ctr_ucre_id", referencedColumnName="id")
	@JsonIgnore
    private Users createdBy;

    @OneToMany(mappedBy="contract")
    private List<Task> listOfTask;

    @OneToMany(mappedBy="contract")
    private List<UsrCtrPrf> listOfUsrCtrPrf;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="ctr_umod_id", referencedColumnName="id")
	@JsonIgnore
    private Users modifiedBy;

    /**
     * Constructor
     */
    public Contract() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS ---\\
    public Long getId() {
        return this.id;
    }

    public void setId( Long id ) {
        this.id = id ;
    }

    public String getCtrCode() {
        return this.ctrCode;
    }

	public void setCtrCode( String ctrCode ) {
        this.ctrCode = ctrCode ;
    }

    public String getCtrSlabel() {
        return this.ctrSlabel;
    }

	public void setCtrSlabel( String ctrSlabel ) {
        this.ctrSlabel = ctrSlabel ;
    }

    public String getCtrLlabel() {
        return this.ctrLlabel;
    }

	public void setCtrLlabel( String ctrLlabel ) {
        this.ctrLlabel = ctrLlabel ;
    }

    public Boolean getCtrValid() {
        return this.ctrValid;
    }

	public void setCtrValid( Boolean ctrValid ) {
        this.ctrValid = ctrValid ;
    }

    public Date getCtrStartDate() {
        return this.ctrStartDate;
    }

	public void setCtrStartDate( Date ctrStartDate ) {
        this.ctrStartDate = ctrStartDate ;
    }

    public Date getCtrEndDate() {
        return this.ctrEndDate;
    }

	public void setCtrEndDate( Date ctrEndDate ) {
        this.ctrEndDate = ctrEndDate ;
    }

    public Date getCtrDcre() {
        return this.ctrDcre;
    }

	public void setCtrDcre( Date ctrDcre ) {
        this.ctrDcre = ctrDcre ;
    }

    public Date getCtrDmod() {
        return this.ctrDmod;
    }

	public void setCtrDmod( Date ctrDmod ) {
        this.ctrDmod = ctrDmod ;
    }

    public Geometry getGeom() {
        return this.geom;
    }

	public void setGeom( Geometry geom ) {
        this.geom = geom ;
    }

    //--- GETTERS AND SETTERS FOR LINKS ---\\
    public ContractActivity getContractActivity() {
        return this.contractActivity;
    }

    public void setContractActivity(ContractActivity contractActivity) {
        this.contractActivity = contractActivity;
    }

    public List<OrgCtr> getListOfOrgCtr() {
        return this.listOfOrgCtr;
    }

    public void setListOfOrgCtr(List<OrgCtr> listOfOrgCtr) {
        this.listOfOrgCtr = listOfOrgCtr;
    }

    public Users getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(Users createdBy) {
        this.createdBy = createdBy;
    }

    public List<Task> getListOfTask() {
        if (this.listOfTask != null) {
            return this.listOfTask.stream()
                .filter(e -> e.getDeletedAt() == null)
                .collect(Collectors.toList());
        } else {
            return new ArrayList<>();
        }
    }

    public List<Task> getListOfTaskWithDeleted() {
        return this.listOfTask;
    }

    public void setListOfTask(List<Task> listOfTask) {
        this.listOfTask = listOfTask;
    }

    public List<UsrCtrPrf> getListOfUsrCtrPrf() {
        if (this.listOfUsrCtrPrf != null) {
            return this.listOfUsrCtrPrf.stream()
                .filter(e -> e.getDeletedAt() == null)
                .collect(Collectors.toList());
        } else {
            return new ArrayList<>();
        }
    }

    public List<UsrCtrPrf> getListOfUsrCtrPrfWithDeleted() {
        return this.listOfUsrCtrPrf;
    }

    public void setListOfUsrCtrPrf(List<UsrCtrPrf> listOfUsrCtrPrf) {
        this.listOfUsrCtrPrf = listOfUsrCtrPrf;
    }

    public Users getModifiedBy() {
        return this.modifiedBy;
    }

    public void setModifiedBy(Users modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

}
