/*
 * Generated by TelosysTools with the custom VEOLIA template
 */
package com.veolia.nextcanope.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import jakarta.persistence.*;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * JPA entity class for "ContractActivity"
 *
 * @author VEOLIA
 *
 */
@Entity
@Table(name="contract_activity", schema="nomad" )
public class ContractActivity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="cta_code", nullable=false, length=2147483647)
    private String ctaCode ;

    @Column(name="cta_slabel", length=2147483647)
    private String ctaSlabel ;

    @Column(name="cta_llabel", length=2147483647)
    private String ctaLlabel ;

    @Column(name="cta_valid")
    private Boolean ctaValid ;

    @Column(name="cta_ucre_id")
    private Long ctaUcreId ;

    @Column(name="cta_umod_id")
    private Long ctaUmodId ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="cta_dcre")
    private Date ctaDcre ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="cta_dmod")
    private Date ctaDmod ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    @ManyToOne
    @JoinColumn(name="cta_ucre_id", referencedColumnName="id", insertable=false, updatable=false)
	@JsonIgnore
    private Users createdBy ; 


    @OneToMany(mappedBy="contractActivity")
    private List<Contract> listOfContract ; 


    @ManyToOne
    @JoinColumn(name="cta_umod_id", referencedColumnName="id", insertable=false, updatable=false)
	@JsonIgnore
    private Users modifiedBy ; 


    /**
     * Constructor
     */
    public ContractActivity() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    public void setCtaCode( String ctaCode ) {
        this.ctaCode = ctaCode ;
    }
    public String getCtaCode() {
        return this.ctaCode;
    }

    public void setCtaSlabel( String ctaSlabel ) {
        this.ctaSlabel = ctaSlabel ;
    }
    public String getCtaSlabel() {
        return this.ctaSlabel;
    }

    public void setCtaLlabel( String ctaLlabel ) {
        this.ctaLlabel = ctaLlabel ;
    }
    public String getCtaLlabel() {
        return this.ctaLlabel;
    }

    public void setCtaValid( Boolean ctaValid ) {
        this.ctaValid = ctaValid ;
    }
    public Boolean getCtaValid() {
        return this.ctaValid;
    }

    public void setCtaUcreId( Long ctaUcreId ) {
        this.ctaUcreId = ctaUcreId ;
    }
    public Long getCtaUcreId() {
        return this.ctaUcreId;
    }

    public void setCtaUmodId( Long ctaUmodId ) {
        this.ctaUmodId = ctaUmodId ;
    }
    public Long getCtaUmodId() {
        return this.ctaUmodId;
    }

    public void setCtaDcre( Date ctaDcre ) {
        this.ctaDcre = ctaDcre ;
    }
    public Date getCtaDcre() {
        return this.ctaDcre;
    }

    public void setCtaDmod( Date ctaDmod ) {
        this.ctaDmod = ctaDmod ;
    }
    public Date getCtaDmod() {
        return this.ctaDmod;
    }

    //--- GETTERS FOR LINKS
    public Users getCreatedBy() {
        return this.createdBy;
    } 

    public List<Contract> getListOfContract() {
        return this.listOfContract;
    } 

    public Users getModifiedBy() {
        return this.modifiedBy;
    } 


}
