/*
 * Created on 2023-04-03 ( 11:41:17 )
 * Generated by TelosysTools with the custom VEOLIA template
 */
package com.veolia.nextcanope.model;

import java.io.Serializable;
import java.util.List;
import jakarta.persistence.*;

/**
 * JPA entity class for "Domain"
 *
 * @author VEOLIA
 *
 */
@Entity
@Table(name="domain", schema="config" )
public class Domain implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="type", nullable=false, length=2147483647)
    private String type ;

    @Column(name="parent_type", length=2147483647)
    private String parentType ;

    @Column(name="short", length=2147483647)
    private String short_ ;

    @Column(name="alias", length=2147483647)
    private String alias ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="parent_type", referencedColumnName="type", insertable=false, updatable=false)
    private Domain domain ; 

    @OneToMany(mappedBy="domain")
    private List<Layer> listOfLayer ; 

    @OneToMany(mappedBy="domain")
    private List<Tree> listOfTree ; 

    @OneToMany(mappedBy="domain")
    private List<BusinessObject> listOfBusinessObject ; 

    @OneToMany(mappedBy="domain")
    private List<Domain> listOfDomain ; 


    /**
     * Constructor
     */
    public Domain() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setType( String type ) {
        this.type = type ;
    }
    public String getType() {
        return this.type;
    }

    public void setParentType( String parentType ) {
        this.parentType = parentType ;
    }
    public String getParentType() {
        return this.parentType;
    }

    public void setShort( String short_ ) {
        this.short_ = short_ ;
    }
    public String getShort() {
        return this.short_;
    }

    public void setAlias( String alias ) {
        this.alias = alias ;
    }
    public String getAlias() {
        return this.alias;
    }

    //--- GETTERS FOR LINKS
    public Domain getDomain() {
        return this.domain;
    } 

    public List<Layer> getListOfLayer() {
        return this.listOfLayer;
    } 

    public List<Tree> getListOfTree() {
        return this.listOfTree;
    } 

    public List<BusinessObject> getListOfBusinessObject() {
        return this.listOfBusinessObject;
    } 

    public List<Domain> getListOfDomain() {
        return this.listOfDomain;
    } 


}
