/*
 * Generated by TelosysTools with the custom VEOLIA template
 */
package com.veolia.nextcanope.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import jakarta.persistence.*;

import com.fasterxml.jackson.annotation.JsonIgnore;


import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * JPA entity class for "FormTemplate"
 *
 * @author VEOLIA
 *
 */
@Entity
@Table(name="form_template", schema="nomad" )
@JsonIgnoreProperties(ignoreUnknown = true)
public class FormTemplate implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Long id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="fte_code", nullable=false, length=2147483647)
	@JsonProperty("fte_code")
    private String fteCode ;

    @Column(name="fdn_id", nullable=false)
	@JsonProperty("fdn_id")
    private Long fdnId ;

    @Column(name="fte_ucre_id")
	@JsonProperty("fte_ucre_id")
    private Long fteUcreId ;

    @Column(name="fte_umod_id")
	@JsonProperty("fte_umod_id")
    private Long fteUmodId ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fte_dcre")
	@JsonProperty("fte_dcre")
    private Date fteDcre ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fte_dmod")
	@JsonProperty("fte_dmod")
    private Date fteDmod ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fte_ddel")
	@JsonProperty("fte_ddel")
    private Date fteDdel ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    @ManyToOne
    @JoinColumn(name="fdn_id", referencedColumnName="id", insertable=false, updatable=false)
    private FormDefinition formDefinition ; 


    @ManyToOne
    @JoinColumn(name="fte_umod_id", referencedColumnName="id", insertable=false, updatable=false)
	@JsonIgnore
    private Users modifiedBy ; 


    @OneToMany(mappedBy="formTemplate")
    private List<FormTemplateCustom> listOfFormTemplateCustom ; 


    @ManyToOne
    @JoinColumn(name="fte_ucre_id", referencedColumnName="id", insertable=false, updatable=false)
	@JsonIgnore
    private Users createdBy ; 


    /**
     * Constructor
     */
    public FormTemplate() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

	public void setFteCode( String fteCode ) {
        this.fteCode = fteCode ;
    }

    public String getFteCode() {
        return this.fteCode;
    }

	public void setFdnId( Long fdnId ) {
        this.fdnId = fdnId ;
    }

    public Long getFdnId() {
        return this.fdnId;
    }

	public void setFteUcreId( Long fteUcreId ) {
        this.fteUcreId = fteUcreId ;
    }

    public Long getFteUcreId() {
        return this.fteUcreId;
    }

	public void setFteUmodId( Long fteUmodId ) {
        this.fteUmodId = fteUmodId ;
    }

    public Long getFteUmodId() {
        return this.fteUmodId;
    }

	public void setFteDcre( Date fteDcre ) {
        this.fteDcre = fteDcre ;
    }

    public Date getFteDcre() {
        return this.fteDcre;
    }

	public void setFteDmod( Date fteDmod ) {
        this.fteDmod = fteDmod ;
    }

    public Date getFteDmod() {
        return this.fteDmod;
    }

	public void setFteDdel( Date fteDdel ) {
        this.fteDdel = fteDdel ;
    }

    public Date getFteDdel() {
        return this.fteDdel;
    }

    //--- GETTERS FOR LINKS
    public FormDefinition getFormDefinition() {
        return this.formDefinition;
    } 

    public Users getModifiedBy() {
        return this.modifiedBy;
    } 

    public List<FormTemplateCustom> getListOfFormTemplateCustom() {
        return this.listOfFormTemplateCustom;
    } 

    public Users getCreatedBy() {
        return this.createdBy;
    } 


}
