/*
 * Generated by TelosysTools with the custom VEOLIA template
 */
package com.veolia.nextcanope.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import jakarta.persistence.*;

import com.fasterxml.jackson.annotation.JsonIgnore;


import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * JPA entity class for "FormDefinition"
 *
 * @author VEOLIA
 *
 */
@Entity
@Table(name="form_definition", schema="nomad" )
@JsonIgnoreProperties(ignoreUnknown = true)
public class FormDefinition implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Long id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="fdn_definition", nullable=false, length=2147483647)
	@JsonProperty("fdn_definition")
    private String fdnDefinition ;

    @Column(name="fdn_ucre_id")
	@JsonProperty("fdn_ucre_id")
    private Long fdnUcreId ;

    @Column(name="fdn_umod_id")
	@JsonProperty("fdn_umod_id")
    private Long fdnUmodId ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fdn_dcre")
	@JsonProperty("fdn_dcre")
    private Date fdnDcre ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fdn_dmod")
	@JsonProperty("fdn_dmod")
    private Date fdnDmod ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fdn_ddel")
	@JsonProperty("fdn_ddel")
    private Date fdnDdel ;

    @Column(name="fdn_code", nullable=false, length=2147483647)
	@JsonProperty("fdn_code")
    private String fdnCode ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    @ManyToOne
    @JoinColumn(name="fdn_ucre_id", referencedColumnName="id", insertable=false, updatable=false)
	@JsonIgnore
    private Users createdBy ; 


    @OneToMany(mappedBy="formDefinition")
    private List<FormTemplateCustom> listOfFormTemplateCustom ; 


    @OneToMany(mappedBy="formDefinition")
    private List<FormTemplate> listOfFormTemplate ; 


    @ManyToOne
    @JoinColumn(name="fdn_umod_id", referencedColumnName="id", insertable=false, updatable=false)
	@JsonIgnore
    private Users modifiedBy ; 


    /**
     * Constructor
     */
    public FormDefinition() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

	public void setFdnDefinition( String fdnDefinition ) {
        this.fdnDefinition = fdnDefinition ;
    }

    public String getFdnDefinition() {
        return this.fdnDefinition;
    }

	public void setFdnUcreId( Long fdnUcreId ) {
        this.fdnUcreId = fdnUcreId ;
    }

    public Long getFdnUcreId() {
        return this.fdnUcreId;
    }

	public void setFdnUmodId( Long fdnUmodId ) {
        this.fdnUmodId = fdnUmodId ;
    }

    public Long getFdnUmodId() {
        return this.fdnUmodId;
    }

	public void setFdnDcre( Date fdnDcre ) {
        this.fdnDcre = fdnDcre ;
    }

    public Date getFdnDcre() {
        return this.fdnDcre;
    }

	public void setFdnDmod( Date fdnDmod ) {
        this.fdnDmod = fdnDmod ;
    }

    public Date getFdnDmod() {
        return this.fdnDmod;
    }

	public void setFdnDdel( Date fdnDdel ) {
        this.fdnDdel = fdnDdel ;
    }

    public Date getFdnDdel() {
        return this.fdnDdel;
    }

	public void setFdnCode( String fdnCode ) {
        this.fdnCode = fdnCode ;
    }

    public String getFdnCode() {
        return this.fdnCode;
    }

    //--- GETTERS FOR LINKS
    public Users getCreatedBy() {
        return this.createdBy;
    } 

    public List<FormTemplateCustom> getListOfFormTemplateCustom() {
        return this.listOfFormTemplateCustom;
    } 

    public List<FormTemplate> getListOfFormTemplate() {
        return this.listOfFormTemplate;
    } 

    public Users getModifiedBy() {
        return this.modifiedBy;
    } 


}
