/*
 * Created on 2023-05-15 ( 10:43:07 )
 * Generated by TelosysTools with the custom VEOLIA template
 */
package com.veolia.nextcanope.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import jakarta.persistence.*;

/**
 * JPA entity class for "Intervention"
 *
 * @author VEOLIA
 *
 */
@Entity
@Table(name="intervention", schema="nomad" )
public class Intervention implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="reason", length=2147483647)
    private String reason ;

    @Column(name="status", length=2147483647)
    private String status ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="datebegin")
    private Date datebegin ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dateend")
    private Date dateend ;

    @Column(name="urgent")
    private Boolean urgent ;

    @Column(name="appointment")
    private Boolean appointment ;

    @Column(name="x")
    private BigDecimal x ;

    @Column(name="y")
    private BigDecimal y ;

    @Column(name="geom", length=2147483647)
    private String geom ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    /**
     * Constructor
     */
    public Intervention() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setReason( String reason ) {
        this.reason = reason ;
    }
    public String getReason() {
        return this.reason;
    }

    public void setStatus( String status ) {
        this.status = status ;
    }
    public String getStatus() {
        return this.status;
    }

    public void setDatebegin( Date datebegin ) {
        this.datebegin = datebegin ;
    }
    public Date getDatebegin() {
        return this.datebegin;
    }

    public void setDateend( Date dateend ) {
        this.dateend = dateend ;
    }
    public Date getDateend() {
        return this.dateend;
    }

    public void setUrgent( Boolean urgent ) {
        this.urgent = urgent ;
    }
    public Boolean getUrgent() {
        return this.urgent;
    }

    public void setAppointment( Boolean appointment ) {
        this.appointment = appointment ;
    }
    public Boolean getAppointment() {
        return this.appointment;
    }

    public void setX( BigDecimal x ) {
        this.x = x ;
    }
    public BigDecimal getX() {
        return this.x;
    }

    public void setY( BigDecimal y ) {
        this.y = y ;
    }
    public BigDecimal getY() {
        return this.y;
    }

    public void setGeom( String geom ) {
        this.geom = geom ;
    }
    public String getGeom() {
        return this.geom;
    }

    //--- GETTERS FOR LINKS

}
