/*
 * Generated by TelosysTools with the custom VEOLIA template
 */
package com.veolia.nextcanope.model;

import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.Date;
import java.util.List;
import jakarta.persistence.*;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;


/**
 * JPA entity class for "Itv"
 *
 * @author VEOLIA
 *
 */
@Entity
@Table(name="itv", schema="nomad" )
@JsonIgnoreProperties(ignoreUnknown = true)
public class Itv implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY ---\\
        @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
private Long id;

    //--- ENTITY DATA FIELDS ---\\
    @Column(name="itv_filename", nullable=false, length=2147483647)
    @JsonProperty("itv_filename")
    private String itvFilename;

    @Column(name="itv_status", nullable=false, length=2147483647)
    @JsonProperty("itv_status")
    private String itvStatus;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="itv_dcre")
    @CreationTimestamp
    @JsonProperty("itv_dcre")
    private Date itvDcre;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="itv_dmod")
    @UpdateTimestamp
    @JsonProperty("itv_dmod")
    private Date itvDmod;


    //--- ENTITY LINKS ( RELATIONSHIP ) ---\\
    @ManyToOne
    @JoinColumn(name="itv_umod_id", referencedColumnName="id")
	@JsonIgnore
    private Users modifiedBy;

    @ManyToOne
    @JoinColumn(name="itv_ucre_id", referencedColumnName="id")
	@JsonIgnore
    private Users createdBy;

    @OneToMany(cascade = CascadeType.ALL, mappedBy="itv")
    @Fetch(value = FetchMode.SUBSELECT)
    private List<ItvBlock> listOfItvBlock;

    @OneToMany(cascade = CascadeType.ALL, mappedBy="itv")
    @Fetch(value = FetchMode.SUBSELECT)
    private List<ItvPicture> listOfItvPicture;

    /**
     * Constructor
     */
    public Itv() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS ---\\
    public Long getId() {
        return this.id;
    }

    public void setId( Long id ) {
        this.id = id ;
    }

    public String getItvFilename() {
        return this.itvFilename;
    }

	public void setItvFilename( String itvFilename ) {
        this.itvFilename = itvFilename ;
    }

    public String getItvStatus() {
        return this.itvStatus;
    }

	public void setItvStatus( String itvStatus ) {
        this.itvStatus = itvStatus ;
    }

    public Date getItvDcre() {
        return this.itvDcre;
    }

	public void setItvDcre( Date itvDcre ) {
        this.itvDcre = itvDcre ;
    }

    public Date getItvDmod() {
        return this.itvDmod;
    }

	public void setItvDmod( Date itvDmod ) {
        this.itvDmod = itvDmod ;
    }

    //--- GETTERS AND SETTERS FOR LINKS ---\\
    public Users getModifiedBy() {
        return this.modifiedBy;
    }

    public void setModifiedBy(Users modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    public Users getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(Users createdBy) {
        this.createdBy = createdBy;
    }

    public List<ItvBlock> getListOfItvBlock() {
        return this.listOfItvBlock;
    }

    public void setListOfItvBlock(List<ItvBlock> listOfItvBlock) {
        this.listOfItvBlock = listOfItvBlock;
    }

    public List<ItvPicture> getListOfItvPicture() {
        return this.listOfItvPicture;
    }

    public void setListOfItvPicture(List<ItvPicture> listOfItvPicture) {
        this.listOfItvPicture = listOfItvPicture;
    }

}
