/*
 * Generated by TelosysTools with the custom VEOLIA template
 */
package com.veolia.nextcanope.model;

import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;


/**
 * JPA entity class for "ItvBlockData"
 *
 * @author VEOLIA
 *
 */
@Entity
@Table(name="itv_block_data", schema="nomad" )
@JsonIgnoreProperties(ignoreUnknown = true)
public class ItvBlockData implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY ---\\
        @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
private Long id;

    //--- ENTITY DATA FIELDS ---\\
    @Column(name="ibd_parent", nullable=false, length=2147483647)
    @JsonProperty("ibd_parent")
    private String ibdParent;

    @Column(name="ibd_line")
    @JsonProperty("ibd_line")
    private Long ibdLine;

    @Column(name="ibd_code", nullable=false, length=2147483647)
    @JsonProperty("ibd_code")
    private String ibdCode;

    @Column(name="ibd_value", length=2147483647)
    @JsonProperty("ibd_value")
    private String ibdValue;


    //--- ENTITY LINKS ( RELATIONSHIP ) ---\\
    @ManyToOne
    @JoinColumn(name="itb_id", referencedColumnName="id")
    private ItvBlock itvBlock;

    /**
     * Constructor
     */
    public ItvBlockData() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS ---\\
    public Long getId() {
        return this.id;
    }

    public void setId( Long id ) {
        this.id = id ;
    }

    public String getIbdParent() {
        return this.ibdParent;
    }

	public void setIbdParent( String ibdParent ) {
        this.ibdParent = ibdParent ;
    }

    public Long getIbdLine() {
        return this.ibdLine;
    }

	public void setIbdLine( Long ibdLine ) {
        this.ibdLine = ibdLine ;
    }

    public String getIbdCode() {
        return this.ibdCode;
    }

	public void setIbdCode( String ibdCode ) {
        this.ibdCode = ibdCode ;
    }

    public String getIbdValue() {
        return this.ibdValue;
    }

	public void setIbdValue( String ibdValue ) {
        this.ibdValue = ibdValue ;
    }

    //--- GETTERS AND SETTERS FOR LINKS ---\\
    public ItvBlock getItvBlock() {
        return this.itvBlock;
    }

    public void setItvBlock(ItvBlock itvBlock) {
        this.itvBlock = itvBlock;
    }

}
