/*
 * Generated by TelosysTools with the custom VEOLIA template
 */
package com.veolia.nextcanope.model;

import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.Date;
import jakarta.persistence.*;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;


/**
 * JPA entity class for "ItvPicture"
 *
 * @author VEOLIA
 *
 */
@Entity
@Table(name="itv_picture", schema="nomad" )
@JsonIgnoreProperties(ignoreUnknown = true)
public class ItvPicture implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY ---\\
        @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
private Long id;

    //--- ENTITY DATA FIELDS ---\\
    @Column(name="itp_label", nullable=false, length=2147483647)
    @JsonProperty("itp_label")
    private String itpLabel;

    @Column(name="itp_reference", length=2147483647)
    @JsonProperty("itp_reference")
    private String itpReference;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="itp_dcre")
    @CreationTimestamp
    @JsonProperty("itp_dcre")
    private Date itpDcre;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="itp_dmod")
    @UpdateTimestamp
    @JsonProperty("itp_dmod")
    private Date itpDmod;


    //--- ENTITY LINKS ( RELATIONSHIP ) ---\\
    @ManyToOne
    @JoinColumn(name="itp_umod_id", referencedColumnName="id")
	@JsonIgnore
    private Users modifiedBy;

    @ManyToOne
    @JoinColumn(name="itv_id", referencedColumnName="id")
    private Itv itv;

    @ManyToOne
    @JoinColumn(name="itp_ucre_id", referencedColumnName="id")
	@JsonIgnore
    private Users createdBy;

    /**
     * Constructor
     */
    public ItvPicture() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS ---\\
    public Long getId() {
        return this.id;
    }

    public void setId( Long id ) {
        this.id = id ;
    }

    public String getItpLabel() {
        return this.itpLabel;
    }

	public void setItpLabel( String itpLabel ) {
        this.itpLabel = itpLabel ;
    }

    public String getItpReference() {
        return this.itpReference;
    }

	public void setItpReference( String itpReference ) {
        this.itpReference = itpReference ;
    }

    public Date getItpDcre() {
        return this.itpDcre;
    }

	public void setItpDcre( Date itpDcre ) {
        this.itpDcre = itpDcre ;
    }

    public Date getItpDmod() {
        return this.itpDmod;
    }

	public void setItpDmod( Date itpDmod ) {
        this.itpDmod = itpDmod ;
    }

    //--- GETTERS AND SETTERS FOR LINKS ---\\
    public Users getModifiedBy() {
        return this.modifiedBy;
    }

    public void setModifiedBy(Users modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    public Itv getItv() {
        return this.itv;
    }

    public void setItv(Itv itv) {
        this.itv = itv;
    }

    public Users getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(Users createdBy) {
        this.createdBy = createdBy;
    }

}
