/*
 * Generated by TelosysTools with the custom VEOLIA template
 */
package com.veolia.nextcanope.model;

import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.Date;
import java.util.List;
import jakarta.persistence.*;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;


/**
 * JPA entity class for "LayerReferences"
 *
 * @author VEOLIA
 *
 */
@Entity
@Table(name="layer_references", schema="nomad" )
@JsonIgnoreProperties(ignoreUnknown = true)
public class LayerReferences implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY ---\\
        @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
private Long id;

    //--- ENTITY DATA FIELDS ---\\
    @Column(name="lrf_reference_key", nullable=false, length=2147483647)
    @JsonProperty("lrf_reference_key")
    private String lrfReferenceKey;

    @Column(name="lrf_slabel", length=2147483647)
    @JsonProperty("lrf_slabel")
    private String lrfSlabel;

    @Column(name="lrf_llabel", length=2147483647)
    @JsonProperty("lrf_llabel")
    private String lrfLlabel;

    @Column(name="lrf_valid")
    @JsonProperty("lrf_valid")
    private Boolean lrfValid;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lrf_dcre")
    @CreationTimestamp
    @JsonProperty("lrf_dcre")
    private Date lrfDcre;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lrf_dmod")
    @UpdateTimestamp
    @JsonProperty("lrf_dmod")
    private Date lrfDmod;


    //--- ENTITY LINKS ( RELATIONSHIP ) ---\\
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="lrf_umod_id", referencedColumnName="id")
	@JsonIgnore
    private Users modifiedBy;

    @ManyToOne
    @JoinColumn(name="lyr_id", referencedColumnName="id")
    private Layer layer;

    @OneToMany(mappedBy="layerReferences")
    @Fetch(value = FetchMode.SUBSELECT)
    private List<LayerReferencesDefault> listOfLayerReferencesDefault;

    @OneToMany(mappedBy="layerReferences")
    @Fetch(value = FetchMode.SUBSELECT)
    private List<LayerReferencesUser> listOfLayerReferencesUser;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="lrf_ucre_id", referencedColumnName="id")
	@JsonIgnore
    private Users createdBy;

    /**
     * Constructor
     */
    public LayerReferences() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS ---\\
    public Long getId() {
        return this.id;
    }

    public void setId( Long id ) {
        this.id = id ;
    }

    public String getLrfReferenceKey() {
        return this.lrfReferenceKey;
    }

	public void setLrfReferenceKey( String lrfReferenceKey ) {
        this.lrfReferenceKey = lrfReferenceKey ;
    }

    public String getLrfSlabel() {
        return this.lrfSlabel;
    }

	public void setLrfSlabel( String lrfSlabel ) {
        this.lrfSlabel = lrfSlabel ;
    }

    public String getLrfLlabel() {
        return this.lrfLlabel;
    }

	public void setLrfLlabel( String lrfLlabel ) {
        this.lrfLlabel = lrfLlabel ;
    }

    public Boolean getLrfValid() {
        return this.lrfValid;
    }

	public void setLrfValid( Boolean lrfValid ) {
        this.lrfValid = lrfValid ;
    }

    public Date getLrfDcre() {
        return this.lrfDcre;
    }

	public void setLrfDcre( Date lrfDcre ) {
        this.lrfDcre = lrfDcre ;
    }

    public Date getLrfDmod() {
        return this.lrfDmod;
    }

	public void setLrfDmod( Date lrfDmod ) {
        this.lrfDmod = lrfDmod ;
    }

    //--- GETTERS AND SETTERS FOR LINKS ---\\
    public Users getModifiedBy() {
        return this.modifiedBy;
    }

    public void setModifiedBy(Users modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    public Layer getLayer() {
        return this.layer;
    }

    public void setLayer(Layer layer) {
        this.layer = layer;
    }

    public List<LayerReferencesDefault> getListOfLayerReferencesDefault() {
        return this.listOfLayerReferencesDefault;
    }

    public void setListOfLayerReferencesDefault(List<LayerReferencesDefault> listOfLayerReferencesDefault) {
        this.listOfLayerReferencesDefault = listOfLayerReferencesDefault;
    }

    public List<LayerReferencesUser> getListOfLayerReferencesUser() {
        return this.listOfLayerReferencesUser;
    }

    public void setListOfLayerReferencesUser(List<LayerReferencesUser> listOfLayerReferencesUser) {
        this.listOfLayerReferencesUser = listOfLayerReferencesUser;
    }

    public Users getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(Users createdBy) {
        this.createdBy = createdBy;
    }

}
