/*
 * Generated by TelosysTools with the custom VEOLIA template
 */
package com.veolia.nextcanope.model;

import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.Date;
import jakarta.persistence.*;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.hibernate.annotations.UpdateTimestamp;
import org.hibernate.annotations.CreationTimestamp;


/**
 * JPA entity class for "LayerReferencesUser"
 *
 * @author VEOLIA
 *
 */
@Entity
@Table(name="layer_references_user", schema="nomad" )
@JsonIgnoreProperties(ignoreUnknown = true)
public class LayerReferencesUser implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY ---\\
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Long id;

    //--- ENTITY DATA FIELDS ---\\
    @Column(name="lru_position", nullable=false)
    @JsonProperty("lru_position")
    private Integer lruPosition;

    @Column(name="lru_display_type", nullable=false, length=2147483647)
    @JsonProperty("lru_display_type")
    private String lruDisplayType;

    @Column(name="lru_section", length=2147483647)
    @JsonProperty("lru_section")
    private String lruSection;

    @Column(name="lru_isvisible")
    @JsonProperty("lru_isvisible")
    private Boolean lruIsvisible;

    @Column(name="lru_valid")
    @JsonProperty("lru_valid")
    private Boolean lruValid;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lru_dcre")
    @CreationTimestamp
    @JsonProperty("lru_dcre")
    private Date lruDcre;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lru_dmod")
    @UpdateTimestamp
    @JsonProperty("lru_dmod")
    private Date lruDmod;


    //--- ENTITY LINKS ( RELATIONSHIP ) ---\\
    @ManyToOne
    @JoinColumn(name="lrf_id", referencedColumnName="id")
    private LayerReferences layerReferences;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="lru_umod_id", referencedColumnName="id")
	@JsonIgnore
    private Users modifiedBy;

    @ManyToOne
    @JoinColumn(name="lru_user_id", referencedColumnName="id")
    private Users user;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="lru_ucre_id", referencedColumnName="id")
	@JsonIgnore
    private Users createdBy;

    /**
     * Constructor
     */
    public LayerReferencesUser() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS ---\\
    public Long getId() {
        return this.id;
    }

    public void setId( Long id ) {
        this.id = id ;
    }

    public Integer getLruPosition() {
        return this.lruPosition;
    }

	public void setLruPosition( Integer lruPosition ) {
        this.lruPosition = lruPosition ;
    }

    public String getLruDisplayType() {
        return this.lruDisplayType;
    }

	public void setLruDisplayType( String lruDisplayType ) {
        this.lruDisplayType = lruDisplayType ;
    }

    public String getLruSection() {
        return this.lruSection;
    }

	public void setLruSection( String lruSection ) {
        this.lruSection = lruSection ;
    }

    public Boolean getLruIsvisible() {
        return this.lruIsvisible;
    }

	public void setLruIsvisible( Boolean lruIsvisible ) {
        this.lruIsvisible = lruIsvisible ;
    }

    public Boolean getLruValid() {
        return this.lruValid;
    }

	public void setLruValid( Boolean lruValid ) {
        this.lruValid = lruValid ;
    }

    public Date getLruDcre() {
        return this.lruDcre;
    }

	public void setLruDcre( Date lruDcre ) {
        this.lruDcre = lruDcre ;
    }

    public Date getLruDmod() {
        return this.lruDmod;
    }

	public void setLruDmod( Date lruDmod ) {
        this.lruDmod = lruDmod ;
    }

    //--- GETTERS AND SETTERS FOR LINKS ---\\
    public LayerReferences getLayerReferences() {
        return this.layerReferences;
    }

    public void setLayerReferences(LayerReferences layerReferences) {
        this.layerReferences = layerReferences;
    }

    public Users getModifiedBy() {
        return this.modifiedBy;
    }

    public void setModifiedBy(Users modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    public Users getUser() {
        return this.user;
    }

    public void setUser(Users user) {
        this.user = user;
    }

    public Users getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(Users createdBy) {
        this.createdBy = createdBy;
    }

}
