/*
 * Created on 2023-04-03 ( 11:41:17 )
 * Generated by TelosysTools with the custom VEOLIA template
 */
package com.veolia.nextcanope.model;

import java.io.Serializable;
import jakarta.persistence.*;

/**
 * JPA entity class for "Layer"
 *
 * @author VEOLIA
 *
 */
@Entity
@Table(name="layer", schema="config" )
public class Layer implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="num_order")
    private Integer numOrder ;

    @Column(name="domain_type", length=2147483647)
    private String domainType ;

    @Column(name="business_object_type", length=2147483647)
    private String businessObjectType ;

    @Column(name="tree_group_id")
    private Integer treeGroupId ;

    @Column(name="simplified_tree_group_id")
    private Integer simplifiedTreeGroupId ;

    @Column(name="pg_table", length=2147483647)
    private String pgTable ;

    @Column(name="geom_column_name", nullable=false, length=2147483647)
    private String geomColumnName ;

    @Column(name="uuid_column_name", nullable=false, length=2147483647)
    private String uuidColumnName ;

    @Column(name="geom_srid", nullable=false, length=2147483647)
    private String geomSrid ;

    @Column(name="style", length=2147483647)
    private String style ;

    @Column(name="alias", length=2147483647)
    private String alias ;

    @Column(name="display")
    private Boolean display ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="business_object_type", referencedColumnName="type", insertable=false, updatable=false)
    private BusinessObject businessObject ; 

    @ManyToOne
    @JoinColumn(name="domain_type", referencedColumnName="type", insertable=false, updatable=false)
    private Domain domain ; 

    @ManyToOne
    @JoinColumn(name="simplified_tree_group_id", referencedColumnName="id", insertable=false, updatable=false)
    private Tree tree ; 

    @ManyToOne
    @JoinColumn(name="tree_group_id", referencedColumnName="id", insertable=false, updatable=false)
    private Tree tree2 ; 


    /**
     * Constructor
     */
    public Layer() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setNumOrder( Integer numOrder ) {
        this.numOrder = numOrder ;
    }
    public Integer getNumOrder() {
        return this.numOrder;
    }

    public void setDomainType( String domainType ) {
        this.domainType = domainType ;
    }
    public String getDomainType() {
        return this.domainType;
    }

    public void setBusinessObjectType( String businessObjectType ) {
        this.businessObjectType = businessObjectType ;
    }
    public String getBusinessObjectType() {
        return this.businessObjectType;
    }

    public void setTreeGroupId( Integer treeGroupId ) {
        this.treeGroupId = treeGroupId ;
    }
    public Integer getTreeGroupId() {
        return this.treeGroupId;
    }

    public void setSimplifiedTreeGroupId( Integer simplifiedTreeGroupId ) {
        this.simplifiedTreeGroupId = simplifiedTreeGroupId ;
    }
    public Integer getSimplifiedTreeGroupId() {
        return this.simplifiedTreeGroupId;
    }

    public void setPgTable( String pgTable ) {
        this.pgTable = pgTable ;
    }
    public String getPgTable() {
        return this.pgTable;
    }

    public void setGeomColumnName( String geomColumnName ) {
        this.geomColumnName = geomColumnName ;
    }
    public String getGeomColumnName() {
        return this.geomColumnName;
    }

    public void setUuidColumnName( String uuidColumnName ) {
        this.uuidColumnName = uuidColumnName ;
    }
    public String getUuidColumnName() {
        return this.uuidColumnName;
    }

    public void setGeomSrid( String geomSrid ) {
        this.geomSrid = geomSrid ;
    }
    public String getGeomSrid() {
        return this.geomSrid;
    }

    public void setStyle( String style ) {
        this.style = style ;
    }
    public String getStyle() {
        return this.style;
    }

    public void setAlias( String alias ) {
        this.alias = alias ;
    }
    public String getAlias() {
        return this.alias;
    }

    public void setDisplay( Boolean display ) {
        this.display = display ;
    }
    public Boolean getDisplay() {
        return this.display;
    }

    //--- GETTERS FOR LINKS
    public BusinessObject getBusinessObject() {
        return this.businessObject;
    } 

    public Domain getDomain() {
        return this.domain;
    } 

    public Tree getTree() {
        return this.tree;
    } 

    public Tree getTree2() {
        return this.tree2;
    } 


}
