/*
 * Created on 2023-05-15 ( 11:14:14 )
 * Generated by TelosysTools with the custom VEOLIA template
 */
package com.veolia.nextcanope.model;

import java.io.Serializable;
import java.util.Date;
import jakarta.persistence.*;

/**
 * JPA entity class for "LayerReferencesDefault"
 *
 * @author VEOLIA
 *
 */
@Entity
@Table(name="layer_references_default", schema="nomad" )
public class LayerReferencesDefault implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="lrd_id", nullable=false)
    private Long lrdId ;

    @Column(name="lrd_position", nullable=false)
    private Integer lrdPosition ;

    @Column(name="lrd_section", length=2147483647)
    private String lrdSection ;

    @Column(name="lrd_isvisible")
    private Boolean lrdIsvisible ;

    @Column(name="lrd_display_type", nullable=false, length=2147483647)
    private String lrdDisplayType ;

    @Column(name="lrd_ucre_id")
    private Long lrdUcreId ;

    @Column(name="lrd_valid")
    private Boolean lrdValid ;

    @Column(name="lrd_umod_id")
    private Long lrdUmodId ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lrd_dcre")
    private Date lrdDcre ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lrd_dmod")
    private Date lrdDmod ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="lrd_umod_id", referencedColumnName="id", insertable=false, updatable=false)
    private Users modifiedBy ; 

    @ManyToOne
    @JoinColumn(name="lrd_ucre_id", referencedColumnName="id", insertable=false, updatable=false)
    private Users createdBy ; 

    @ManyToOne
    @JoinColumn(name="lrd_id", referencedColumnName="id", insertable=false, updatable=false)
    private LayerReferences layerReferences ; 


    /**
     * Constructor
     */
    public LayerReferencesDefault() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    public void setLrdId( Long lrdId ) {
        this.lrdId = lrdId ;
    }
    public Long getLrdId() {
        return this.lrdId;
    }

    public void setLrdPosition( Integer lrdPosition ) {
        this.lrdPosition = lrdPosition ;
    }
    public Integer getLrdPosition() {
        return this.lrdPosition;
    }

    public void setLrdSection( String lrdSection ) {
        this.lrdSection = lrdSection ;
    }
    public String getLrdSection() {
        return this.lrdSection;
    }

    public void setLrdIsvisible( Boolean lrdIsvisible ) {
        this.lrdIsvisible = lrdIsvisible ;
    }
    public Boolean getLrdIsvisible() {
        return this.lrdIsvisible;
    }

    public void setLrdDisplayType( String lrdDisplayType ) {
        this.lrdDisplayType = lrdDisplayType ;
    }
    public String getLrdDisplayType() {
        return this.lrdDisplayType;
    }

    public void setLrdUcreId( Long lrdUcreId ) {
        this.lrdUcreId = lrdUcreId ;
    }
    public Long getLrdUcreId() {
        return this.lrdUcreId;
    }

    public void setLrdValid( Boolean lrdValid ) {
        this.lrdValid = lrdValid ;
    }
    public Boolean getLrdValid() {
        return this.lrdValid;
    }

    public void setLrdUmodId( Long lrdUmodId ) {
        this.lrdUmodId = lrdUmodId ;
    }
    public Long getLrdUmodId() {
        return this.lrdUmodId;
    }

    public void setLrdDcre( Date lrdDcre ) {
        this.lrdDcre = lrdDcre ;
    }
    public Date getLrdDcre() {
        return this.lrdDcre;
    }

    public void setLrdDmod( Date lrdDmod ) {
        this.lrdDmod = lrdDmod ;
    }
    public Date getLrdDmod() {
        return this.lrdDmod;
    }

    //--- GETTERS FOR LINKS
    public Users getModifiedBy() {
        return this.modifiedBy;
    } 

    public Users getCreatedBy() {
        return this.createdBy;
    } 

    public LayerReferences getLayerReferences() {
        return this.layerReferences;
    } 


}
