/*
 * Generated by TelosysTools with the custom VEOLIA template
 */
package com.veolia.nextcanope.model;

import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.Date;
import java.util.List;
import jakarta.persistence.*;
import java.util.stream.Collectors;
import java.util.ArrayList;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.hibernate.annotations.UpdateTimestamp;
import org.hibernate.annotations.CreationTimestamp;


/**
 * JPA entity class for "Layer"
 *
 * @author VEOLIA
 *
 */
@Entity
@Table(name="layer", schema="nomad" )
@JsonIgnoreProperties(ignoreUnknown = true)
public class Layer implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY ---\\
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Long id;

    //--- ENTITY DATA FIELDS ---\\
    @Column(name="lyr_num_order")
    @JsonProperty("lyr_num_order")
    private Integer lyrNumOrder;

    @Column(name="lyr_table_name", nullable=false, length=2147483647)
    @JsonProperty("lyr_table_name")
    private String lyrTableName;

    @Column(name="lyr_geom_column_name", nullable=false, length=2147483647)
    @JsonProperty("lyr_geom_column_name")
    private String lyrGeomColumnName;

    @Column(name="lyr_uuid_column_name", nullable=false, length=2147483647)
    @JsonProperty("lyr_uuid_column_name")
    private String lyrUuidColumnName;

    @Column(name="lyr_geom_srid", nullable=false, length=2147483647)
    @JsonProperty("lyr_geom_srid")
    private String lyrGeomSrid;

    @Column(name="lyr_slabel", length=2147483647)
    @JsonProperty("lyr_slabel")
    private String lyrSlabel;

    @Column(name="lyr_llabel", length=2147483647)
    @JsonProperty("lyr_llabel")
    private String lyrLlabel;

    @Column(name="lyr_valid")
    @JsonProperty("lyr_valid")
    private Boolean lyrValid;

    @Column(name="lyr_display")
    @JsonProperty("lyr_display")
    private Boolean lyrDisplay;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lyr_dcre")
    @CreationTimestamp
    @JsonProperty("lyr_dcre")
    private Date lyrDcre;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lyr_dmod")
    @UpdateTimestamp
    @JsonProperty("lyr_dmod")
    private Date lyrDmod;


    //--- ENTITY LINKS ( RELATIONSHIP ) ---\\
    @ManyToOne
    @JoinColumn(name="dom_id", referencedColumnName="id")
    private Domains domains;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="lyr_umod_id", referencedColumnName="id")
	@JsonIgnore
    private Users modifiedBy;

    @OneToMany(mappedBy="layer")
    private List<LayerStyle> listOfLayerStyle;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="lyr_ucre_id", referencedColumnName="id")
	@JsonIgnore
    private Users createdBy;

    @ManyToOne
    @JoinColumn(name="ast_id", referencedColumnName="id")
    private AssetType assetType;

    @OneToMany(mappedBy="layer")
    private List<Asset> listOfAsset;

    @OneToMany(mappedBy="layer")
    private List<LayerReferences> listOfLayerReferences;

    /**
     * Constructor
     */
    public Layer() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS ---\\
    public Long getId() {
        return this.id;
    }

    public void setId( Long id ) {
        this.id = id ;
    }

    public Integer getLyrNumOrder() {
        return this.lyrNumOrder;
    }

	public void setLyrNumOrder( Integer lyrNumOrder ) {
        this.lyrNumOrder = lyrNumOrder ;
    }

    public String getLyrTableName() {
        return this.lyrTableName;
    }

	public void setLyrTableName( String lyrTableName ) {
        this.lyrTableName = lyrTableName ;
    }

    public String getLyrGeomColumnName() {
        return this.lyrGeomColumnName;
    }

	public void setLyrGeomColumnName( String lyrGeomColumnName ) {
        this.lyrGeomColumnName = lyrGeomColumnName ;
    }

    public String getLyrUuidColumnName() {
        return this.lyrUuidColumnName;
    }

	public void setLyrUuidColumnName( String lyrUuidColumnName ) {
        this.lyrUuidColumnName = lyrUuidColumnName ;
    }

    public String getLyrGeomSrid() {
        return this.lyrGeomSrid;
    }

	public void setLyrGeomSrid( String lyrGeomSrid ) {
        this.lyrGeomSrid = lyrGeomSrid ;
    }

    public String getLyrSlabel() {
        return this.lyrSlabel;
    }

	public void setLyrSlabel( String lyrSlabel ) {
        this.lyrSlabel = lyrSlabel ;
    }

    public String getLyrLlabel() {
        return this.lyrLlabel;
    }

	public void setLyrLlabel( String lyrLlabel ) {
        this.lyrLlabel = lyrLlabel ;
    }

    public Boolean getLyrValid() {
        return this.lyrValid;
    }

	public void setLyrValid( Boolean lyrValid ) {
        this.lyrValid = lyrValid ;
    }

    public Boolean getLyrDisplay() {
        return this.lyrDisplay;
    }

	public void setLyrDisplay( Boolean lyrDisplay ) {
        this.lyrDisplay = lyrDisplay ;
    }

    public Date getLyrDcre() {
        return this.lyrDcre;
    }

	public void setLyrDcre( Date lyrDcre ) {
        this.lyrDcre = lyrDcre ;
    }

    public Date getLyrDmod() {
        return this.lyrDmod;
    }

	public void setLyrDmod( Date lyrDmod ) {
        this.lyrDmod = lyrDmod ;
    }

    //--- GETTERS AND SETTERS FOR LINKS ---\\
    public Domains getDomains() {
        return this.domains;
    }

    public void setDomains(Domains domains) {
        this.domains = domains;
    }

    public Users getModifiedBy() {
        return this.modifiedBy;
    }

    public void setModifiedBy(Users modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    public List<LayerStyle> getListOfLayerStyle() {
        if (this.listOfLayerStyle != null) {
            return this.listOfLayerStyle.stream()
                .filter(e -> e.getDeletedAt() == null)
                .collect(Collectors.toList());
        } else {
            return new ArrayList<>();
        }
    }

    public List<LayerStyle> getListOfLayerStyleWithDeleted() {
        return this.listOfLayerStyle;
    }

    public void setListOfLayerStyle(List<LayerStyle> listOfLayerStyle) {
        this.listOfLayerStyle = listOfLayerStyle;
    }

    public Users getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(Users createdBy) {
        this.createdBy = createdBy;
    }

    public AssetType getAssetType() {
        return this.assetType;
    }

    public void setAssetType(AssetType assetType) {
        this.assetType = assetType;
    }

    public List<Asset> getListOfAsset() {
        return this.listOfAsset;
    }

    public void setListOfAsset(List<Asset> listOfAsset) {
        this.listOfAsset = listOfAsset;
    }

    public List<LayerReferences> getListOfLayerReferences() {
        return this.listOfLayerReferences;
    }

    public void setListOfLayerReferences(List<LayerReferences> listOfLayerReferences) {
        this.listOfLayerReferences = listOfLayerReferences;
    }

}
