/*
 * Generated by TelosysTools with the custom VEOLIA template
 */
package com.veolia.nextcanope.model;

import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.Date;
import java.util.List;
import jakarta.persistence.*;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;


/**
 * JPA entity class for "OrganizationalUnitType"
 *
 * @author VEOLIA
 *
 */
@Entity
@Table(name="organizational_unit_type", schema="nomad" )
@JsonIgnoreProperties(ignoreUnknown = true)
public class OrganizationalUnitType implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY ---\\
        @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
private Long id;

    //--- ENTITY DATA FIELDS ---\\
    @Column(name="out_code", nullable=false, length=2147483647)
    @JsonProperty("out_code")
    private String outCode;

    @Column(name="out_slabel", nullable=false, length=2147483647)
    @JsonProperty("out_slabel")
    private String outSlabel;

    @Column(name="out_llabel", length=2147483647)
    @JsonProperty("out_llabel")
    private String outLlabel;

    @Column(name="out_valid")
    @JsonProperty("out_valid")
    private Boolean outValid;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="out_dcre")
    @CreationTimestamp
    @JsonProperty("out_dcre")
    private Date outDcre;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="out_dmod")
    @UpdateTimestamp
    @JsonProperty("out_dmod")
    private Date outDmod;


    //--- ENTITY LINKS ( RELATIONSHIP ) ---\\
    @ManyToOne
    @JoinColumn(name="out_ucre_id", referencedColumnName="id")
	@JsonIgnore
    private Users createdBy;

    @OneToMany(mappedBy="organizationalUnitType")
    private List<OrganizationalUnit> listOfOrganizationalUnit;

    @ManyToOne
    @JoinColumn(name="out_umod_id", referencedColumnName="id")
	@JsonIgnore
    private Users modifiedBy;

    /**
     * Constructor
     */
    public OrganizationalUnitType() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS ---\\
    public Long getId() {
        return this.id;
    }

    public void setId( Long id ) {
        this.id = id ;
    }

    public String getOutCode() {
        return this.outCode;
    }

	public void setOutCode( String outCode ) {
        this.outCode = outCode ;
    }

    public String getOutSlabel() {
        return this.outSlabel;
    }

	public void setOutSlabel( String outSlabel ) {
        this.outSlabel = outSlabel ;
    }

    public String getOutLlabel() {
        return this.outLlabel;
    }

	public void setOutLlabel( String outLlabel ) {
        this.outLlabel = outLlabel ;
    }

    public Boolean getOutValid() {
        return this.outValid;
    }

	public void setOutValid( Boolean outValid ) {
        this.outValid = outValid ;
    }

    public Date getOutDcre() {
        return this.outDcre;
    }

	public void setOutDcre( Date outDcre ) {
        this.outDcre = outDcre ;
    }

    public Date getOutDmod() {
        return this.outDmod;
    }

	public void setOutDmod( Date outDmod ) {
        this.outDmod = outDmod ;
    }

    //--- GETTERS AND SETTERS FOR LINKS ---\\
    public Users getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(Users createdBy) {
        this.createdBy = createdBy;
    }

    public List<OrganizationalUnit> getListOfOrganizationalUnit() {
        return this.listOfOrganizationalUnit;
    }

    public void setListOfOrganizationalUnit(List<OrganizationalUnit> listOfOrganizationalUnit) {
        this.listOfOrganizationalUnit = listOfOrganizationalUnit;
    }

    public Users getModifiedBy() {
        return this.modifiedBy;
    }

    public void setModifiedBy(Users modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

}
