/*
 * Generated by TelosysTools with the custom VEOLIA template
 */
package com.veolia.nextcanope.model;


import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.Date;
import jakarta.persistence.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;


/**
 * JPA entity class for "OrgCtr"
 *
 * @author VEOLIA
 *
 */
@Entity
@Table(name="org_ctr", schema="nomad" )
@IdClass(OrgCtrId.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class OrgCtr implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY ---\\
    @Id
    @Column(name="org_id", nullable=false, insertable=false, updatable=false)
    private Long orgId;

    @Id
    @Column(name="ctr_id", nullable=false, insertable=false, updatable=false)
    private Long ctrId;

    //--- ENTITY DATA FIELDS ---\\
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="orc_dcre")
    @CreationTimestamp
    @JsonProperty("orc_dcre")
    private Date orcDcre;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="orc_dmod")
    @UpdateTimestamp
    @JsonProperty("orc_dmod")
    private Date orcDmod;


    //--- ENTITY LINKS ( RELATIONSHIP ) ---\\
    @ManyToOne
    @JoinColumn(name="orc_ucre_id", referencedColumnName="id")
    private Users users;

    @ManyToOne
    @JoinColumn(name="ctr_id", referencedColumnName="id")
    private Contract contract;

    @ManyToOne
    @JoinColumn(name="orc_umod_id", referencedColumnName="id")
    private Users users2;

    @ManyToOne
    @JoinColumn(name="org_id", referencedColumnName="id")
    private OrganizationalUnit organizationalUnit;

    /**
     * Constructor
     */
    public OrgCtr() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS ---\\
    public Date getOrcDcre() {
        return this.orcDcre;
    }

	public void setOrcDcre( Date orcDcre ) {
        this.orcDcre = orcDcre ;
    }

    public Date getOrcDmod() {
        return this.orcDmod;
    }

	public void setOrcDmod( Date orcDmod ) {
        this.orcDmod = orcDmod ;
    }

    //--- GETTERS AND SETTERS FOR LINKS ---\\
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    public Contract getContract() {
        return this.contract;
    }

    public void setContract(Contract contract) {
        this.contract = contract;
    }

    public Users getUsers2() {
        return this.users2;
    }

    public void setUsers2(Users users2) {
        this.users2 = users2;
    }

    public OrganizationalUnit getOrganizationalUnit() {
        return this.organizationalUnit;
    }

    public void setOrganizationalUnit(OrganizationalUnit organizationalUnit) {
        this.organizationalUnit = organizationalUnit;
    }

}
