/*
 * Generated by TelosysTools with the custom VEOLIA template
 */
package com.veolia.nextcanope.model;

import java.io.Serializable;


/**
 * Composite primary key for entity "OrgCtr" ( stored in table "org_ctr" )
 *
 * @author Telosys
 *
 */
public class OrgCtrId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES
    private Contract contract;
    private OrganizationalUnit organizationalUnit;
    /**
     * Constructor
     */
    public OrgCtrId() {
        super();
    }

    public OrgCtrId(
        Contract contract,
        OrganizationalUnit organizationalUnit
    ) {
        super();
        this.contract = contract ;
        this.organizationalUnit = organizationalUnit ;
    }
    
    //--- GETTERS & SETTERS FOR KEY FIELDS
    public Contract getContract() {
        return this.contract;
    }

    public void setContract(Contract contract) {
        this.contract = contract;
    }

    public OrganizationalUnit getOrganizationalUnit() {
        return this.organizationalUnit;
    }

    public void setOrganizationalUnit(OrganizationalUnit organizationalUnit) {
        this.organizationalUnit = organizationalUnit;
    }

}
