/*
 * Generated by TelosysTools with the custom VEOLIA template
 */
package com.veolia.nextcanope.model;

import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.Date;
import java.util.List;
import jakarta.persistence.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;


/**
 * JPA entity class for "Permissions"
 *
 * @author VEOLIA
 *
 */
@Entity
@Table(name="permissions", schema="nomad" )
@JsonIgnoreProperties(ignoreUnknown = true)
public class Permissions implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY ---\\
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Long id;

    //--- ENTITY DATA FIELDS ---\\
    @Column(name="per_code", nullable=false, length=2147483647)
    @JsonProperty("per_code")
    private String perCode;

    @Column(name="per_slabel", nullable=false, length=2147483647)
    @JsonProperty("per_slabel")
    private String perSlabel;

    @Column(name="per_llabel", length=2147483647)
    @JsonProperty("per_llabel")
    private String perLlabel;

    @Column(name="per_valid")
    @JsonProperty("per_valid")
    private Boolean perValid;

    @Column(name="per_ucre_id")
    @JsonProperty("per_ucre_id")
    private Long perUcreId;

    @Column(name="per_umod_id")
    @JsonProperty("per_umod_id")
    private Long perUmodId;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="per_dcre")
    @CreationTimestamp
    @JsonProperty("per_dcre")
    private Date perDcre;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="per_dmod")
    @UpdateTimestamp
    @JsonProperty("per_dmod")
    private Date perDmod;


    //--- ENTITY LINKS ( RELATIONSHIP ) ---\\
    @OneToMany(mappedBy="permissions")
    private List<PrfPer> listOfPrfPer;

    /**
     * Constructor
     */
    public Permissions() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS ---\\
    public Long getId() {
        return this.id;
    }

    public void setId( Long id ) {
        this.id = id ;
    }

    public String getPerCode() {
        return this.perCode;
    }

	public void setPerCode( String perCode ) {
        this.perCode = perCode ;
    }

    public String getPerSlabel() {
        return this.perSlabel;
    }

	public void setPerSlabel( String perSlabel ) {
        this.perSlabel = perSlabel ;
    }

    public String getPerLlabel() {
        return this.perLlabel;
    }

	public void setPerLlabel( String perLlabel ) {
        this.perLlabel = perLlabel ;
    }

    public Boolean getPerValid() {
        return this.perValid;
    }

	public void setPerValid( Boolean perValid ) {
        this.perValid = perValid ;
    }

    public Long getPerUcreId() {
        return this.perUcreId;
    }

	public void setPerUcreId( Long perUcreId ) {
        this.perUcreId = perUcreId ;
    }

    public Long getPerUmodId() {
        return this.perUmodId;
    }

	public void setPerUmodId( Long perUmodId ) {
        this.perUmodId = perUmodId ;
    }

    public Date getPerDcre() {
        return this.perDcre;
    }

	public void setPerDcre( Date perDcre ) {
        this.perDcre = perDcre ;
    }

    public Date getPerDmod() {
        return this.perDmod;
    }

	public void setPerDmod( Date perDmod ) {
        this.perDmod = perDmod ;
    }

    //--- GETTERS AND SETTERS FOR LINKS ---\\
    public List<PrfPer> getListOfPrfPer() {
        return this.listOfPrfPer;
    }

    public void setListOfPrfPer(List<PrfPer> listOfPrfPer) {
        this.listOfPrfPer = listOfPrfPer;
    }

}
