/*
 * Generated by TelosysTools with the custom VEOLIA template
 */
package com.veolia.nextcanope.model;


import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.Date;
import jakarta.persistence.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;


/**
 * JPA entity class for "PrfPer"
 *
 * @author VEOLIA
 *
 */
@Entity
@Table(name="prf_per", schema="nomad" )
@IdClass(PrfPerId.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class PrfPer implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY ---\\
    @Id
    @Column(name="prf_id", nullable=false, insertable=false, updatable=false)
    private Long prfId;

    @Id
    @Column(name="per_id", nullable=false, insertable=false, updatable=false)
    private Long perId;

    //--- ENTITY DATA FIELDS ---\\
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="prp_dcre")
    @CreationTimestamp
    @JsonProperty("prp_dcre")
    private Date prpDcre;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="prp_dmod")
    @UpdateTimestamp
    @JsonProperty("prp_dmod")
    private Date prpDmod;


    //--- ENTITY LINKS ( RELATIONSHIP ) ---\\
    @ManyToOne
    @JoinColumn(name="per_id", referencedColumnName="id")
    private Permissions permissions;

    @ManyToOne
    @JoinColumn(name="prp_umod_id", referencedColumnName="id")
    private Users users2;

    @ManyToOne
    @JoinColumn(name="prf_id", referencedColumnName="id")
    private Profile profile;

    @ManyToOne
    @JoinColumn(name="prp_ucre_id", referencedColumnName="id")
    private Users users;

    /**
     * Constructor
     */
    public PrfPer() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS ---\\
    public Date getPrpDcre() {
        return this.prpDcre;
    }

	public void setPrpDcre( Date prpDcre ) {
        this.prpDcre = prpDcre ;
    }

    public Date getPrpDmod() {
        return this.prpDmod;
    }

	public void setPrpDmod( Date prpDmod ) {
        this.prpDmod = prpDmod ;
    }

    //--- GETTERS AND SETTERS FOR LINKS ---\\
    public Permissions getPermissions() {
        return this.permissions;
    }

    public void setPermissions(Permissions permissions) {
        this.permissions = permissions;
    }

    public Users getUsers2() {
        return this.users2;
    }

    public void setUsers2(Users users2) {
        this.users2 = users2;
    }

    public Profile getProfile() {
        return this.profile;
    }

    public void setProfile(Profile profile) {
        this.profile = profile;
    }

    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

}
