/*
 * Generated by TelosysTools with the custom VEOLIA template
 */
package com.veolia.nextcanope.model;

import java.io.Serializable;


/**
 * Composite primary key for entity "PrfPer" ( stored in table "prf_per" )
 *
 * @author Telosys
 *
 */
public class PrfPerId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES
    private Permissions permissions;
    private Profile profile;
    /**
     * Constructor
     */
    public PrfPerId() {
        super();
    }

    public PrfPerId(
        Permissions permissions,
        Profile profile
    ) {
        super();
        this.permissions = permissions ;
        this.profile = profile ;
    }
    
    //--- GETTERS & SETTERS FOR KEY FIELDS
    public Permissions getPermissions() {
        return this.permissions;
    }

    public void setPermissions(Permissions permissions) {
        this.permissions = permissions;
    }

    public Profile getProfile() {
        return this.profile;
    }

    public void setProfile(Profile profile) {
        this.profile = profile;
    }

}
