/*
 * Generated by TelosysTools with the custom VEOLIA template
 */
package com.veolia.nextcanope.model;

import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.Date;
import jakarta.persistence.*;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;


/**
 * JPA entity class for "ReportQuestion"
 *
 * @author VEOLIA
 *
 */
@Entity
@Table(name="report_question", schema="nomad" )
@JsonIgnoreProperties(ignoreUnknown = true)
public class ReportQuestion implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY ---\\
        @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
private Long id;

    //--- ENTITY DATA FIELDS ---\\
    @Column(name="rqn_code", nullable=false, length=2147483647)
    @JsonProperty("rqn_code")
    private String rqnCode;

    @Column(name="rqn_slabel", nullable=false, length=2147483647)
    @JsonProperty("rqn_slabel")
    private String rqnSlabel;

    @Column(name="rqn_llabel", nullable=false, length=2147483647)
    @JsonProperty("rqn_llabel")
    private String rqnLlabel;

    @Column(name="rqn_type", nullable=false, length=2147483647)
    @JsonProperty("rqn_type")
    private String rqnType;

    @Column(name="rqn_required")
    @JsonProperty("rqn_required")
    private Boolean rqnRequired;

    @Column(name="rqn_select_values", length=2147483647)
    @JsonProperty("rqn_select_values")
    private String rqnSelectValues;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="rqn_dcre")
    @CreationTimestamp
    @JsonProperty("rqn_dcre")
    private Date rqnDcre;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="rqn_dmod")
    @UpdateTimestamp
    @JsonProperty("rqn_dmod")
    private Date rqnDmod;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="rqn_ddel")
    @JsonProperty("rqn_ddel")
    private Date deletedAt;


    //--- ENTITY LINKS ( RELATIONSHIP ) ---\\
    @ManyToOne
    @JoinColumn(name="rqn_umod_id", referencedColumnName="id")
	@JsonIgnore
    private Users modifiedBy;

    @ManyToOne
    @JoinColumn(name="rqn_ucre_id", referencedColumnName="id")
	@JsonIgnore
    private Users createdBy;

    /**
     * Constructor
     */
    public ReportQuestion() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS ---\\
    public Long getId() {
        return this.id;
    }

    public void setId( Long id ) {
        this.id = id ;
    }

    public String getRqnCode() {
        return this.rqnCode;
    }

	public void setRqnCode( String rqnCode ) {
        this.rqnCode = rqnCode ;
    }

    public String getRqnSlabel() {
        return this.rqnSlabel;
    }

	public void setRqnSlabel( String rqnSlabel ) {
        this.rqnSlabel = rqnSlabel ;
    }

    public String getRqnLlabel() {
        return this.rqnLlabel;
    }

	public void setRqnLlabel( String rqnLlabel ) {
        this.rqnLlabel = rqnLlabel ;
    }

    public String getRqnType() {
        return this.rqnType;
    }

	public void setRqnType( String rqnType ) {
        this.rqnType = rqnType ;
    }

    public Boolean getRqnRequired() {
        return this.rqnRequired;
    }

	public void setRqnRequired( Boolean rqnRequired ) {
        this.rqnRequired = rqnRequired ;
    }

    public String getRqnSelectValues() {
        return this.rqnSelectValues;
    }

	public void setRqnSelectValues( String rqnSelectValues ) {
        this.rqnSelectValues = rqnSelectValues ;
    }

    public Date getRqnDcre() {
        return this.rqnDcre;
    }

	public void setRqnDcre( Date rqnDcre ) {
        this.rqnDcre = rqnDcre ;
    }

    public Date getRqnDmod() {
        return this.rqnDmod;
    }

	public void setRqnDmod( Date rqnDmod ) {
        this.rqnDmod = rqnDmod ;
    }

    public Date getDeletedAt() {
        return deletedAt;
    }

    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }

    public void markAsDeleted(Users user) {
        this.deletedAt = new Date();
        this.modifiedBy = user;
    }

    //--- GETTERS AND SETTERS FOR LINKS ---\\
    public Users getModifiedBy() {
        return this.modifiedBy;
    }

    public void setModifiedBy(Users modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    public Users getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(Users createdBy) {
        this.createdBy = createdBy;
    }

}
