/*
 * Generated by TelosysTools with the custom VEOLIA template
 */
package com.veolia.nextcanope.model;

import java.io.Serializable;
import java.util.Date;
import jakarta.persistence.*;

import com.fasterxml.jackson.annotation.JsonIgnore;


import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * JPA entity class for "Report"
 *
 * @author VEOLIA
 *
 */
@Entity
@Table(name="report", schema="nomad" )
@JsonIgnoreProperties(ignoreUnknown = true)
public class Report implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Long id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="tsk_id")
	@JsonProperty("tsk_id")
    private Long tskId ;

    @Column(name="rpt_key", length=2147483647)
	@JsonProperty("rpt_key")
    private String rptKey ;

    @Column(name="rpt_ucre_id")
	@JsonProperty("rpt_ucre_id")
    private Long rptUcreId ;

    @Column(name="rpt_label", length=2147483647)
	@JsonProperty("rpt_label")
    private String rptLabel ;

    @Column(name="rpt_umod_id")
	@JsonProperty("rpt_umod_id")
    private Long rptUmodId ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="rpt_dcre")
	@JsonProperty("rpt_dcre")
    private Date rptDcre ;

    @Column(name="rpt_value", length=2147483647)
	@JsonProperty("rpt_value")
    private String rptValue ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="rpt_dmod")
	@JsonProperty("rpt_dmod")
    private Date rptDmod ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="rpt_ddel")
	@JsonProperty("rpt_ddel")
    private Date rptDdel ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="rpt_umod_id", referencedColumnName="id", insertable=false, updatable=false)
	@JsonIgnore
    private Users modifiedBy ; 


    @ManyToOne
    @JoinColumn(name="tsk_id", referencedColumnName="id", insertable=false, updatable=false)
    private Task task ; 


    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="rpt_ucre_id", referencedColumnName="id", insertable=false, updatable=false)
	@JsonIgnore
    private Users createdBy ; 


    /**
     * Constructor
     */
    public Report() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

	public void setTskId( Long tskId ) {
        this.tskId = tskId ;
    }

    public Long getTskId() {
        return this.tskId;
    }

	public void setRptKey( String rptKey ) {
        this.rptKey = rptKey ;
    }

    public String getRptKey() {
        return this.rptKey;
    }

	public void setRptUcreId( Long rptUcreId ) {
        this.rptUcreId = rptUcreId ;
    }

    public Long getRptUcreId() {
        return this.rptUcreId;
    }

	public void setRptLabel( String rptLabel ) {
        this.rptLabel = rptLabel ;
    }

    public String getRptLabel() {
        return this.rptLabel;
    }

	public void setRptUmodId( Long rptUmodId ) {
        this.rptUmodId = rptUmodId ;
    }

    public Long getRptUmodId() {
        return this.rptUmodId;
    }

	public void setRptDcre( Date rptDcre ) {
        this.rptDcre = rptDcre ;
    }

    public Date getRptDcre() {
        return this.rptDcre;
    }

	public void setRptValue( String rptValue ) {
        this.rptValue = rptValue ;
    }

    public String getRptValue() {
        return this.rptValue;
    }

	public void setRptDmod( Date rptDmod ) {
        this.rptDmod = rptDmod ;
    }

    public Date getRptDmod() {
        return this.rptDmod;
    }

	public void setRptDdel( Date rptDdel ) {
        this.rptDdel = rptDdel ;
    }

    public Date getRptDdel() {
        return this.rptDdel;
    }

    //--- GETTERS FOR LINKS
    public Users getModifiedBy() {
        return this.modifiedBy;
    } 

    public Task getTask() {
        return this.task;
    } 

    public Users getCreatedBy() {
        return this.createdBy;
    } 


}
