/*
 * Generated by TelosysTools with the custom VEOLIA template
 */
package com.veolia.nextcanope.model;

import java.io.Serializable;
import java.util.Date;
import jakarta.persistence.*;

import com.fasterxml.jackson.annotation.JsonIgnore;


import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * JPA entity class for "StyleImage"
 *
 * @author VEOLIA
 *
 */
@Entity
@Table(name="style_image", schema="nomad" )
@JsonIgnoreProperties(ignoreUnknown = true)
public class StyleImage implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Long id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="syd_id", nullable=false)
	@JsonProperty("syd_id")
    private Long sydId ;

    @Column(name="syi_code", nullable=false, length=2147483647)
	@JsonProperty("syi_code")
    private String syiCode ;

    @Column(name="syi_source", nullable=false, length=2147483647)
	@JsonProperty("syi_source")
    private String syiSource ;

    @Column(name="syi_ucre_id")
	@JsonProperty("syi_ucre_id")
    private Long syiUcreId ;

    @Column(name="syi_umod_id")
	@JsonProperty("syi_umod_id")
    private Long syiUmodId ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="syi_dcre")
	@JsonProperty("syi_dcre")
    private Date syiDcre ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="syi_dmod")
	@JsonProperty("syi_dmod")
    private Date syiDmod ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="syi_ddel")
	@JsonProperty("syi_ddel")
    private Date syiDdel ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    @ManyToOne
    @JoinColumn(name="syi_ucre_id", referencedColumnName="id", insertable=false, updatable=false)
	@JsonIgnore
    private Users createdBy ; 


    @ManyToOne
    @JoinColumn(name="syi_umod_id", referencedColumnName="id", insertable=false, updatable=false)
	@JsonIgnore
    private Users modifiedBy ; 


    @ManyToOne
    @JoinColumn(name="syd_id", referencedColumnName="id", insertable=false, updatable=false)
    private StyleDefinition styleDefinition ; 


    /**
     * Constructor
     */
    public StyleImage() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

	public void setSydId( Long sydId ) {
        this.sydId = sydId ;
    }

    public Long getSydId() {
        return this.sydId;
    }

	public void setSyiCode( String syiCode ) {
        this.syiCode = syiCode ;
    }

    public String getSyiCode() {
        return this.syiCode;
    }

	public void setSyiSource( String syiSource ) {
        this.syiSource = syiSource ;
    }

    public String getSyiSource() {
        return this.syiSource;
    }

	public void setSyiUcreId( Long syiUcreId ) {
        this.syiUcreId = syiUcreId ;
    }

    public Long getSyiUcreId() {
        return this.syiUcreId;
    }

	public void setSyiUmodId( Long syiUmodId ) {
        this.syiUmodId = syiUmodId ;
    }

    public Long getSyiUmodId() {
        return this.syiUmodId;
    }

	public void setSyiDcre( Date syiDcre ) {
        this.syiDcre = syiDcre ;
    }

    public Date getSyiDcre() {
        return this.syiDcre;
    }

	public void setSyiDmod( Date syiDmod ) {
        this.syiDmod = syiDmod ;
    }

    public Date getSyiDmod() {
        return this.syiDmod;
    }

	public void setSyiDdel( Date syiDdel ) {
        this.syiDdel = syiDdel ;
    }

    public Date getSyiDdel() {
        return this.syiDdel;
    }

    //--- GETTERS FOR LINKS
    public Users getCreatedBy() {
        return this.createdBy;
    } 

    public Users getModifiedBy() {
        return this.modifiedBy;
    } 

    public StyleDefinition getStyleDefinition() {
        return this.styleDefinition;
    } 


}
