/*
 * Generated by TelosysTools with the custom VEOLIA template
 */
package com.veolia.nextcanope.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import jakarta.persistence.*;

import com.fasterxml.jackson.annotation.JsonIgnore;


import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * JPA entity class for "StyleDefinition"
 *
 * @author VEOLIA
 *
 */
@Entity
@Table(name="style_definition", schema="nomad" )
@JsonIgnoreProperties(ignoreUnknown = true)
public class StyleDefinition implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Long id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="syd_code", nullable=false, length=2147483647)
	@JsonProperty("syd_code")
    private String sydCode ;

    @Column(name="syd_definition", nullable=false, length=2147483647)
	@JsonProperty("syd_definition")
    private String sydDefinition ;

    @Column(name="syd_ucre_id")
	@JsonProperty("syd_ucre_id")
    private Long sydUcreId ;

    @Column(name="syd_umod_id")
	@JsonProperty("syd_umod_id")
    private Long sydUmodId ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="syd_dcre")
	@JsonProperty("syd_dcre")
    private Date sydDcre ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="syd_dmod")
	@JsonProperty("syd_dmod")
    private Date sydDmod ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="syd_ddel")
	@JsonProperty("syd_ddel")
    private Date sydDdel ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    @ManyToOne
    @JoinColumn(name="syd_umod_id", referencedColumnName="id", insertable=false, updatable=false)
	@JsonIgnore
    private Users modifiedBy ; 


    @OneToMany(mappedBy="styleDefinition")
    private List<LayerStyleCustom> listOfLayerStyleCustom ; 


    @ManyToOne
    @JoinColumn(name="syd_ucre_id", referencedColumnName="id", insertable=false, updatable=false)
	@JsonIgnore
    private Users createdBy ; 


    @OneToMany(mappedBy="styleDefinition")
    private List<StyleImage> listOfStyleImage ; 


    @OneToMany(mappedBy="styleDefinition")
    private List<LayerStyle> listOfLayerStyle ; 


    /**
     * Constructor
     */
    public StyleDefinition() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

	public void setSydCode( String sydCode ) {
        this.sydCode = sydCode ;
    }

    public String getSydCode() {
        return this.sydCode;
    }

	public void setSydDefinition( String sydDefinition ) {
        this.sydDefinition = sydDefinition ;
    }

    public String getSydDefinition() {
        return this.sydDefinition;
    }

	public void setSydUcreId( Long sydUcreId ) {
        this.sydUcreId = sydUcreId ;
    }

    public Long getSydUcreId() {
        return this.sydUcreId;
    }

	public void setSydUmodId( Long sydUmodId ) {
        this.sydUmodId = sydUmodId ;
    }

    public Long getSydUmodId() {
        return this.sydUmodId;
    }

	public void setSydDcre( Date sydDcre ) {
        this.sydDcre = sydDcre ;
    }

    public Date getSydDcre() {
        return this.sydDcre;
    }

	public void setSydDmod( Date sydDmod ) {
        this.sydDmod = sydDmod ;
    }

    public Date getSydDmod() {
        return this.sydDmod;
    }

	public void setSydDdel( Date sydDdel ) {
        this.sydDdel = sydDdel ;
    }

    public Date getSydDdel() {
        return this.sydDdel;
    }

    //--- GETTERS FOR LINKS
    public Users getModifiedBy() {
        return this.modifiedBy;
    } 

    public List<LayerStyleCustom> getListOfLayerStyleCustom() {
        return this.listOfLayerStyleCustom;
    } 

    public Users getCreatedBy() {
        return this.createdBy;
    } 

    public List<StyleImage> getListOfStyleImage() {
        return this.listOfStyleImage;
    } 

    public List<LayerStyle> getListOfLayerStyle() {
        return this.listOfLayerStyle;
    } 


}
