/*
 * Created on 2023-04-03 ( 11:41:17 )
 * Generated by TelosysTools with the custom VEOLIA template
 */
package com.veolia.nextcanope.model;

import java.io.Serializable;
import java.util.List;
import jakarta.persistence.*;

/**
 * JPA entity class for "Tree"
 *
 * @author VEOLIA
 *
 */
@Entity
@Table(name="tree", schema="config" )
public class Tree implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="domain_type", length=2147483647)
    private String domainType ;

    @Column(name="parent_id")
    private Integer parentId ;

    @Column(name="num_order")
    private Integer numOrder ;

    @Column(name="alias", length=2147483647)
    private String alias ;

    @Column(name="short", length=2147483647)
    private String short_ ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="tree")
    private List<Layer> listOfLayer ; 

    @OneToMany(mappedBy="tree2")
    private List<Layer> listOfLayer2 ; 

    @OneToMany(mappedBy="tree")
    private List<Tree> listOfTree ; 

    @ManyToOne
    @JoinColumn(name="parent_id", referencedColumnName="id", insertable=false, updatable=false)
    private Tree tree ; 

    @ManyToOne
    @JoinColumn(name="domain_type", referencedColumnName="type", insertable=false, updatable=false)
    private Domain domain ; 


    /**
     * Constructor
     */
    public Tree() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setDomainType( String domainType ) {
        this.domainType = domainType ;
    }
    public String getDomainType() {
        return this.domainType;
    }

    public void setParentId( Integer parentId ) {
        this.parentId = parentId ;
    }
    public Integer getParentId() {
        return this.parentId;
    }

    public void setNumOrder( Integer numOrder ) {
        this.numOrder = numOrder ;
    }
    public Integer getNumOrder() {
        return this.numOrder;
    }

    public void setAlias( String alias ) {
        this.alias = alias ;
    }
    public String getAlias() {
        return this.alias;
    }

    public void setShort( String short_ ) {
        this.short_ = short_ ;
    }
    public String getShort() {
        return this.short_;
    }

    //--- GETTERS FOR LINKS
    public List<Layer> getListOfLayer() {
        return this.listOfLayer;
    } 

    public List<Layer> getListOfLayer2() {
        return this.listOfLayer2;
    } 

    public List<Tree> getListOfTree() {
        return this.listOfTree;
    } 

    public Tree getTree() {
        return this.tree;
    } 

    public Domain getDomain() {
        return this.domain;
    } 


}
