/*
 * Generated by TelosysTools with the custom VEOLIA template
 */
package com.veolia.nextcanope.model;

import java.io.Serializable;


/**
 * Composite primary key for entity "UsrCtrPrf" ( stored in table "usr_ctr_prf" )
 *
 * @author Telosys
 *
 */
public class UsrCtrPrfId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private Users user;
    private Contract contract;
    
    /**
     * Constructor
     */
    public UsrCtrPrfId() {
        super();
    }

    /**
     * Constructor with values
     * @param user
     * @param contract
     */
    public UsrCtrPrfId( Users user, Contract contract ) {
        super();
        this.user = user;
        this.contract = contract ;
    }
    
    //--- GETTERS & SETTERS FOR KEY FIELDS


    public Users getUser() {
        return user;
    }

    public void setUser(Users user) {
        this.user = user;
    }

    public Contract getContract() {
        return contract;
    }

    public void setContract(Contract contract) {
        this.contract = contract;
    }

    //--- equals METHOD
	@Override
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		UsrCtrPrfId other = (UsrCtrPrfId) obj; 
		//--- Attribute usrId
		if ( user == null ) {
			if ( other.user != null )
				return false ; 
		} else if ( ! user.equals(other.user) )
			return false ; 
		//--- Attribute ctrId
		if ( user == null ) {
			if ( other.user != null )
				return false ; 
		} else if ( ! user.equals(other.user) )
			return false ; 
		return true; 
	} 

    //--- hashCode METHOD
	@Override
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute usrId
		result = prime * result + ((user == null) ? 0 : user.hashCode() ) ;
		//--- Attribute ctrId
		result = prime * result + ((user == null) ? 0 : user.hashCode() ) ;
		
		return result; 
	} 

    //--- toString METHOD
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(user.getId());
        sb.append("|");
        sb.append(user.getId());
        return sb.toString(); 
    } 

}
