/*
 * Generated by TelosysTools with the custom VEOLIA template
 */
package com.veolia.nextcanope.model;


import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.Date;
import jakarta.persistence.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;


/**
 * JPA entity class for "UsrCtrPrf"
 *
 * @author VEOLIA
 *
 */
@Entity
@Table(name="usr_ctr_prf", schema="nomad" )
@IdClass(UsrCtrPrfId.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class UsrCtrPrf implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY ---\\
    @Id
    @Column(name="usr_id", nullable=false, insertable=false, updatable=false)
    private Long usrId;

    @Id
    @Column(name="ctr_id", nullable=false, insertable=false, updatable=false)
    private Long ctrId;

    //--- ENTITY DATA FIELDS ---\\
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="usc_dcre")
    @CreationTimestamp
    @JsonProperty("usc_dcre")
    private Date uscDcre;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="usc_dmod")
    @UpdateTimestamp
    @JsonProperty("usc_dmod")
    private Date uscDmod;


    //--- ENTITY LINKS ( RELATIONSHIP ) ---\\
    @ManyToOne
    @JoinColumn(name="usc_umod_id", referencedColumnName="id")
    private Users users2;

    @ManyToOne
    @JoinColumn(name="ctr_id", referencedColumnName="id")
    private Contract contract;

    @ManyToOne
    @JoinColumn(name="usc_ucre_id", referencedColumnName="id")
    private Users users;

    @ManyToOne
    @JoinColumn(name="prf_id", referencedColumnName="id")
    private Profile profile;

    @ManyToOne
    @JoinColumn(name="usr_id", referencedColumnName="id")
    private Users users3;

    /**
     * Constructor
     */
    public UsrCtrPrf() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS ---\\
    public Date getUscDcre() {
        return this.uscDcre;
    }

	public void setUscDcre( Date uscDcre ) {
        this.uscDcre = uscDcre ;
    }

    public Date getUscDmod() {
        return this.uscDmod;
    }

	public void setUscDmod( Date uscDmod ) {
        this.uscDmod = uscDmod ;
    }

    //--- GETTERS AND SETTERS FOR LINKS ---\\
    public Users getUsers2() {
        return this.users2;
    }

    public void setUsers2(Users users2) {
        this.users2 = users2;
    }

    public Contract getContract() {
        return this.contract;
    }

    public void setContract(Contract contract) {
        this.contract = contract;
    }

    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    public Profile getProfile() {
        return this.profile;
    }

    public void setProfile(Profile profile) {
        this.profile = profile;
    }

    public Users getUsers3() {
        return this.users3;
    }

    public void setUsers3(Users users3) {
        this.users3 = users3;
    }

}
