/*
 * Generated by TelosysTools with the custom VEOLIA template
 */
package com.veolia.nextcanope.model;

import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.Date;
import jakarta.persistence.*;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;


/**
 * JPA entity class for "VlTopologyType"
 *
 * @author VEOLIA
 *
 */
@Entity
@Table(name="vl_topology_type", schema="nomad" )
@JsonIgnoreProperties(ignoreUnknown = true)
public class VlTopologyType implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY ---\\
        @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
private Long id;

    //--- ENTITY DATA FIELDS ---\\
    @Column(name="tpt_type", nullable=false, length=2147483647)
    @JsonProperty("tpt_type")
    private String tptType;

    @Column(name="tpt_required_fields", length=2147483647)
    @JsonProperty("tpt_required_fields")
    private String tptRequiredFields;

    @Column(name="tpt_valid")
    @JsonProperty("tpt_valid")
    private Boolean tptValid;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tpt_dcre")
    @CreationTimestamp
    @JsonProperty("tpt_dcre")
    private Date tptDcre;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tpt_dmod")
    @UpdateTimestamp
    @JsonProperty("tpt_dmod")
    private Date tptDmod;


    //--- ENTITY LINKS ( RELATIONSHIP ) ---\\
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="tpt_ucre_id", referencedColumnName="id")
	@JsonIgnore
    private Users createdBy;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="tpt_umod_id", referencedColumnName="id")
	@JsonIgnore
    private Users modifiedBy;

    /**
     * Constructor
     */
    public VlTopologyType() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS ---\\
    public Long getId() {
        return this.id;
    }

    public void setId( Long id ) {
        this.id = id ;
    }

    public String getTptType() {
        return this.tptType;
    }

	public void setTptType( String tptType ) {
        this.tptType = tptType ;
    }

    public String getTptRequiredFields() {
        return this.tptRequiredFields;
    }

	public void setTptRequiredFields( String tptRequiredFields ) {
        this.tptRequiredFields = tptRequiredFields ;
    }

    public Boolean getTptValid() {
        return this.tptValid;
    }

	public void setTptValid( Boolean tptValid ) {
        this.tptValid = tptValid ;
    }

    public Date getTptDcre() {
        return this.tptDcre;
    }

	public void setTptDcre( Date tptDcre ) {
        this.tptDcre = tptDcre ;
    }

    public Date getTptDmod() {
        return this.tptDmod;
    }

	public void setTptDmod( Date tptDmod ) {
        this.tptDmod = tptDmod ;
    }

    //--- GETTERS AND SETTERS FOR LINKS ---\\
    public Users getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(Users createdBy) {
        this.createdBy = createdBy;
    }

    public Users getModifiedBy() {
        return this.modifiedBy;
    }

    public void setModifiedBy(Users modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

}
