/*
 * Created on 2023-05-15 ( 11:14:14 )
 * Generated by TelosysTools with the custom VEOLIA template
 */
package com.veolia.nextcanope.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import jakarta.persistence.*;

/**
 * JPA entity class for "WorkorderTaskReason"
 *
 * @author VEOLIA
 *
 */
@Entity
@Table(name="workorder_task_reason", schema="nomad" )
public class WorkorderTaskReason implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="wtr_code", nullable=false, length=2147483647)
    private String wtrCode ;

    @Column(name="wtr_slabel", nullable=false, length=2147483647)
    private String wtrSlabel ;

    @Column(name="wtr_llabel", length=2147483647)
    private String wtrLlabel ;

    @Column(name="wtr_valid")
    private Boolean wtrValid ;

    @Column(name="wtr_work_request")
    private Boolean wtrWorkRequest ;

    @Column(name="wtr_report")
    private Boolean wtrReport ;

    @Column(name="wtr_wo")
    private Boolean wtrWo ;

    @Column(name="wtr_task")
    private Boolean wtrTask ;

    @Column(name="wtr_ucre_id")
    private Long wtrUcreId ;

    @Column(name="wtr_umod_id")
    private Long wtrUmodId ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="wtr_dcre")
    private Date wtrDcre ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="wtr_dmod")
    private Date wtrDmod ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="wtr_umod_id", referencedColumnName="id", insertable=false, updatable=false)
    private Users modifiedBy ; 

    @ManyToOne
    @JoinColumn(name="wtr_ucre_id", referencedColumnName="id", insertable=false, updatable=false)
    private Users createdBy ; 

    @OneToMany(mappedBy="workorderTaskReason")
    private List<Task> listOfTask ; 

    @OneToMany(mappedBy="workorderTaskReason")
    private List<Workorder> listOfWorkorder ; 

    @OneToMany(mappedBy="workorderTaskReason")
    private List<AstWtr> listOfAstWtr ; 


    /**
     * Constructor
     */
    public WorkorderTaskReason() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    public void setWtrCode( String wtrCode ) {
        this.wtrCode = wtrCode ;
    }
    public String getWtrCode() {
        return this.wtrCode;
    }

    public void setWtrSlabel( String wtrSlabel ) {
        this.wtrSlabel = wtrSlabel ;
    }
    public String getWtrSlabel() {
        return this.wtrSlabel;
    }

    public void setWtrLlabel( String wtrLlabel ) {
        this.wtrLlabel = wtrLlabel ;
    }
    public String getWtrLlabel() {
        return this.wtrLlabel;
    }

    public void setWtrValid( Boolean wtrValid ) {
        this.wtrValid = wtrValid ;
    }
    public Boolean getWtrValid() {
        return this.wtrValid;
    }

    public void setWtrWorkRequest( Boolean wtrWorkRequest ) {
        this.wtrWorkRequest = wtrWorkRequest ;
    }
    public Boolean getWtrWorkRequest() {
        return this.wtrWorkRequest;
    }

    public void setWtrReport( Boolean wtrReport ) {
        this.wtrReport = wtrReport ;
    }
    public Boolean getWtrReport() {
        return this.wtrReport;
    }

    public void setWtrWo( Boolean wtrWo ) {
        this.wtrWo = wtrWo ;
    }
    public Boolean getWtrWo() {
        return this.wtrWo;
    }

    public void setWtrTask( Boolean wtrTask ) {
        this.wtrTask = wtrTask ;
    }
    public Boolean getWtrTask() {
        return this.wtrTask;
    }

    public void setWtrUcreId( Long wtrUcreId ) {
        this.wtrUcreId = wtrUcreId ;
    }
    public Long getWtrUcreId() {
        return this.wtrUcreId;
    }

    public void setWtrUmodId( Long wtrUmodId ) {
        this.wtrUmodId = wtrUmodId ;
    }
    public Long getWtrUmodId() {
        return this.wtrUmodId;
    }

    public void setWtrDcre( Date wtrDcre ) {
        this.wtrDcre = wtrDcre ;
    }
    public Date getWtrDcre() {
        return this.wtrDcre;
    }

    public void setWtrDmod( Date wtrDmod ) {
        this.wtrDmod = wtrDmod ;
    }
    public Date getWtrDmod() {
        return this.wtrDmod;
    }

    //--- GETTERS FOR LINKS
    public Users getModifiedBy() {
        return this.modifiedBy;
    } 

    public Users getCreatedBy() {
        return this.createdBy;
    } 

    public List<Task> getListOfTask() {
        return this.listOfTask;
    } 

    public List<Workorder> getListOfWorkorder() {
        return this.listOfWorkorder;
    } 

    public List<AstWtr> getListOfAstWtr() {
        return this.listOfAstWtr;
    } 


}
